### ISSUE TITLE
Using parmed to create openMM system with CHARMM parameters: E14FAC does not scale chargeProd

### ISSUE THREAD

**Issue by wiederm** [ParmEd/ParmEd#1017]
Hi!

First of all: thank you so much for developing parmed! This is such a great and helpful tool!
I came across some unexpected behavior reading in CHARMM parameter files and creating a openMM system (and I am not sure if the problem is on parmed or openMM side I must admit). The CHARMM non bonded parameter statement allows to scale the 1-4 LJ interactions with the E14FAC key word. As far as I see it this is not used in the openMM exceptions to scale the chargeProd (1-4 epsilon scaling works).

An example input file to reproduce this is attached. An example output for a single exception and the two corresponding atoms is (in this case epsilon is scaled by 0.5):

Parameters for 1: charge: 0.03145 e sigma: 0.2649532787749369 nm epsilon: 0.06568879999999999 kJ/mol
Parameters for 5: charge: 0.03145 e sigma: 0.2649532787749369 nm epsilon: 0.06568879999999999 kJ/mol
Parameters for 14Scaling: chargeProduct: 0.0009891025 e**2 sigma: 0.26495327877493696 nm epsilon: 0.032844399999999996 kJ/mol

[parmed-charmm.zip](https://github.com/ParmEd/ParmEd/files/2569469/parmed-charmm.zip)

**Comment by swails** [comment]
You appear correct. Thanks for the report.

**Comment by swails** [comment]
I've looked at this more.  e14fac is *only* for electrostatic interactions.  You can go to https://www.charmmtutorial.org/index.php/The_Energy_Function (unfortunately their certificate is invalid, but you don't need to send any data so it's safe to allow the invalid cert and view the page).  The section on Non-bonded exclusions expands on this a little bit.  CHARMM allows electrostatics to be scaled, but 1-4 Lennard-Jones interactions utilize completely distinct pairwise parameters compared to the "standard" L-J parameters between atom type pairs.

This is infinitely more flexible than "scaling".  It's also trivial to implement scaling using this approach -- all you have to do is divide the epsilon by the scaling factor, and you're done.  That's exactly how the Amber force field is "ported" to CHARMM.

ParmEd is actually smart enough to do this as well.  You can see that [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/parameters.py#L1151-L1159) where the epsilon value is divided by scnb when writing out the 1-4 terms.

I'm going to go ahead and close this since ParmEd has always treated this correctly.
