### ISSUE TITLE
OpenMM to Parmed to Gromacs Errors

### ISSUE THREAD

**Issue by nividic** [ParmEd/ParmEd#1030]
Hi There,

I’m trying to convert an OpenMM system to Gromacs files by using Parmed without success. The system is the Lysozyme protein solvated in water. I’ve attached all the required files to attempt the conversion and the related python script. I’m using Parmed 3.1.0 and OpenMM 7.3.0 in python 3.6.6. 

If I use the flag `rigidWater=True` in the OpenMM system creation, the parmed gromacs conversion generates the error:

`Traceback (most recent call last):
  File "omm_par.py", line 23, in <module>
    pmd_structure.save("SYSTEM.top", overwrite=True)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.6/site-packages/parmed/structure.py", line 1485, in save
    s.write(fname, **kwargs)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.6/site-packages/parmed/gromacs/gromacstop.py", line 1642, in write
    parameters == 'inline')
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.6/site-packages/parmed/gromacs/gromacstop.py", line 2040, in _write_molecule
    raise GromacsError('Cannot determine SETTLE geometry') # pragma: no cover
parmed.exceptions.GromacsError: Cannot determine SETTLE geometry`

If I switched the flag to `rigidWater=False` I'm getting the error:

`Traceback (most recent call last):
  File "omm_par.py", line 24, in <module>
    pmd_structure.save("SYSTEM.gro", overwrite=True)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.6/site-packages/parmed/structure.py", line 1478, in save
    gromacs.GromacsGroFile.write(self, fname, **kwargs)
  File "/Users/gcalabro/local/miniconda3/envs/openeye_data_record/lib/python3.6/site-packages/parmed/gromacs/gromacsgro.py", line 303, in write
    raise Exception("Could not find %s" % atom)
Exception: Could not find <Atom O [0]; In HOH 0>` 

I've also tried to downgrade Parmed to 3.0.1. In this case the last conversion (`rigidWater=False`) seems to work but the produced gromacs files are not recognized by gromacs, in this case if I run the gromacs system command:

`gmx grompp -f min.mdp -c SYSTEM.gro -p SYSTEM.top -o test.tpr`

I’m getting the gromacs error:

`ERROR 1 [file SYSTEM.top, line 23]:
  Atom type names can't be single digits.
`

I've attached the files to reproduce the issue. Thanks a lot for your help.

[parmed_test.zip](https://github.com/ParmEd/ParmEd/files/2809159/parmed_test.zip)

**Comment by nividic** [comment]
...So here what I have found so far debugging Parmed for the SETTLE bug (I generated a system with just one water molecule to help the debugging (files attached)). 

In order to create the Parmed structure from OpenMM, Parmed loops over the OpenMM forces (https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L158-L184).

Suppose that we have one rigid water molecule when the previous loop encounters an HarmonicAngleForce if the water is rigid the call https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L216 is never executed (`force.getNumAngles()` = 0) and no angles are added to the Parmed structure. 
As consequence the SETTLE section https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L2034 fails

[water_system.zip](https://github.com/ParmEd/ParmEd/files/2809968/water_system.zip)

**Comment by swails** [comment]
I have a vague recollection of adding support for reading an OpenMM System object back into a `Structure`, and this issue in particular.  The problem with OpenMM is that constrained degrees of freedom in general have all of their forces _removed_.

Unfortunately that means that this information is effectively lost from the parameter/topology file.  Setting `rigidWater=False` and creating a system without any constraints should ensure that all parameters are added to the `System`, and is definitely the best practice if you ultimately plan to translate that _back_ to some other format through ParmEd.

It is probably worth adding a note in the documentation that converting from OpenMM should be done from a `System` sans constraints.  Otherwise I'll need to add some guesswork to make sure it does the right thing with respect to other programs (and really it _can't_ be translated to other programs that specify whether constraints are active via the input file rather than the parameter/topology files).

**Comment by nividic** [comment]
Thank you so much for your prompt reply. So, this problem seems to be more a “design” choice…on one side OpenMM remove forces that are useless along a MD run and on the other side this is an MD running detail, the ff parameters should still be there and I can understand your point. 
I do not have any problem to set `ridigwater=False` in the end I’m interested to have the Gromacs files. 

However, two other problems need to be faced, one seems to go away downgrading ParmEd while the other needs to be addressed in any case (Atom type names can't be single digits). In this last case I advise to use a combination of element atom name and integer to form the Gromacs atom type and not just integers. 

In the end I want to thank you for ParmEd, we are currently using it in the OpenEye cloud computing platform (Orion) to perform MD and try to support interoperability between different MD engines. 

Best,
Gaetano

**Comment by swails** [comment]
Sorry for the delay, but I finally found the problem!

Here is the Python script you had:

```python
from simtk.openmm.app import PDBFile, ForceField

from simtk import unit

from simtk.openmm import app

import parmed

print('Reading the PDB file')
pdb = PDBFile("system.pdb")

print('Reading the force field')
ff = ForceField('amber99sb.xml', 'tip3p.xml')

print('Creating the system')
omm_system = ff.createSystem(pdb.topology,
                             nonbondedCutoff=1*unit.nanometer,
                             nonbondedMethod=app.PME,
                             constraints=None,
                             rigidWater=False)


print('Creating a structure from the OpenMM objects')
pmd_structure = parmed.openmm.load_topology(pdb.topology, system=omm_system, xyz=pdb.positions)


print('Saving GROMACS files')
pmd_structure.save("SYSTEM.top", overwrite=True)
pmd_structure.save("SYSTEM.gro", overwrite=True)
```

I added some printing and turned off constraints (just to make sure that all parameters will be present).

The root of the problem derives from the fact that you used an OpenMM-generated `Topology` object instead of a ParmEd-generated one.  In OpenMM, the PDB parser assigns atom IDs as the string of the atom number, while ParmEd casts them to an integer.  The ParmEd converter from OpenMM objects to its internal representation (which it can use to write any other file format) defers the assignment of atom types until it assigns nonbonded parameters if the atom types were assigned by a file format that doesn't encode that information.  It determines this by checking if the "id" attribute is an integer.  For ParmEd-generated topologies, it's always an integer.  For OpenMM-generated ones, it's always a string.

This information is necessary to writing GROMACS gro files, since it needs to split the system into molecules the same way it does for topology files so it can ensure the atoms appear in the correct order.

The solution is to use `parmed.load_file` instead of `PDBFile` from OpenMM.  Change your script to the following:

```python
from simtk.openmm.app import ForceField

from simtk import unit

from simtk.openmm import app

import parmed

print('Reading the PDB file')
pdb = parmed.load_file("system.pdb")

print('Reading the force field')
ff = ForceField('amber99sb.xml', 'tip3p.xml')

print('Creating the system')
omm_system = ff.createSystem(pdb.topology,
                             nonbondedCutoff=1*unit.nanometer,
                             nonbondedMethod=app.PME,
                             constraints=None,
                             rigidWater=False)


print('Creating a structure from the OpenMM objects')
pmd_structure = parmed.openmm.load_topology(pdb.topology, system=omm_system, xyz=pdb.positions)


print('Saving GROMACS files')
pmd_structure.save("SYSTEM.top", overwrite=True)
pmd_structure.save("SYSTEM.gro", overwrite=True)
```

I'll issue a pull request to make this conversion more friendly to OpenMM `Topology` objects.  Note though that it will always be more robust to use ParmEd's parsers and objects, since those are the only ones that are really developed for consistency across all of the functionality.

**Comment by xiki-tempula** [comment]
Sorry, I wonder what is the current recommanded way of loading the openMM topology file?
I'm trying to convert the openMM topology to gromacs topplogy and it doesn;t seems to work

    top = pmd.load_file('lig.offxml')
    top.save('lig.top')

**Comment by swails** [comment]
Can you open a new issue?  Adding it here just hides it (and the issue is already closed).
