### ISSUE TITLE
charmm parameters to openmm

### ISSUE THREAD

**Issue by sawstory** [ParmEd/ParmEd#1056]
Hi
can you please guide me how to convert charmm parameter files to openmm force field so I can use pdb choice in openmm-setup instead of the charmm option that require psf file that I get through vmd and crd file that I get from Discovery studio and the topology and parameter files, all that cause a lot of error so I wonder if I can get help to convert the attached file parameter file and merge it with openmm built in charmm36.
Peter Eastman from openmm forum told me to use ParmEd to do that but after 1 week I still dont know how :(
All the best
[Parameter file for cobalamins.prm.TXT](https://github.com/ParmEd/ParmEd/files/3332559/Parameter.file.for.cobalamins.prm.TXT)

Omar

**Comment by swails** [comment]
Hi Omar,

Sorry for the delay in getting back to you.  Please have a look at https://github.com/choderalab/openmm-forcefields, which should make this task much easier.  It uses ParmEd under the hood to do the conversions, but it will handle all of the boilerplate code that you would otherwise have to write.

Tagging @jchodera so that he can correct me if that repository is outdated as far as converting force fields to OpenMM format (from CHARMM or AMBER).

Good luck!
Jason

**Comment by Panda-DaLong** [comment]
I encountered the same problem.

Have you solved it?
