### ISSUE TITLE
boxsize modification amber

### ISSUE THREAD

**Issue by davidRFB** [ParmEd/ParmEd#1137]
Hi ! 

I am working with parmed to modify an amber topology boxsize. I use this simple script
```

import parmed as pmd
am=pmd.load_file("complex.prmtop","complex_solv.crd")
am.box[:3]=am.box[:3]-3
am.save("complex_f.prmtop",format="amber")
am.save("complex.crd",format="rst7") 
```

but the box size in the topology is not modified : 
complex.prmtop : 
%FLAG BOX_DIMENSIONS                                                            
%FORMAT(5E16.8)                                                                 
  9.00000000E+01  8.40849650E+01  8.35178610E+01  8.38039010E+01

complex_f.prmtop:
%FORMAT(5E16.8)
  9.00000000E+01  8.40849650E+01  8.35178610E+01  8.38039010E+01

while the complex_solv.crd does have the box modification : 

complex_solv.crd ( last line)
  84.0849650  83.5178610  83.8039010  90.0000000  90.0000000  90.0000000
complex.crd (last line)
  81.0849650  80.5178610  80.8039010  90.0000000  90.0000000  90.0000000

So I do not know why this happen o how could I do this operation. 
Thank you very much.

**Comment by swails** [comment]
The box size in the prmtop file isn't used - it's the box size in the coordinate file that is used in simulations.

**Comment by swails** [comment]
I'm going to close this because it's not a problem.  The box size in the prmtop file has never been changed traditionally which has never mattered since the box size that's used is stored in the coordinate file.

This is as it should be since NpT simulations alter the box size during the simulation, and the only place that information could be written to is the restart (coordinate) file.
