### ISSUE TITLE
Support for GROMACS nrexcl=2 topology conversion to AMBER prmtop

### ISSUE THREAD

**Issue by joezwu** [ParmEd/ParmEd#1161]
Hello!

I am writing to inquire on whether there may be plans to include 1-3 non-bonded interactions in the Parmed code when needing to convert GROMACS topology with `nrexcl=2` to AMBER prmtop. Right now, Parmed does not support `nrexcl=2`, so I would need to modify all GROMACS itp files from `nrexcl=2` to `nrexcl=3`, and then post-process to add 1-3 and 1-4 non-bonded interactions back into the topology. 

I look forward to hearing back, thank you!

Best,
Joe

**Comment by swails** [comment]
It's not ParmEd that doesn't support `nrexcl=2`, it's Amber.  The nrexcl=3 assumption is baked into the entire Amber ecosystem.  The bonds, angles, and torsions actually double as the exclusion and exception lists so that you can't have an angle term *and* compute a nonbonded interaction (scaled or not) between them.

There is potentially a way to hack this that would work for many topologies (but not all) - and that would require adding torsions with 0-force constants where the 1-4 atoms are involved in an angle (like 5-membered rings), then labeling that dihedral as one where end-group nonbonded interactions need to be computed.  But that also requires having at least 4 atoms available in your exclusion set to form torsions between, and I'm simply not sure how or whether that would even really work.

And this is just for `nrexcl=2`.  nrexcl>3 is easier to support because you're not trying to create torsions between <4 atoms, but it would still require a fairly substantial amount of bookkeeping changes, and the resulting topology file would be completely broken in terms of its topology (no program will recognize that the torsion list has been hijacked for its nonbonded exception handling).

-------

The above discussion assumes that nrexcl=2 has exceptions between 1-3 pairs rather than hard exclusions (the difference being that an exception is a "modified" nonbonded interaction, such as a scaled interaction or different parameters).  If nrexcl=2 uses hard exclusions, then it is equivalent to nrexcl=3 with scaling factors of 1.0 for both electrostatics and Lennard-Jones.

**Comment by joezwu** [comment]
Thank you Jason, that was a fantastic explanation, and extremely useful advice/suggestion--much appreciated!
