### ISSUE TITLE
Fix charge on residue template and update a system

### ISSUE THREAD

**Issue by Dan-Burns** [ParmEd/ParmEd#1191]
Hello,

I created a system in openmm and then loaded the topology into parmed.  I used parmed.modeller.ResidueTemplate.from_residue to fix_charges on a residue. 
How do I update my openmm system with the adjusted charges?

Thank you,

Dan

**Comment by swails** [comment]
There are two options:

1. Transfer the charges from the residue template back to the residue, then create the OpenMM System from there
2. Transfer the charges from the residue template directly to the OpenMM System.

The first option is considerably easier (the latter requires familiarity with the OpenMM API).  The first option would be something like:

```python
for template_atom, structure_atom in zip(template.atoms, structure.residues[residue_idx].atoms):
    structure_atom.charge = template_atom.charge
```

Hopefully this gives you some idea of how to get these charge tweaks.

Do you have a specific reason you want to do this?  The reason I added this function was because some file formats have fixed precision in their outputs, and if the printed numbers add up to a net non-integer charge, creating a system with lots of those residues can make that small error add up to a large value.  But that shouldn't be an issue if you already have the `Structure` and just want to create a system from it.

**Comment by Dan-Burns** [comment]
I have a modified DNA nucleotide.  When I add the methyl group to the forcefield the residue charge is no longer -1.  I needed to adjust the charges on the atoms so that the total charge is set back to -1.

Thank you for the example!

Dan

**Comment by swails** [comment]
I hope it helped!  I'm going to close assuming it's resolved.
