### ISSUE TITLE
Contributing a LAMMPS reader

### ISSUE THREAD

**Issue by orionarcher** [ParmEd/ParmEd#1204]
I am interested in contributing LAMMPS IO. This was suggested in issue #862, which was closed 2 years ago because at the time InterMol seemed to offer similar functionality. 

InterMol is awesome software but it seems to be abandonware. Issues are not being answered, PRs are not being tended to, and there has not been a release in a year. I've spent the past day trying to use InterMol to read a Lammps file, but it cannot correctly parse dihedrals of the `opls` format or impropers of the `cvff` format. As such, I believe the best solution is to use InterMol code (licensed under MIT) to construct LAMMPS IO in ParmEd.

I'd love to hear feedback from developers on this idea. If there is a better alternative for Lammps IO, that'd be great.

**Comment by mrshirts** [comment]
So, a comment.  InterMol is nearly abandonware (there will be no more releases, I think), but part of the reason is the eventual release of https://github.com/openforcefield/openff-interchange.  Jason can speak up, but I doubt there will be ParmEd support for LAMMPS, because further development of ParmEd beyond bugfixes is not likely to happen. 

The eventual vision is that Interchange can be hooked up to readers from most codes, as Interchange is being designed with a very simple and transparent API.  Readers adapted from InterMol will likely be relatively easy to construct. 

The other thing to look at to see if it meets your needs is https://github.com/mosdef-hub/gmso/, that likely has better support for lammps that intermol right now (but might do different things).

**Comment by mrshirts** [comment]
> I am now considering abandoning my OPLS force fields and switching entirely to the OpenFF / OpenMM ecosystem and using the Sage FF.

Well, I think Sage should work as well or better than OPLS, but I'm biased as one of the OpenFF PIs . . .
