### ISSUE TITLE
Save the dihedral section that is not present in the original topology

### ISSUE THREAD

**Issue by xiki-tempula** [ParmEd/ParmEd#1245]
I have two topologies.
One only has proper torsion.
The other has improper torsion and rb type torsion.
I would like to switch the torsion from the second topology to the first topology.
I was thinking something along the lines of 

```
    top_1 = pmd.load_file(top_1_file)
    top_2 = pmd.load_file(top_2_file)
    top_1.rb_torsion_types = top_2.rb_torsion_types
    top_1.rb_torsions = top_2.rb_torsions
    top_1.improper_types = top_2.improper_types
    top_1.impropers = top_2.impropers
    top_1.dihedral_types = top_2.dihedral_types
    top_1.dihedrals = top_2.dihedrals
    top_1.save('topol.top')
```
However, it seems that the `improper torsion` and `rb type torsion`, which are not present in the top_1 is not in the file 'topol.top'.

**Comment by swails** [comment]
You can't really do this.  The torsions reference the type instances directly, and just replacing the lists won't re-associate the torsion types with the torsions from the new lists.

I'm not sure exactly what you're trying to do and why...

**Comment by xiki-tempula** [comment]
@swails I'm thinking of doing an unpopular thing. 
I have a custom force field that does well in dihedrals but not very good at bond and angle.
The general force field have good bond and angle but the dihedral are not so well.
So I was thinking of combining the best of both world use bond and angle from one topology and dihedral from the other.

**Comment by swails** [comment]
This assumes that all of the valence terms are orthogonal -- that is the bond, angle, and torsional energy profiles are independent of the parameters in the other terms.  While I've never actually done this test myself, there's no reason to think it would be true.

This is a long way of saying that force fields cannot be naively mixed-and-matched this way, as the derivation of every parameter is impacted by every other parameter in the force field.

----

But as for what you're trying to do with ParmEd, it's impossible.  If I had to describe what ParmEd does in one word, that one word is "bookkeeping".  It keeps track of topology and topology assignments.  While my approach to bookkeeping in ParmEd has worked (surprisingly) well for many common applications, what you are trying to do (at least the way you're trying to do it) breaks every core assumption upon which the ParmEd bookkeeping system is built.  Supporting it would require a 100% rewrite of the entire library which will definitely not happen in this project.

And besides, there's a *lot* of work that would be required to prove it's actually a good idea 😃.  I'm going to go ahead and close this since it's impossible by ParmEd's design.
