### ISSUE TITLE
ImportError when creating system with rst7 and parm7 files

### ISSUE THREAD

**Issue by slweng0321** [ParmEd/ParmEd#1291]
Dear all,
I try to create system with the Amber input rst7 and parm7 file via the following script:
```python
system = fus.createSystem(nonbondedMethod=PME,
nonbondedCutoff=1.0nanometer, constraints=app.HBonds,
hydrogenMass=1.5amu,
)
```

I receive the error:
```
Traceback (most recent call last):
File "//openmm.py", line 29, in
system = fus.createSystem(nonbondedMethod=PME,
File "//amber22/lib/python3.9/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed
```
I used Platform.getOpenMMVersion() to check OpenMM version and it is 7.6.
How can I fix this problem? Thanks for any help.

**Comment by swails** [comment]
This error message is misleading, and is from an old version of ParmEd.  The version of ParmEd that you're using doesn't work with OpenMM 7.6 (you must use 7.5).

I would recommend upgrading ParmEd and using the latest release (version 4).  Then your script should work.

**Comment by swails** [comment]
The error message you're seeing is a result of ParmEd being unable to import `simtk.openmm.app.internal.unitcell`, which was first introduced in OpenMM version 6.3 (long, long ago).

However, in OpenMM 7.6, the top level import was renamed from `simtk` to just `openmm`, so ParmEd *is* unable to import `simtk.openmm.app.internal.unitcell`, leading it to (mistakenly) believe that the OpenMM version is too old (when in fact it's too new).

ParmEd has long since been upgraded to work with OpenMM 7.6, but the version you have installed with Amber is too old.  If it's easier to install an older OpenMM, you can do that.  Otherwise, you will need to install an upgraded version of ParmEd instead.

**Comment by slweng0321** [comment]
@swails I installed the newer version of ParmEd and it seems to work. Thanks!
