### ISSUE TITLE
Rosetta prolines not compatible with OpenMM

### ISSUE THREAD

**Issue by cxhernandez** [ParmEd/ParmEd#131]
Was trying to solvate a system I made in Rosetta, using the AMBER99SBildn forcefield in OpenMM, when I got this error:

``` python
In [82]: mod = solvate(s.positions, s.topology, ff, 0.1, padding=1.0, model='tip3p')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-82-47afa158ec15> in <module>()
----> 1 mod = solvate(s.positions, s.topology, ff, 0.1, padding=1.0, model='tip3p')

/home/cxh/anaconda/lib/python2.7/site-packages/mdcookbook-0.1-py2.7.egg/mdcookbook/core.pyc in solvate(positions, topology, forcefield, ion_content, boxSize, padding, model)
    124     modeller.addSolvent(forcefield, model='tip3p', padding=padding*nanometers,
    125                         boxSize=boxSize, positiveIon='Na+', negativeIon='Cl-',
--> 126                         ionicStrength=ion_content*molar)
    127     return modeller
    128

/home/cxh/anaconda/lib/python2.7/site-packages/simtk/openmm/app/modeller.pyc in addSolvent(self, forcefield, model, boxSize, padding, positiveIon, negativeIon, ionicStrength)
    315         # Have the ForceField build a System for the solute from which we can determine van der Waals radii.
    316
--> 317         system = forcefield.createSystem(self.topology)
    318         nonbonded = None
    319         for i in range(system.getNumForces()):

/home/cxh/anaconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.pyc in createSystem(self, topology, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, removeCMMotion, hydrogenMass, **args)
    377                             break
    378                 if matches is None:
--> 379                     raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
    380                 matchAtoms = dict(zip(matches, res.atoms()))
    381                 for atom, match in zip(res.atoms(), matches):

ValueError: No template found for residue 6 (PRO).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```

**Comment by cxhernandez** [comment]
Seems like not all the bonds are being made from proline:

``` python
>>> [bond for bond in s.bonds 
        if bond.atom1.residue.name == "PRO" 
        or bond.atom2.residue.name == "PRO"]
[<Bond <Atom C [55]; In GLN 4>--<Atom N [70]; In PRO 5>; type=None>,
 <Bond <Atom N [70]; In PRO 5>--<Atom CA [71]; In PRO 5>; type=None>,
 <Bond <Atom CA [71]; In PRO 5>--<Atom C [72]; In PRO 5>; type=None>,
 <Bond <Atom C [72]; In PRO 5>--<Atom O [73]; In PRO 5>; type=None>,
 <Bond <Atom CA [71]; In PRO 5>--<Atom CB [74]; In PRO 5>; type=None>,
 <Bond <Atom CB [74]; In PRO 5>--<Atom CG [75]; In PRO 5>; type=None>,
 <Bond <Atom N [70]; In PRO 5>--<Atom CD [76]; In PRO 5>; type=None>,
 <Bond <Atom CG [75]; In PRO 5>--<Atom CD [76]; In PRO 5>; type=None>,
 <Bond <Atom CA [71]; In PRO 5>--<Atom HA [78]; In PRO 5>; type=None>,
 <Bond <Atom CB [74]; In PRO 5>--<Atom 1HB [79]; In PRO 5>; type=None>,
 <Bond <Atom CB [74]; In PRO 5>--<Atom 2HB [80]; In PRO 5>; type=None>,
 <Bond <Atom CG [75]; In PRO 5>--<Atom 1HG [81]; In PRO 5>; type=None>,
 <Bond <Atom CG [75]; In PRO 5>--<Atom 2HG [82]; In PRO 5>; type=None>,
 <Bond <Atom CD [76]; In PRO 5>--<Atom 1HD [83]; In PRO 5>; type=None>,
 <Bond <Atom CD [76]; In PRO 5>--<Atom 2HD [84]; In PRO 5>; type=None>,
 <Bond <Atom C [72]; In PRO 5>--<Atom N [85]; In MET 6>; type=None>]
```

This is on 16 bonds, where OpenMM is expect 20.

**Comment by swails** [comment]
It looks to me like every bond that *should* be there is.  And if you look at the `PRO` residue definition in `ff99sbildn.xml` you see only 16 bonds:

```xml
  <Residue name="PRO">
   <Atom name="N" type="278"/>
   <Atom name="CD" type="279"/>
   <Atom name="HD2" type="280"/>
   <Atom name="HD3" type="280"/>
   <Atom name="CG" type="281"/>
   <Atom name="HG2" type="282"/>
   <Atom name="HG3" type="282"/>
   <Atom name="CB" type="283"/>
   <Atom name="HB2" type="284"/>
   <Atom name="HB3" type="284"/>
   <Atom name="CA" type="285"/>
   <Atom name="HA" type="286"/>
   <Atom name="C" type="287"/>
   <Atom name="O" type="288"/>
   <Bond from="0" to="1"/> # 1
   <Bond from="0" to="10"/> # 2
   <Bond from="1" to="2"/> # 3
   <Bond from="1" to="3"/> # 4
   <Bond from="1" to="4"/> # 5
   <Bond from="4" to="5"/> # 6
   <Bond from="4" to="6"/> # 7
   <Bond from="4" to="7"/> # 8
   <Bond from="7" to="8"/> # 9
   <Bond from="7" to="9"/> # 10
   <Bond from="7" to="10"/> # 11
   <Bond from="10" to="11"/> # 12
   <Bond from="10" to="12"/> # 13
   <Bond from="12" to="13"/> # 14
   <ExternalBond from="0"/> # 15 (external)
   <ExternalBond from="12"/> # 16 (external)
  </Residue>
```

Just looking at them, the bonds *look* right.  I suspect the real issue are the atom names.  In particular, it looks like Rosetta is applying the old atom naming scheme from the PDB v.2 standard -- `1HD` instead of the PDB v.3 standard `HD1`

**Comment by swails** [comment]
Actually, `1HD` -> `HD2` and `2HD` -> `HD3`

Amber names (both residue and atom) follow the PDB standard as much as they can (Amber requires a unique mapping of residue name to tautomer, so HIS can only represent 1 of the 3 main tautomers/protomers, for example).  Rosetta seems to be violating this standard.

**Comment by hainm** [comment]
@cxhernandez: if you don't need to make things to  be consistent with your previous simulations, I highly recommend to use `ff14SB` rather using `AMBER99SBildn` since `ff14SB` has better balance for alpha, beta and PP2.

Hai

**Comment by swails** [comment]
Oh man, I misread your second comment.

> The one caveat is that once Structure.topology is called it seems like the topology attribute is permanently set. @swails: is there anyway to update the OpenMM topology, in case I change the number of atoms, bonds, etc. within the Structure class?

Creating a Topology instance isn't particularly cheap, so `Structure` caches an instance of it.  However, one of the principal features of ParmEd (and `Structure` in particular) is that it is supposed to take care of the bookkeeping stuff like this for you.  If you look at the start of the `topology` descriptor ([here](https://github.com/ParmEd/ParmEd/blob/master/chemistry/structure.py#L1108-L1127)) you'll see that the cached `_topology` is only returned if `is_changed()` is `False`.

The `TrackedList` class, which is a `list` subclass making up every list-like attribute of `Structure`, overrides the `list` methods to indicate that a particular method "changes" the underlying list -- this knowledge is passed up to `Structure` via `is_changed()`, so cached objects should get discarded when this is the case.

It turns out that, since I never use `list.remove`, I forgot to tag that as a list-changing method.  This is fixed in #132.  In the meantime, may I suggest using `Structure.strip` instead:

```Python
def rmNV(s):
    s.strip([atom.name == 'NV' for atom in s.atoms])
    return s
```

Another few comments: deleting an atom from `struct.atoms` also removes it from its containing residue, and triggers `atoms.changed` to `True` (which bubbles up to `struct.is_changed()`).  And in methods that require knowledge of the whole topology (like `createSystem` or `topology`), all "empty" terms (i.e., terms containing atoms that have been deleted from the structure) are removed from their lists (so you never needed to touch the list of bonds at all).

The reason you were having troubles here is that `remove` wasn't doing the right thing on the AtomList.

**Comment by swails** [comment]
I think @hainm is correct in that ff14SB has demonstrably better performance overall than 99SBildn (not sure if the Simmerling lab's paper on 14SB is out yet...)

That said, OpenMM doesn't have ff14SB, so that's not really an option at this point.  Adding it to OpenMM is on my (very long) to-do list.

**Comment by hainm** [comment]
@swails: the 14SB paper just got its first review. Hopefully it will be a available soon (took so long :D).

**Comment by cxhernandez** [comment]
@swails: Thanks for all the tips! Everything seems to be working just fine now!

@hainm: Unfortunately, I used 99SBildn for my initial simulations almost a year ago, so I want things to be consistent– but thanks for the recommendation, and I'll looking out for that paper!

**Comment by cxhernandez** [comment]
Just an after thought... should I include a note about this in the docs, @swails?

**Comment by swails** [comment]
Adding a note about prolines to the Rosetta docs would be a good idea.

The general info about bookkeeping and such I'll add in a bit more detail later.  Thanks!

**Comment by swails** [comment]
> Adding a note about prolines to the Rosetta docs would be a good idea.

Or whatever else you think is relevant to using Rosetta inside ParmEd that will help users (e.g., me :)).

**Comment by cxhernandez** [comment]
Notwithstanding some sort of PyRosetta tutorial (which I'd be more than happy to write-up), I think this is it really. The structure object makes it really easy to port everything into OpenMM :smile:

Somewhat unrelated: I'm inclined to contact someone in the Baker, Gray, or Das labs to see if they might be able to help with extracting CHARMM parameters into ParmEd. Would you be interested in this functionality?

**Comment by swails** [comment]
ParmEd can already read CHARMM parameters (in the CHARMM parameter file format): see [here](https://github.com/ParmEd/ParmEd/blob/master/chemistry/charmm/parameters.py)

Or is this not what you meant?

**Comment by kyleabeauchamp** [comment]
Are you talking about the rosetta small molecule parameterization stuff?  It's not clear to me how robust that stuff is, as compared to their RNA and protein stuff...

**Comment by cxhernandez** [comment]
Sorry, I meant extract the CHARMM parameters from PyRosetta into ParmEd. I found this mysterious list of `properties` in PyRosetta's `AtomType` class, and I'm thinking these might correspond to different CHARMM parameters that Rosetta uses. But I haven't found any documentation that explains what each element in the list corresponds to.

**Comment by swails** [comment]
Sorry, I forgot I never responded here!

Yea -- any force field information that Rosetta makes available would be great to bring over to ParmEd.  There *should* be the infrastructure already in place to store that information.
