### ISSUE TITLE
Warning issues about converting gromacs top to Amber

### ISSUE THREAD

**Issue by aw10279** [ParmEd/ParmEd#1343]
Hi there, 
I got a warning when I tried to convert gromacs top to amber: 

GromacsWarning: 40 1-4 pairs were missing from the [ pairs ] section and were set to zero; make sure you know what you're doing! GromacsWarning).

When I run cp2k with this Amber top, I got a formating error. Then I tried to solve this issue according #1298 by using gromber and changing my script, unfortunatly they both didn't work. So I wonder if any other way to solve it, thank you.

my script:
import parmed as pmd
from parmed import gromacs
gromacs.GROMACS_TOPDIR = "/home/fyy/soft/gromacs2023/share/gromacs/top"
gmx_top = pmd.load_file('1.top', xyz='1.gro')
gmx_top.save('md.prm', format='amber')
gmx_top.save('md.crd', format='rst7')

my gromacs inputs:
[gromacs_files.zip](https://github.com/ParmEd/ParmEd/files/14754946/gromacs_files.zip)

**Comment by swails** [comment]
The warning is precisely that -- just a warning.  I *believe* that the default behavior for GROMACS is to treat these 1-4 pairs as explicit exclusions (same as being set to "0") rather than exceptions.

I would recommend running a single-point energy calculation with both Amber and GROMACS (using the same input coordinates) and compare the different components of the energy breakdown (in particular the electrostatic and nonbonded terms).  If the energies match, then the conversion was successful.

**Comment by aw10279** [comment]
> The warning is precisely that -- just a warning. I _believe_ that the default behavior for GROMACS is to treat these 1-4 pairs as explicit exclusions (same as being set to "0") rather than exceptions.
> 
> I would recommend running a single-point energy calculation with both Amber and GROMACS (using the same input coordinates) and compare the different components of the energy breakdown (in particular the electrostatic and nonbonded terms). If the energies match, then the conversion was successful.

Thank you very much for your reply, but I still have no idea about this issue. This convertion I made is to generate the input for cp2k, if this warning exists, the cp2k will report a error about formating. So I need a way to modify these  values of 1-4 pairs, what should I do for it?  @swails

**Comment by swails** [comment]
Run a single-point energy calculation with the converted Amber files and with the original GROMACS files.  If the energies match (they won't match *exactly*, but will very closely), then the conversion is fine and the warning can be ignored.

**Comment by aw10279** [comment]
> Run a single-point energy calculation with the converted Amber files and with the original GROMACS files. If the energies match (they won't match _exactly_, but will very closely), then the conversion is fine and the warning can be ignored.

However, it seems like that the error report for this issue can not be ignored, so I have to try some other ways to solve it. Thanks a lot for your kindness anyway！

**Comment by swails** [comment]
I wrote the code for the warning message (and it is a warning, *not* an error), so I know what it means.

If the energies match to within 0.01 relative error, then the conversion succeeded and you can use the files with confidence.

The warning is there to get you to actually run this comparison rather than simply take it on faith that the conversion worked correctly.

---

I'm going to close this issue since the question has been answered.
