### ISSUE TITLE
put `utils` in `chemistry` namespace?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#153]
hey man,

can you move the `utils` in tests folder to `chemistry` namespace? I want to test your files from `pytraj`.
https://github.com/ParmEd/ParmEd/blob/gromacs_support/test/test_chemistry_gromacs.py#L11
somethings like: 
```python
from chemistry.utils import get_fn # just like `mdtraj`
```

or 
```python
from chemistry.testing.datafiles import bla_bla
```
(oh wait, do you install test files with `chemistry`, or they are just in original folder?)

Hai

**Comment by hainm** [comment]
uhm, jus check your test/files folder: 137 MB. :D

**Comment by hainm** [comment]
and I have a quick question: Is there any format that `ParmEd` can read but cpptraj cannot? I just add code so that if cpptraj/pytraj failed loading file, ParmEd will be called to load and then `io.load_pseudo_parm(from_parmed_object`. 

I just need a test case if you have one.

Hai

**Comment by swails** [comment]
ParmEd does not install its test files.  As you've pointed out, the tests are too big.

**Comment by swails** [comment]
> and I have a quick question: Is there any format that ParmEd can read but cpptraj cannot?

Just the GRO file as far as I can tell (for now, anyway).  Look for any of the ".gro" files in the test directory (it is basically the Gromacs equivalent of an Amber restart file, crossed with a PDB file).  You can use it the same way as a PDB (i.e., both as a Topology and a coordinate frame).

**Comment by hainm** [comment]
@mojyt: do you have any comment about ".gro" file format? (your future plan, ...)

@swails 
>ParmEd does not install its test files. As you've pointed out, the tests are too big.

I see. I will set env for ParmEd.

**Comment by hainm** [comment]
@swails 

What do you think about creating alias for `ParmEd` test files? 
`MDAnalysis` has a test suite which is seperated from their main package. I can do this (and find it very convenient)

```python
from MDAnalysisTests.datafiles import PSF, DCD
```

`ParmEd` does not need to have a suite but it can search for data files in `$AMBERHOME`, in original `ParmEd` folder (in case downloading from git), from `$PARMEDHOME` if user set, ...
(of course ParmEd will raise Error if it can not find).

The motivation to do this is: I dont want to bother remember where are the files, what are their names, I could always look at `chemistry.tests.datafiles`. Or if I am using ipython-notebook, I just don't want to `cd some_place_where_parmed_is`.

btw, this suggestion is just for make things more convenient for testing (at least for myself :D). 

(I am thinking doing the same thing for `pytraj` and `pytraj` did have `cpptraj_test_dir` for search for cpptraj's tests)

Hai

**Comment by swails** [comment]
I'm not really sure how I feel about this.  I don't want to install the test files since they're so large. I also don't want to add code that depends on the source code directory.  In particular, this would break under any of the following conditions:

1. Someone moves their source code directory (or deletes it)
2. The test files are changed between when the user last installed ParmEd and when they last pulled changes
3. When someone uses `conda` (i.e., they never downloaded the source code).

It wouldn't surprise me for conda to be a common mode of installation in the future, and point 2 could result in errors that are *very* hard to decipher (mixing and matching versions has caused some of the most confounding debugging sessions I've done).

One thing you could do is add `/path/to/ParmEd/test` to `PYTHONPATH` and import `utils` that way...

**Comment by hainm** [comment]
I see.
