### ISSUE TITLE
more fancy slicing for structure

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#158]
what do you think?

```python
parm[[':10-20', ':8']]
```

which is equal to
```python
parm[':10-20']  + parm[':8']
```

I got this idea (which is similar to `pandas`) when I wanted to group DataSetList in `pytraj` with specific group of legends.
https://github.com/pytraj/pytraj/blob/master/tests/test_DataSetList_getitem_as_dict.py#L23

by the way, Amber mask is really flexible, `ParmEd` might not need above thing

```python
parm[':10-20 & :8']
```
Hai

**Comment by swails** [comment]
> what do you think?
> 
```
> parm[[':10-20', ':8']]
```
> which is equal to
> 
```
> parm[':10-20']  + parm[':8']
```

This is not at all intuitive to me.  And that syntax is already a name selection array (i.e., right now it will be interpreted as taking all atoms with names `':10-20'` and `':8'`).

> by the way, Amber mask is really flexible, ParmEd might not need above thing
> 
```
> parm[':10-20 & :8']
```

This is very different from your above proposal.  Your above proposal would take residues 10-20 and put them in a new structure, then add residue 8 on afterwards.  This later mask will select nothing.  Assuming you meant `':10-20 | :8'`, which will select residues 8 and 10-20, residue 8 will come at the beginning rather than the end.

I really don't think the syntax

```
parm[[mask1, mask2, mask3]]
```

is shorter than

```
parm[mask1] + parm[mask2] + parm[mask3]
```

in any meaningful way.  The latter syntax is explicit and tells you *exactly* what you are doing, and what will happen.  The former does not.  And the slicing/selection syntax is already bordering on too complicated, but there are, IMO, clear use cases and an intuitive interpretation for all of the selection modes that are supported right now.  Adding this would make the selection code more difficult to understand, write, and verify correctness and would make selection syntax more complicated.

**Comment by hainm** [comment]
you're right, @swails. 

Per `parm[[mask1, mask2, mask3]]`, I was thinking about speed (vs slice 3 times to create `Structure`).  By the way, thinking about speeding things up without benchmarking is evil. :D 

PS: yes I meant about `':10-20 | :8'`. 

Hai
