### ISSUE TITLE
template water molecule

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#164]
I am intending to make a Topology template for each water model for `pytraj` but I think it's more reasonable if `ParmEd` can be bundled with those templates.

something like
```python
from chemistry.amber.watermodels import TIP3P
import chemistry.amber.AmberParm as AP
tip3p = TIP3P()
# add many water
parm = AP()
for i in range(100):
    parm += tip3p
```

The combo of `ParmEd` (easy to build new Topology) and `pytraj` (easy to process/add/translate/rotate/)... coords will make things easier (such as building new molecules, add some waters to some locations, ...)

**Comment by davidlmobley** [comment]
I'm curious - are you thinking to use ParmEd to actually, for example, solvate systems (i.e. handling coordinates as well)?  Or are you just talking about adding water parameters to the topology?




Long-term, I would love to see ParmEd replace/extend tools we tend to use for that now - i.e. things like tleap, or GROMACS' `gmx solvate`, etc. I don't know if this is in the plans, though. It seems like a much bigger problem.





—

**Comment by hainm** [comment]
@davidlmobley  I am thinking about building both Topology by `ParmEd` and coords by [pytraj] (https://github.com/pytraj/pytraj). `pytraj` need a Topology to map atom and do other kind of meaningful things (translation, rotation, mask selection, ...). In the future, if `ParmEd` and `pytraj` developers are still active in dev, I think it's possible to replace current tools. And they are much more flexible (still fast) since they are in Python world.

Hai

**Comment by swails** [comment]
> Long-term, I would love to see ParmEd replace/extend tools we tend to use for that now - i.e. things like tleap, or GROMACS' `gmx solvate`, etc. I don't know if this is in the plans, though. It seems like a much bigger problem.

It's on the radar, not in the plans.  To be honest, I more see it as a back-end powering some other tools, like Chimera or PyMol (both Python-based).  GUI integration and scriptability are important in this kind of thing, and that is not something I'm knowledgeable enough in to warrant spending time doing it.  If someone else wants to that's great :).

For the time being, I want to focus on making ParmEd do what it already does better, and document it.

**Comment by swails** [comment]
@hainm -- It sounds like a reasonable proposal, and I'd be happy to review and accept any PR proposals.  Is this something you were interested in implementing?

If so, `amber` is the wrong namespace for this -- try `chemistry.modelling` instead.  Also, the code

```Python
from chemistry.amber.watermodels import TIP3P
import chemistry.amber.AmberParm as AP
tip3p = TIP3P()
# add many water
parm = AP()
for i in range(100):
    parm += tip3p
```

Is far more efficiently written as

```Python
from chemistry.amber.watermodels import TIP3P
import chemistry.amber.AmberParm as AP
tip3p = TIP3P()
# add many water
parm = AP() + tip3p * 100
```

Also, the resulting positions of replicated and added `Structure` instances is not defined formally by the API (it currently puts every duplicated atom in exactly the same place as it originally was).  I want the flexibility to change where the atoms are placed as the need arises.  For now, the addition and replication functionality was only added because the Gromacs parser required it.  And as a result, it only does what those parsers needed at a minimum.

**Comment by hainm** [comment]
@swails I will put this in my todo-list.

Hai

**Comment by hainm** [comment]
@swails  wha'ts about build single TIP3P.top molecule and load it to `parmed` when calling TIP3P(). I am not familiar enough with different parameters in Topology so I am not sure if this is stupid.

**Comment by swails** [comment]
Why not just defining a `Structure` instance with a parametrized TIP3P instead?  It shouldn't be too hard -- just add 3 atoms with appropriate charges and masses to a single residue and the corresponding bonds (with bond strengths).  Then it can just be a regular object rather than a function.

I don't have any use for this myself.

**Comment by hainm** [comment]
yeah. thanks. May be I just put this in my todo-list for a while to focus on other things first. I don't have any use now too.

**Comment by swails** [comment]
Closing this for now.  Seems to be on the back-burner (if it's going to happen at all).
