### ISSUE TITLE
unclear about `acceptors` attrs

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#189]
```python
In [41]: t
Out[41]: <Structure 1086 atoms; 34 residues; 0 bonds; PBC; NOT parametrized>

In [42]: t.acceptors
Out[42]: []

In [43]: t.acceptors?
Type:        TrackedList
String form: []
Length:      0

```

what does `acceptors` mean? (I thought about hbond). if this is about 'hbond', this seems not-right.
(`t = pmd.download_PDB("1o15"`)

**Comment by swails** [comment]
CHARMM PSF files define acceptors (and yes, it's for H-bonds).  No other topology class defines them, so usually it's just an empty list.  But for people that want to use ParmEd to interrogate CHARMM PSF topologies, the data is made available.

Same with donors.

**Comment by hainm** [comment]
clear to me now.

**Comment by hainm** [comment]
actually this is still confusing me (may be others too). For example

```python
In [28]: x = pmd.download_PDB('5cxt')

In [29]: x
Out[29]: <Structure 9071 atoms; 1616 residues; 0 bonds; PBC (triclinic); NOT parametrized>

In [30]: x.donors
Out[30]:
TrackedList([
])
```

At first, I think people always assume donor-acceptor in H-bond. The empty tracklist indicates there is None. Either you should make it an attribute of PSF only, or clearly indicate in its doc.

**Comment by swails** [comment]
You could say the same thing about bonds, which is simply an empty list when loading a PDB file (for now):

```Python
>>> import parmed as pmd
>>> x = pmd.download_PDB('5cxt')
>>> x
<Structure 9071 atoms; 1616 residues; 0 bonds; PBC (triclinic); NOT parametrized>
>>> x.bonds
TrackedList([
])
>>> 
```

But I hope that you're not suggesting we should delete all list attributes that don't get filled by the parser...  This would make interconverting an absolute nightmare and a jumbled mess of `if hasattr(struct, 'blah'):`.

And if someone wants to *define* acceptors in a Structure they instantiate from some source in order to have ParmEd write a PSF file that has defined acceptors, they just add `AcceptorDonor`s to the list.  Doing away with attributes gets in the way of duck typing, which reigns supreme in ParmEd.

The concept is this: parsers will populate the attributes that are defined in the files.  It won't populate others, and they will simply be empty lists.  Most structures will *also* have empty `torsion_torsions` or `stretch_bends` (which are only found in the AMOEBA force field), but again it would be a nightmare to only sometimes have these attributes compared to carrying around some empty lists.

So I think the confusion on this account is better than the huge jump in conversion complexity that's introduced by making some of these topological attributes only conditionally present.
