### ISSUE TITLE
parm.chamber--> parm.is_chamber()?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#199]
what do you think?

**Comment by swails** [comment]
Not a compelling enough reason to break the API *or* add a redundant synonym IMO.  The attribute is really not even necessary anymore since `ChamberParm` and `AmberParm` are separate classes (the former inherits from the latter) -- this didn't used to be the case.  `isinstance(thing, parmed.amber.ChamberParm)` does the same thing.

**Comment by hainm** [comment]
so this will be obsolete?

**Comment by swails** [comment]
It's still a convenience thing, and it's used in several places within ParmEd.  I don't expect it to go anywhere.
