### ISSUE TITLE
load from GRO file and don't have `coords`

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#202]
```python
In [15]: from mdtraj.testing import get_fn

In [16]: pt = pmd.load_file(get_fn("frame0.gro"))
```
```
In [13]: pt.coords
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-8396b94ba432> in <module>()
----> 1 pt.coords

AttributeError: 'Structure' object has no attribute 'coords'

In [14]: pt.positions
Out[14]: Quantity(value=[(4.29, 13.100000000000001, 8.59), (5.2, 13.600000000000001, 8.8), (4.89, 14.299999999999999, 9.6), (5.6000000000000005, 14.2, 7.890000000000001), (6.1, 12.5, 9.399999999999999), (6.4, 12.5, 10.600000000000001), (6.59, 11.6, 8.49), (6.5, 11.6, 7.5), (7.29, 10.4, 9.09), (7.890000000000001, 10.69, 10.0), (6.2, 9.5, 9.6), (5.699999999999999, 9.09, 8.8), (6.59, 8.7, 10.2), (5.390000000000001, 10.0, 10.2), (8.4, 9.79, 8.2), (8.4, 9.89, 7.0), (9.3, 9.0, 8.8), (9.09, 9.0, 9.79), (10.5, 8.4, 8.299999999999999), (10.69, 7.7, 9.09), (10.4, 7.99, 7.29), (11.299999999999999, 9.09, 8.299999999999999)], unit=angstrom)

```

**`pt` does not have load_coordinates**

**Comment by hainm** [comment]
AmberParm
```python
In [17]: traj = io.load_sample_data()

In [18]:

In [18]: pt2 = pmd.load_file(traj.top.filename)

In [19]: pt2.load_coordinates(traj[0].coords)

In [20]: pt2.positions
Out[20]: Quantity(value=[(3.32577, 1.547909, -1.6e-06), (4.046154, 0.839991, -2.9e-06), (2.823094, 1.499508, -0.874687), (2.823097, 1.499507, 0.874685), (3.970048, 2.845795, -1e-07), (3.671663, 3.400129, -0.88982), (3.576965, 3.653838, 1.232143), (3.877484, 3.115795, 2.131197), (4.075059, 4.623017, 1.205786), (2.496995, 3.801075, 1.241379), (5.485541, 2.705207, -4.4e-06), (6.008824, 1.593175, -8.4e-06), (6.1910071, 3.8385836, -5.1e-06), (5.7152868, 4.7295323, -2.8e-06), (7.6400076, 3.8385837, -7.4e-06), (8.0038585, 3.3248391, 0.8898118), (8.1890012, 3.1272109, -1.2321515), (7.8406911, 3.6356234, -2.1312048), (9.2785764, 3.1424273, -1.2057951), (7.8406894, 2.0944027, -1.2413883), (8.1879242, 5.2585384, -2e-06), (7.4245351, 6.2216985, 3.4e-06), (9.5167782, 5.3864922, -2e-06), (10.1032885, 4.5642362, -5.3e-06), (10.1610562, 6.6843782, 1.2e-06), (9.8626701, 7.2387139, -0.8898172), (9.7679746, 7.4924189, 1.2321464), (10.0684947, 6.9543742, 2.131199), (10.2660686, 8.4615979, 1.2057906), (8.6880046, 7.6396559, 1.2413839), (11.6765492, 6.5437902, -5.1e-06), (12.2461278, 6.4909563, -1.1226755), (12.2461365, 6.4909441, 1.1226605), (13.1938543, 6.4030293, 0.9973513)], unit=angstrom)

In [21]: pt2.co
pt2.coords  pt2.copy

In [21]: pt2.coords
Out[21]: array('d', [3.32577, 1.547909, -1.6e-06, 4.046154, 0.839991, -2.9e-06, 2.823094, 1.499508, -0.874687, 2.823097, 1.499507, 0.874685, 3.970048, 2.845795, -1e-07, 3.671663, 3.400129, -0.88982, 3.576965, 3.653838, 1.232143, 3.877484, 3.115795, 2.131197, 4.075059, 4.623017, 1.205786, 2.496995, 3.801075, 1.241379, 5.485541, 2.705207, -4.4e-06, 6.008824, 1.593175, -8.4e-06, 6.1910071, 3.8385836, -5.1e-06, 5.7152868, 4.7295323, -2.8e-06, 7.6400076, 3.8385837, -7.4e-06, 8.0038585, 3.3248391, 0.8898118, 8.1890012, 3.1272109, -1.2321515, 7.8406911, 3.6356234, -2.1312048, 9.2785764, 3.1424273, -1.2057951, 7.8406894, 2.0944027, -1.2413883, 8.1879242, 5.2585384, -2e-06, 7.4245351, 6.2216985, 3.4e-06, 9.5167782, 5.3864922, -2e-06, 10.1032885, 4.5642362, -5.3e-06, 10.1610562, 6.6843782, 1.2e-06, 9.8626701, 7.2387139, -0.8898172, 9.7679746, 7.4924189, 1.2321464, 10.0684947, 6.9543742, 2.131199, 10.2660686, 8.4615979, 1.2057906, 8.6880046, 7.6396559, 1.2413839, 11.6765492, 6.5437902, -5.1e-06, 12.2461278, 6.4909563, -1.1226755, 12.2461365, 6.4909441, 1.1226605, 13.1938543, 6.4030293, 0.9973513])
```

**Comment by hainm** [comment]
the API seems not to be consistent.

**Comment by swails** [comment]
For coordinate handling there is limited consistency.  F

**Comment by swails** [comment]
For coordinate handling there is limited consistency. For now, the only real coordinate attribute is "positions", which is a unit-bearing list of Vec3 instances. 

This is next on the agenda to fix, and the plan is to have "coordinates" be a 3-dimensional numpy array with shape (frame, natom, 3). So all coordinate-bearing classes will have the same API. 

My main hesitation is the hard numpy requirement since the Amber portion of ParmEd's user base doesn't necessarily care about Python. But there's a limit to how much flexibility I can support, so I think it's going to happen.

**Comment by leeping** [comment]
I imagine numpy is ubiquitous among users of Python for scientific computing, so I have no problem with introducing that dependency, but that could be my bias. :)

**Comment by davidlmobley** [comment]
Yeah. You might even be doing AMBER people a favor if you require some
Python stuff - i.e. what I tell my beginning undergrads is basically just:
- install anaconda python
- configure omnia conda channel
- conda install (whatever)

They don't even have to be aware of what they've installed - it just works.
And then I can do cool things like have them run ipython notebooks so I can
teach them python/plotting super easily with almost no configuration on
their part.

David

On Sat, Jun 13, 2015 at 10:13 AM, Lee-Ping <notifications@github.com> wrote:

> I imagine numpy is ubiquitous among users of Python for scientific
> computing, so I have no problem with introducing that dependency, but that
> could be my bias. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/202#issuecomment-111730928>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by hainm** [comment]
Installing Ambertools is complicated enough. So I support the idea that make `parmed` very light. Why `parmed` really need numpy?

**Comment by swails** [comment]
> Installing Ambertools is complicated enough. So I support the idea that make parmed very light. Why parmed really need numpy?

There are things ParmEd can do that require numpy (computing COMs of molecules, which is used for OFF file generation).  And NetCDF reading and writing also require numpy (and scipy).  There is a lot of functionality that is useful that doesn't require numpy, though.

The reasons to support numpy-free ParmEd:

- Several things in AmberTools rely on ParmEd that are used by people that may not have any interest in using Python: MMPBSA.py, ante-MMPBSA.py, and cpinutil.py to name a few.
- ParmEd has an interpreter (similar to cpptraj) that again, does not require users to incorporate Python into their workflows.  I'm not sure how much of the Amber user base doesn't have numpy installed, but I'd be willing to bet the percentage is non-negligible (unlike the OpenMM user base, by contrast).

The reasons to require numpy:

- If users *have* numpy, they will almost certainly want data exposed as numpy arrays (like coordinates) when available
- The Python `list` and `numpy.ndarray` have completely different APIs.  `some_array * 10` scales every element by 10 for a numpy array, but it makes a new array with 10 concatenated copies of `some_array` for list!
- It reduces maintenance burden

The last two are the most important.  I don't use Python without numpy installed, so I very rarely test the numpy-less code paths.  That's a real problem.  Sure, I have Travis set up to run a set of tests without numpy, but that's not the same as using it on a regular basis.  Also, supporting numpy being optional adds complexity and bloat to the code base, further reducing maintainability.

> if you just need C++ speed to transpose 1D to 3D array, you can use Cython to write a method to do so.

No way
- It's just as easy to install numpy as it is to install Cython requirements (even if you distribute cythonized files which I probably wouldn't, you'd still need the Python dev headers, which usually have to be installed separately through the package manager just like numpy)
- Numpy has the benefit of hundreds of man-years devoted to its development
- It adds considerable complexity to the code base, raising barriers to getting others involved.

> And pytraj does not need numpy at all.

How many people that you think would be interested in using pytraj (instead of just using cpptraj) would do so without numpy installed?  I suspect few, if any.  I see the power of pytraj (and related packages) as providing a seamless way to hook analysis of MD into the scipy stack (numpy, scipy, matplotlib, scikit-learn, statsmodels, pandas, ... etc).  Without numpy, there is no scipy stack, and the utility of packages like pytraj and mdtraj takes a serious hit (which is why mdtraj is built on top of numpy).

Every line of code that gets added to ParmEd whose purpose is simply to (try to) duplicate numpy, scipy, or pandas functionality without substantially improving upon it somehow is measurably worse IMO than not adding it at all.

**Comment by rmcgibbo** [comment]
It would be awesome if we had any kind of survey data from users about the platforms they're running on and the installation hurdles. In the last two years or so, most of the people I know have switched to anaconda, but I know that they're not a representative subset. I suspect for personal linux workstations, more people are using python through their system package manager.

On most of the CentOS-based Stanford clusters I use, the RHEL system python in `/usr/bin/` does not have numpy, but the sysadmins provide one or more pythons through `module`s that do have numpy installed. I recall BlueWaters and Titan being this way too.

**Comment by hainm** [comment]
@swails  I see what you mean. I was considering `parmed` as a package for editing/converting/exploring Topology for all popular packages. So that's my point for my comment  above. Of course, it's great to build on top of other popular and stable packages.

**Comment by rmcgibbo** [comment]
Anyways, IMO the extra maintenance burden of writing scientific/numerical code in python without numpy (and thus any access to the scipy stack) is so high as to be essentially not worth it. I would personally rather just write golang.

**Comment by hainm** [comment]
@rmcgibbo try julialang yet?

**Comment by rmcgibbo** [comment]
Yes. I don't think it solves the relevant issues for this conversation though.

**Comment by swails** [comment]
This is implemented in #211.

**Comment by hainm** [comment]
@swails are you going to add `load_coordinates` for `Structure` class too?

**Comment by hainm** [comment]
nevermind, I just saw 'DeprecationWarning: load_coordinates is deprecated'
