### ISSUE TITLE
Question about writing frcmod (without Structure)

### ISSUE THREAD

**Issue by leeping** [ParmEd/ParmEd#212]
Hi there,

I'm following up on using ParmEd to write out a new AMBER force field definition starting from an OpenMM force field XML file.  Here's what I've done so far:

1) I created a `ParameterSet` object with all of the parameters from reading the OpenMM XML.
2) I read in the `all_amino94.lib` and `ct, nt` versions from the AMBER folder.
3) I replaced the atom types in the `.lib` files with my new custom atom types, and wrote them back out.

I'm currently trying to figure out how to write the `.frcmod` file.  The source code has some `.frcmod`-writing functionality in the `actions` folder, but I don't know how to use the `Action` classes.  It also appears that I need to create an `AmberParm` object, but I don't have a `Structure` object from reading the force field XML file - just a `ParameterSet`.

If you have some tips I could follow, that would be great.

Thanks,

- Lee-Ping

**Comment by swails** [comment]
I've been meaning to get to this.  See `parmed/amber/parameters.py`.  The `ParameterSet` object there (which predates *every* class in the `Structure` hierarchy) is responsible for the frcmod writing.

I need to replace the crap in there with stuff that properly uses the object layout in `parmed.parameters` and `parmed.topologyobjects`.

**Comment by hainm** [comment]
@swails is `topologyobjects` internal module? any intention to change its name? hard to read for me.

**Comment by swails** [comment]
Yea, it's largely internal.  All of the stuff there is imported into the `parmed` namespace.  No plans to change its name.

**Comment by leeping** [comment]
Thanks, Jason - that worked!  Now it's a matter of testing the agreement between Amber and Gromacs, which I will try to do as soon as possible.

**Comment by swails** [comment]
Let me know how it goes, and if you have any questions along the way!

**Comment by swails** [comment]
@leeping -- I'm sure you're settling into your new position and everything, but I've *finally* gotten around to migrating `parmed/amber/parameters.py` over to the main object model (so it subclasses from `parmed.parameters.ParameterSet` and uses the same data structures).

I apologize in advance if this broke any of your scripts -- I'd be happy to help fix them up a bit.  But this should make things a bit easier in the long run.

But since the fb15 force field is already deposited in the Amber repository, I'm going to go ahead and say this was at least partially a success, and close it.  :) Feel free to reopen if necessary.
