### ISSUE TITLE
better __str__ and __repr__ for pdb.bonds

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#215]
```python
In [25]: pdb = pmd.download_PDB("5AUN")

In [26]: pdb
Out[26]: <Structure 3323 atoms; 736 residues; 0 bonds; PBC; NOT parametrized>

In [27]: pdb.bonds
Out[27]: []
```

--> I though this is a python list.
so I assigned this

```python
In [33]: pdb.bonds = list(traj.top.bond_indices)
In [33]: pdb.bonds[:3]
Out[33]: [array('i', [0, 1]), array('i', [0, 2]), array('i', [0, 3])]
In [34]: pdb
Out[34]: ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
```

so I guess I need to convert anything to a python `list`. --> I did and still got error. --> so `pdb.bonds` is an object of `TrackedList`.

Can you:
* add `__str__` and `__repr__` for `pdb.bonds`
* protect assignment for `bonds`
```python
In [38]: pdb = pmd.download_PDB("5AUN")

In [39]: type(pdb.bonds)
Out[39]: parmed.topologyobjects.TrackedList

In [40]: pdb.bonds = []

In [41]: type(pdb.bonds)
Out[41]: list
```

**Comment by swails** [comment]
> --> I though this is a python list.

It derives from `list`, and as a result inherits its `__repr__`.  I actually like this `__repr__`, personally, since it gives nice representations when it's actually *filled* with stuff.

>
```
> In [33]: pdb.bonds = list(traj.top.bond_indices)
> In [33]: pdb.bonds[:3]
> Out[33]: [array('i', [0, 1]), array('i', [0, 2]), array('i', [0, 3])]
> In [34]: pdb
> Out[34]: ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
```
>

Yea, this won't work.  `Structure` assumes everything is a `TrackedList` (so it looks for a `changed` attribute that gets toggled whenever you try and modify the list in any way).  It's pretty straightforward once you're familiar with the design: `Structure.bonds` is full of `Bond` instances, `.angles` is full of `Angle`, ... etc.

> Can you:
> 
> add `__str__` and `__repr__` for pdb.bonds

IMO, `__str__` and `__repr__` should never be the same.  If you don't implement `__str__`, it defaults to `__repr__` (and vice-versa, I think).  If you want to improve the representation you see at the interactive interpreter, `__repr__` is all you want to change.

That said, I like the standard `list.__repr__` for `TrackedList`, personally.  If enough other people would rather see something different, I'll reconsider.

> protect assignment for bonds

I'm going to wait on this to see if it becomes more important.  I would have to do the same thing for every other attribute on `Structure`, and that just becomes a mess.  Keeping everything as a plain attribute keeps the object layout simple, at the cost of perhaps some growing pains when people that want to start *building* `Structure` instances get into it.

It's tempting to fall into the practice of doing something "wrong" (without knowing it) and getting what seems to be very strange and unexpected behavior and jumping to the conclusion that safeguards must be put in place to prevent that from ever happening again (I do it myself very often).  But for now I want to resist that temptation.

For now, I'm addressing it in documentation (#216)

**Comment by hainm** [comment]
yea, feel free to close this topic.

**Comment by hainm** [comment]
ah, so why not something like

```python
In [18]: p.bonds
Out[18]:
<TrackedList
[<Bond <Atom C [10]; In ALA 0>--<Atom O [11]; In ALA 0>; type=<BondType; k=570.000, req=1.229>>,
 <Bond <Atom C [10]; In ALA 0>--<Atom N [12]; In ALA 1>; type=<BondType; k=490.000, req=1.335>>]
>
```

**Comment by swails** [comment]
That's a good point.  I can do that.

**Comment by swails** [comment]
Done in #237
