### ISSUE TITLE
~18-30 s to load 46176 atoms

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#219]
I just want to post the timing here in case you're interested in speeding up the parsing in the future.

```python
pmd.load_file('supercell.parm7")
```

**Comment by swails** [comment]
This seems a bit slower than I'd expect. Are you sure you're using the accelerated parser?

**Comment by hainm** [comment]
@swails 

what do you mean about 'accelerated' one? I just pulled master and compiler it. I've tried in `casegroup`.

If you meant using `src/_rdparm.cpp`: Yes, I did see it compiled.

I got `30 s` for the first time I ran my script, but later always got `18-19 s`.

**Comment by hainm** [comment]
for cpptra/pytraj: < 1 s. 

(I know Topology in pytraj/cpptraj and parmed have different types of info)

**Comment by hainm** [comment]
if using `timeit`

```python
In [2]: %timeit parm = pmd.load_file("supercell.parm7")
1 loops, best of 3: 12.5 s per loop
```

if using `time`
```python
In [3]: %time pmd.load_file("supercell.parm7")
CPU times: user 20.7 s, sys: 205 ms, total: 20.9 s
Wall time: 20.9 s
Out[3]: <AmberParm 46176 atoms; 3072 residues; 47040 bonds; PBC; parametrized>
```

**Comment by swails** [comment]
On my Mac laptop (with an 2.6 GHz Intel Core i5), here are the timings I'm getting when I load `dhfr_cmap_pbc.parm7` from the test directory:

```Python
In [2]: %time pmd.load_file('dhfr_cmap_pbc.parm7')
CPU times: user 4.21 s, sys: 182 ms, total: 4.39 s
Wall time: 4.39 s
Out[2]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC (orthogonal); parametrized>

In [3]: %timeit pmd.load_file('dhfr_cmap_pbc.parm7')
1 loops, best of 3: 3.3 s per loop
```

On my desktop, which has an AMD FX-6100 3.3 GHz CPU, I'm getting

```Python
In [1]: import parmed as pmd

In [2]: %time pmd.load_file('dhfr_cmap_pbc.parm7')
CPU times: user 6.95 s, sys: 160 ms, total: 7.11 s
Wall time: 7.16 s
Out[2]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC (orthogonal); parametrized>

In [3]: %timeit pmd.load_file('dhfr_cmap_pbc.parm7')
1 loops, best of 3: 4.81 s per loop
```

On my desktop when I *don't* use the accelerated parser, I'm getting

```Python
In [2]: %time pmd.load_file('test/files/dhfr_cmap_pbc.parm7')
CPU times: user 8.46 s, sys: 180 ms, total: 8.64 s
Wall time: 8.65 s
Out[2]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC (orthogonal); parametrized>

In [3]: %timeit pmd.load_file('test/files/dhfr_cmap_pbc.parm7')
1 loops, best of 3: 6.37 s per loop
```

So it seems that the time taken in tasks *besides* raw parsing has increased.  But I'm still seeing parsing and processing times less than half of what you are...

> for cpptra/pytraj: < 1 s.
> 
> (I know Topology in pytraj/cpptraj and parmed have different types of info)

The parsers also have very different philosophies.  First of all, cpptraj and pytraj *only* parse the information that it deems important, and it will fail if all of the data in the topology file is not correct (e.g., if there is anything besides the expected number of values in a given section).  ParmEd, by contrast, reads all of the raw data and processes it without making any pre-assumptions about what data is *supposed* to be there (which means it can parse stuff like Amber MDL files from RISM whereas cpptraj/pytraj cannot).  This makes it necessarily slower.  And the Atom/Bond/Angle/... creation is done at the Python level in ParmEd, rather than the C/C++ level in pytraj, which accounts for another order of magnitude difference there.

I'll certainly profile this and see where the bottlenecks are, but last time I checked the cost was fairly evenly distributed, and I'm still getting times 2-5x faster than you are...

**Comment by hainm** [comment]
@swails 
can you try timing this in `casegroup`?

```python
In [2]: %timeit pmd.load_file("supercell.parm7")
1 loops, best of 3: 12.6 s per loop

In [3]: pwd
Out[3]: '/u1/haichit/test'
```

```python
In [17]: %time pmd.load_file('dhfr_cmap_pbc.parm7')
CPU times: user 13.3 s, sys: 114 ms, total: 13.4 s
Wall time: 13.4 s
Out[17]: <ChamberParm 56057 atoms; 18015 residues; 56091 bonds; PBC; parametrized>
```

**Comment by hainm** [comment]
oops, forgot to `timeit`

```python
In [2]: %timeit pmd.load_file('dhfr_cmap_pbc.parm7')
1 loops, best of 3: 7.23 s per loop
```

**Comment by swails** [comment]
Does `supercell.parm7` have an `ATOMIC_NUMBER` section?

**Comment by hainm** [comment]
Yes It does. You can check that file in the folder. i am using py3. I just reran the speed test while there is no other programs running, there is still 18s to load.

Hai

**Comment by swails** [comment]
I finally got my hands on supercell.parm7 and I see similar behavior.  On my i5 MacBook Pro:

```
%timeit pmd.load_file('supercell.parm7')
1 loops, best of 3: 5.58 s per loop
```

Compare that to the 2.36 seconds that `dhfr_cmap_pbc.parm7` took, and this file takes ~2x longer.  Your profiler points to the dihedral loading as the biggest cost.  This file is atypical because the solute/solvent ratio is so large.  So there are more dihedrals than in most other systems.

Hopefully there is something obviously slow that I'm doing that I can fix.

**Comment by swails** [comment]
OK, it's not entirely clear to me how to improve this in Python.  The dihedral and atom loading are both about the same cost.  The biggest hit in the dihedral loading is that it accesses `TrackedList.__getitem__` which has some logic to handle slicing (basically making sure that a slice of `TrackedList` returns another `TrackedList` instead of a `list`).  This is slowing things down (indeed, using `isinstance` instead of `hasattr` in that function gave a very measurable speedup).

I think it's time to revisit whether or not it's important for a `TrackedList` slice to return a `TrackedList` or if a simple `list` suffices.  I can't think of any instance where a `TrackedList` is needed, so getting rid of this feature will push one of the most heavily used functions from pure Python into the C code for `list`.

Other than this, there is nothing more I can do to make pure Python much faster (without going to pypy).  And shaving off several seconds per read isn't worth going all Cython on my code :).

**Comment by swails** [comment]
The combination of #225, #226 and #237 give, overall, a ~30-40% performance boost for `supercell.py`.  And there's not much more I can do.

I'm going to go ahead and close this.
