### ISSUE TITLE
consistent syntax: write_PDB vs write_pdb, write_CIF vs write_cif?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#222]
Jason,

is there any different between them? `write_cif` and `write_CIF`?

```python
In [10]: pdb.write_cif
Out[10]: <bound method Structure.write of <Structure 1164 atoms; 274 residues; 0 bonds; PBC; NOT parametrized>>

In [11]: pmd.write_CIF
Out[11]: <function parmed.formats.pdb.CIFFile.write>
```

**Comment by swails** [comment]
No.  See [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/__init__.py#L22) and [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L1380).

This will all be cleaned up a bit when #106 gets implemented.

**Comment by hainm** [comment]
thx. Yes, should be cleaned. Kind of confused.

**Comment by hainm** [comment]
reopen this

```python

In [4]: pmd.write
pmd.write_CIF  pmd.write_PDB  

vs 

In [4]: pmd.Structure.write_p
pmd.Structure.write_pdb  pmd.Structure.write_psf 
```

should change to `write_pdb` and `write_cif`?

**Comment by swails** [comment]
`write_PDB` and `write_CIF` are really historical functions that have lost their utility since the `Structure.save` addition.  I picked the names `write_PDB` and `write_CIF` as analogies to `read_PDB` and `read_CIF` (which themselves are mostly replaced by `load_file`).

I don't want to change the name, but they are probably good candidates for deprecation and eventual removal. Same with `write_pdb` and `write_cif` and `write_psf`.
