### ISSUE TITLE
import `tools` to `parmed` namespace?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#238]
hey man,

I saw in the amer topic "[AMBER] another leap inconsistency", you posted an example here.

```python
pmd.tools.energy(y, 'omm', 'decompose').execute()
```
but `tools` is not available when `import parmed as pmd`.
(I need to do `from parmed import tools`). If this is what you intend to import to main namespace, we can add to `__init__` file: `from parmed import tools`, right? :p 

I did this and try to PR but got error

```python
Traceback (most recent call last):
  File "./setup.py", line 41, in <module>
    import parmed
  File "/u1/haichit/programs/parmed/parmed/__init__.py", line 17, in <module>
    from parmed import tools
  File "/u1/haichit/programs/parmed/parmed/tools/__init__.py", line 7, in <module>
    from .actions import *
  File "/u1/haichit/programs/parmed/parmed/tools/actions.py", line 6, in <module>
    from parmed import (Bond, BondType, Angle, AngleType, Dihedral, DihedralType,
ImportError: cannot import name 'load_file'
```

the cause of error is you import `parmed` in `setup.py` to get `__version__`. Is this a good idea to import here? (like get version from string parsing).

Hai

**Comment by hainm** [comment]
One more question (:D), do you have a reason to prefer absolute import vs relative import? just curious about your rationale.

In `pytraj` I mostly use relative import but for some cases, need to use absolute one to avoid circular importing. 

PS: I know that `pandas` use absolute import while sklearn mostly use relative import.

Hai

**Comment by hainm** [comment]
Should we avoid `import *` too? I saw few lines in `parmed`.

**Comment by swails** [comment]
> the cause of error is you import parmed in setup.py to get __version__. Is this a good idea to import here? (like get version from string parsing).

This isn't actually the cause.  The problem is that `parmed.tools` was originally a separate `ParmedTools` package, and so it treated the `parmed` (old `chemistry`) as a separate package.  In particular, it would import things from `parmed.topologyobjects` straight from the `parmed` namespace rather than from the `parmed.topologyobjects` module where they were defined (or `parmed.load_file` instead of `parmed.formats.registry.load_file`.  *This* is what introduced order in the imports in `parmed/__init__.py`.  I want to get this fixed at some point, but that's a problem for Tomorrow Jason.

Until I use something like versioneer or a tool to automate this, I only want to keep 1 copy of the version if at all possible.

> One more question (:D), do you have a reason to prefer absolute import vs relative import? just curious about your rationale.

It wasn't long ago that ParmEd supported Python 2.4 through Python 3.4.  So absolute imports were the only choice.  I don't prefer one over the other, personally.  Relative imports have some advantages -- consider pysander, where I can have a single code base for both `sander` and `sanderles` (you can see in the Amber git repo how I use relative importing to keep it so I only need one copy of the code base).

> Should we avoid `import *` too? I saw few lines in `parmed`.

I use this in very specific circumstances, and I never import * from a module that doesn't define an `__all__`.  I actually only do this in 3 places in `parmed`:

```
parmed/__init__.py:11: 'from parmed.topologyobjects import *' used; unable to detect undefined names
parmed/modeller/__init__.py:10: 'from parmed.modeller.residue import *' used; unable to detect undefined names
parmed/tools/__init__.py:6: 'from parmed.tools.actions import *' used; unable to detect undefined names
```

All other instances are in packages that I use/distribute, but didn't write (`unit` and `fortranformat`).  And I use it in `xparmed` widgets, but that's how Tkinter was designed to be used.  So I do it rarely, but it has its uses.

**Comment by hainm** [comment]
thanks.

**Comment by swails** [comment]
And thank *you* for the continued interest and questions about even the little things in ParmEd.

**Comment by hainm** [comment]
yeah. like you said, it was quick to create and close an issue.
