### ISSUE TITLE
help(summary) vs "summary?"

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#246]
is that possible (and do-able) to add "?" ipython-like for getting parmed's doc in interactive mode? I find this `sum<Tab>?` save lots of times.

may be it will be really cool if `parmed` can integrate with ipython. Something like
```python
%%parmed
```

**Comment by swails** [comment]
> is that possible (and do-able) to add "?" ipython-like for getting parmed's doc in interactive mode? I find this sum<Tab>? save lots of times.

The command interpreter inherits from `cmd.Cmd` (which is part of the Python standard library).  So the syntax is dictated by that class.  The help syntax is either:

```
> help <command>
> ?<command>
```

`cmd.Cmd` does a lot of work for me -- readline support, command processing, help syntax generation, etc.  This also implements a rather "standard" command-line API.  It's also stdlib, so it doesn't introduce any additional dependencies.  So I'm definitely not abandoning this class for something else.  The IPython-like syntax (`?` at the end, rather than the beginning) was easy to implement, so I added it in #247.

> may be it will be really cool if parmed can integrate with ipython. Something like
> 
```
> %%parmed
```

If you want to add that I'd be happy to accept the PR, but I don't know IPython *nearly* well enough to even put this on my priority list.

**Comment by hainm** [comment]
On Mon, Jul 6, 2015 at 12:59 PM, Jason Swails <notifications@github.com>
wrote:

> is that possible (and do-able) to add "?" ipython-like for getting
> parmed's doc in interactive mode? I find this sum? save lots of times.
>
> The command interpreter inherits from cmd.Cmd (which is part of the
> Python standard library). So the syntax is dictated by that class. The help
> syntax is either:
>
> > help <command>
> > ?<command>
>
> cmd.Cmd does a lot of work for me -- readline support, command
> processing, help syntax generation, etc. This also implements a rather
> "standard" command-line API. It's also stdlib, so it doesn't introduce any
> additional dependencies. So I'm definitely not abandoning this class for
> something else.
>
Sure. I myself prefer stdlib too.


> The IPython-like syntax (? at the end, rather than the beginning) was
> easy to implement, so I added it in #247
> <https://github.com/ParmEd/ParmEd/pull/247>.
>

cool. thanks.


>  may be it will be really cool if parmed can integrate with ipython.
> Something like
>
> %%parmed
>
>  If you want to add that I'd be happy to accept the PR, but I don't know
> IPython *nearly* well enough to even put this on my priority list.
>

ok. I might PR (but I don't promise :D) since I am curious about writing
ipython extension.

Hai


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/246#issuecomment-118924669>.
>



-- 
Hai Nguyen

**Comment by swails** [comment]
> ok. I might PR (but I don't promise :D) since I am curious about writing
> ipython extension.

Have at it :).

Closing this, since the main request is implemented.
