### ISSUE TITLE
better way to change bond, dihedral, ... parameters with parm and pysander?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#261]
It's clear that this code does not work since `parmed` will load the same Topology file.

```python
        import parmed as pmd
        import sander

        traj = pt.iterload("./data/Tc5b.crd", "./data/Tc5b.top")
        p = pmd.load_file(traj.top.filename)
        inp = sander.gas_input(8)
        coords = traj[0].coords

        for k in range(20, 100):
            p.bonds[3].type.k = k
            print(p.bonds[3].type.k)
            with sander.setup(p, coords, None, inp):
                ene, frc = sander.energy_forces()
                print (ene.bond)
```

So I need to 
```
p.save("newparm.parm7")
p = pmd.load_file("newparm.parm7")
```
to reload the new parameters.

Do you have intend to make pysander able to read internal parameter changes?

thanks.

Hai

**Comment by hainm** [comment]
by the way, it's still fine (and fast) if people want to change parameters for bond, angle or dih for small fragment.

**Comment by hainm** [comment]
ah, you really need to update pysander code to warn users. The updated new pars but `pysander` just load the original filename.

**Comment by hainm** [comment]
it took few hours to figure out why changing bond parameters for `parm` did not change the bond energy.

**Comment by swails** [comment]
So this is actually a limitation in how ParmEd detects changes to the parameter arrays.  For historical reasons, ParmEd carries around a dict of the raw data as well as the topological objects for the atoms, bonds, angles, etc.  You changed the topological feature (`bond.type.k`), but not the raw data.  So when `pysander` internally wrote a new topology file, it didn't write the updated parameter you just changed.

To address this, I added the `TrackedList` class to detect when changes were made to the topological objects so that `write_parm` would know when to flush that data to the `parm_data` dict that it ultimately wrote to the prmtop file.  But this only detects changes to the list itself -- like when you append, set an item, delete an item, extend, insert, remove, pop, etc.  There's no way for `TrackedList` to recognize when you change an attribute of a particular item in the list.

There were reasons in the past to avoid always calling `remake_parm` when writing (since that call used to reorder all of the topology pointers), but those reasons really don't apply anymore.  #262 makes the change that `write_parm` *always* updates the raw data from the topology arrays.  Hopefully that doesn't break anything and I can just merge it.  It may introduce a significant slowdown in cases where you plan on writing out a *lot* of topology files (since it has to regenerate a lot of information all the time).

So until #262 gets merged, the solution is to add the line `parm.remake_parm()` as shown below:

```Python
        import parmed as pmd
        import sander

        traj = pt.iterload("./data/Tc5b.crd", "./data/Tc5b.top")
        p = pmd.load_file(traj.top.filename)
        inp = sander.gas_input(8)
        coords = traj[0].coords

        for k in range(20, 100):
            p.bonds[3].type.k = k
            p.remake_parm() # ADDED LINE
            print(p.bonds[3].type.k)
            with sander.setup(p, coords, None, inp):
                ene, frc = sander.energy_forces()
                print (ene.bond)
```

If you have better ideas for how to handle this, I'm all ears...

**Comment by swails** [comment]
Also, keep in mind that, like with the Amber topology file, many bonds can share the same type.  So `p.bonds[3].type.k = k` will probably change the force constant on multiple bonds.  You can use the `is` operator to determine if two bonds share the same type:

```Python
In [1]: import parmed as pmd

In [2]: l = pmd.load_file('test/files/trx.prmtop', 'test/files/trx.inpcrd')

In [3]: bt = l.bonds[0].type

In [4]: sum(b.type is bt for b in l.bonds)
Out[4]: 115
```

So in this case, changing the force constant of the first bond *also* changes the force constant of 114 other bonds (since they all share that common type).  If you want to change only one parameter type, you can create a new type (which is a little bit complex):

```Python 
In [6]: from copy import copy

In [7]: l.bond_types.append(copy(l.bonds[0].type))

In [8]: l.bond_types.claim() # Claim ownership of all atoms

In [10]: l.bonds[0].type = l.bond_types[-1]

In [11]: bt = l.bonds[0].type

In [12]: sum(b.type is bt for b in l.bonds)
Out[12]: 1

In [13]: sum(b.type == bt for b in l.bonds)
Out[13]: 115
```

In this last case, you can see how the bond type was copied so changing it will no longer change any other bonds' parameters.

**Comment by hainm** [comment]
thanks.

**Comment by hainm** [comment]
can you push to amber git too?

**Comment by swails** [comment]
So #262 errored.  I have to figure out why and whether it is an acceptable change or not.

**Comment by hainm** [comment]
:D. 

By the way, with pysander + pytraj/cpptraj, doing dihedral scan, plotting ... for MM is so easy now.

**Comment by swails** [comment]
This is fixed now.
