### ISSUE TITLE
slicing to get a Structure

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#267]
this is my situation

```python
In [54]: p['@P*']
Out[54]: <Atom P [0]; In AF2 0>

In [55]: p['@C*']
Out[55]: <AmberParm 10 atoms; 1 residues; 6 bonds; parametrized>
```

I am wondering if just dump data to a Structure rather return either an Atom or and a Structure?

**Comment by hainm** [comment]
in `pytraj`, slicing a Trajectory can return a Frame or a new Trajectory, but there is still option to return a Trajectory with a single Frame.

```python
In [61]: traj[1]
Out[61]: <Frame with 5293 atoms>

In [62]: traj[1:3]
Out[62]: 
<pytraj.Trajectory with 2 frames: <Topology with 5293 atoms, 1704 residues, 1692 mols, 5300 bonds, PBC with box type = ortho>>
           

In [63]: traj[1:2]
Out[63]: 
<pytraj.Trajectory with 1 frames: <Topology with 5293 atoms, 1704 residues, 1692 mols, 5300 bonds, PBC with box type = ortho>>
```

**Comment by hainm** [comment]
or single atom

```python
In [64]: traj['@1']
Out[64]: 
<pytraj.Trajectory with 10 frames: <Topology with 1 atoms, 1 residues, 1 mols, 0 bonds, PBC with box type = ortho>>
```

**Comment by swails** [comment]
Originally I had it so that the only thing that returned a `Atom` was a single integer index.  Everything else returned a `Structure`, even if it was only a single atom.  Making it so any single-atom selection returned an `Atom` let me simplify the code a bit.

What behavior do you need here?  `struct[10]` I always want to return an `Atom`.  What would be best for something like: `x = struct['@P=']` where there is only one phosphorus?  An `Atom` or a `Structure`?

What about something like

```Python
x = struct[10000:]
```

where there are fewer than 10000 atoms in the structure?  Currently, this returns `None`.  Would a `Structure` with no atoms, residues, or any terms at all be preferable?  And perhaps this should evaluate to boolean `False`?  My main motivation for returning `None` is so I can use it in something like:

```
if struct[10000:]:
    # Do something...
```

But that can be accomplished with returning an empty `Structure` and having that evaluate to `False`, too.

**Comment by swails** [comment]
Actually, I remember why I changed it now so that any single-atom selections only return an `Atom`.  At first, only a single integer selection would return an `Atom`.  But there are other circumstances where an `Atom` is what you want returned.  For instance:

```Python
struct[10,2]    # The third atom of the 11th residue
struct['B',0,0] # The first atom of the 'B' chain
struct['@100']  # The 100th atom.
```

For my uses, an `Atom` is what I'd want from all of those selections.  What behavior would fill your needs?

**Comment by hainm** [comment]
@swails 

for my use
```python
p['@P*'].save("test.pdb")
```

**Comment by hainm** [comment]
there is no confusing to me if `struct[10]` return an Atom.
but `struct['@P=']` should return a new `Structure`, even with 1 atom.

`struct[10000:]` could return an empty `Structure`. I don't think it's good idea to return None.

**Comment by swails** [comment]
So `struct[10000]` would raise an `IndexError` if there weren't that many atoms.  But like standard containers in Python, making that a slice will return a boolean-False empty container.

Since an empty structure is not boolean False, I chose `None` as the return value.  But it would probably be best to return an empty `Structure` and implement `__bool__` (or `__nonzero__` for Py2).

**Comment by hainm** [comment]
what's about adding 'is_empty()' method? I myself prefer to use this (more explicit) rather using `if struct`

**Comment by swails** [comment]
You can get the same thing from `len(struct.atoms) == 0` or `len(struct.residues) == 0`.  What qualifies as "empty"?  For example:

```Python
>>> len(struct)
0
>>> len(struct.atoms)
0
>>> len(struct.residues)
1
```

Is that empty?  Testing lengths of atoms/residues is more explicit IMO.  The only reason I would give a `Structure` truthiness is so that a slice selecting nothing returns false-y (just like a slice of any other collection in Python).

**Comment by hainm** [comment]
> The only reason I would give a Structure truthiness is so that a slice selecting nothing returns false-y (just like a slice of any other collection in Python).

agree

**Comment by hainm** [comment]
this is another reason to get a `Structure`

```python
In [35]: pmd.tools.printDihedrals(p['@F*'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-bcc46a1ab95c> in <module>()
----> 1 pmd.tools.printDihedrals(p['@F*'])

/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/actions.py 
in  __init__(self, input_parm, arg_list, *args, **kwargs)
    131             self.parm_list = ParmList()
    132         else:
--> 133            raise TypeError('input_parm expected to be a ParmList or Structure '
    134                             'instance')
    135         # Set active parm

TypeError: input_parm expected to be a ParmList or Structure instance
```

```python
In [34]: type(p['@F*'])
Out[34]: parmed.topologyobjects.Atom
```

**Comment by hainm** [comment]
just want to add one more example that should return a new Structure (from my closed issue).

currently

```python
In [40]: p
Out[40]: <AmberParm 33 atoms; 1 residues; 35 bonds; parametrized>

In [41]: p[:1]
Out[41]: <Atom P1 [0]; In MOL 0>
```

vs.

```python
In [42]: a = [1, 3]

In [43]: a[:1]
Out[43]: [1]

In [44]: type(a[:1])
Out[44]: list
```

same motivation as above

```python
pmd.tools.printDihedrals(p[:1])
```

**Comment by swails** [comment]
> same motivation as above
> 
```
> pmd.tools.printDihedrals(p[:1])
```

Note, this will never print anything.  A single atom can never form any bonds (or multiple-bond connections), since, by definition, there are no other atoms to bond to :).  So `pmd.tools.printDihedrals(p[:1])` will always print a blank list...

In general,

```Python
pmd.tools.printDihedrals(p[<selection>])
```
will return different results than

```Python
pmd.tools.printDihedrals(p, '<selection>')
```

where `<selection>` is either a selector or the equivalent Amber mask.

That said, #275 implements the ideas sketched out in this issue and should give the behavior you want (that is admittedly much more consistent with the rest of the API and that I like better as well).

**Comment by hainm** [comment]
I am ok with `pmd.tools.printDihedrals(p, '<selection>')` (it actually save me time to type `[]`)
