### ISSUE TITLE
.mol2 file charge precision

### ISSUE THREAD

**Issue by nividic** [ParmEd/ParmEd#268]
Hi There,

Would be possible to change the .mol2 format writer and add a parameter that specifies the precision of the written charges? Sometimes the AM1BCC charge calculation does not give exact integer total charge and this could cause problem to tleap. 

Cheers,

Gaetano

**Comment by swails** [comment]
Are you sure this doesn't just add unnecessary complexity to the Mol2 writer API?  What about just increasing the precision to whatever you need rather than making it an option?

**Comment by swails** [comment]
Or did you want to *decrease* the precision?  If it's the latter, you could always force neutralization or truncate to the desired charge precision by hand:

```Python
import parmed as pmd
res = pmd.load_file('something.mol2')

# Explicit neutralization
net_chg = sum(a.charge for a in res)
net_chg /= len(res)
for a in res:
    a.charge -= net_chg

# Manual precision truncation
for atom in res:
    atom.charge = round(atom.charge, 3)
```

Another thing we could do is add a `neutralize()` method on `ResidueTemplate` (or `Structure`, really) that does this charge neutralization for you (which sounds like a potentially useful feature).  Unless I'm mistaken, what you really want is a way to get a mol2 file with an integer charge before feeding it into tleap*.  Adding flexibility to the precision of the mol2 file writer is not the best way to achieve that, IMO (for instance, you will still have that problem if you decided to save the file as an Amber library/OFF file instead of a mol2).

\*non-integer charges really *shouldn't* confuse tleap at all.  It will print a warning so that you know about it, but the `addIons` commands will treat any charge as the integer that it is closest to when neutralizing.  This wasn't true in AmberTools 14 or earlier, where negative charges were truncated rather than rounded (e.g., a charge of -1.9998 would result in 1 Na+ being added rather than 2), but this was fixed in AmberTools 15.

**Comment by nividic** [comment]
Hi Jason,
Thanks a lot for your prompt reply. Yes, we exactly want to have an integer charge before feed tleap. Therefore would it be very useful if you could add the neutrilize() function to the Parmed APIs.

Thanks a lot,

Gaetano

**Comment by davidlmobley** [comment]
@swails - just to agree with Gaetano here, this has been an issue for us a number of times. Partly it causes problems for us not so much because `tleap` chokes, but rather because the charge may get quite far from integer (i.e. if we have 500 molecules each with a net charge of 0.001). This is problematic for at least a couple of reasons:
* While the net charge of the system is not important for dynamics, it IS important for free energy calculations
*  IIRC, if the net charge is sufficiently far from zero, `tleap` prints a message containing the text "ERROR" (though it proceeds anyway). Currently we parse `tleap` output looking for errors (to avoid silent failures) so our tools will halt when this happens

**Comment by swails** [comment]
Fair point.  Just to be clear on the proposed API addition here: I'm going to add a `fix_charges` method to `ResidueTemplate` that will round the charge to the nearest integer and smear the difference over every atom in the residue template, which will ensure that the net charge is an integer.

The mol2 parser by default parses to a `ResidueTemplate` object (as does parsing an Amber OFF library, which actually parses to a `ResidueTemplateContainer` that is a list of `ResidueTemplate` objects).  Unless there's a real use-case, I don't want to add `fix_charges` to `Structure`.  My plan is for this to be an in-place modifier that returns `self`.  So the API would look something like this:

```Python
# Utility function
def check_net_charge(res):
    """ Returns True if the charge is an integer, False otherwise """
    net_chg = sum(a.charge for a in res)
    return round(net_chg) == net_chg

import parmed as pmd
res = pmd.load_file('molecule.mol2')
assert not check_net_charge(res) # Assume the net charge is not an integer
# Fix charges and write mol2 file
res.fix_charges()
res.save('integer_charges.mol2')
# OR do it in one line
# res.fix_charges().save('integer_charges.mol2')
assert check_net_charge(res) # will be True now
```

Does this work for your use cases, @nividic and @davidlmobley?

**Comment by hainm** [comment]
yeah, in case we load a fragment.

**Comment by davidlmobley** [comment]
That looks great to me. Thanks!

On Mon, Jul 13, 2015 at 7:23 PM, Jason Swails <notifications@github.com>
wrote:

> Fair point. Just to be clear on the proposed API addition here: I'm going
> to add a fix_charges method to ResidueTemplate that will round the charge
> to the nearest integer and smear the difference over every atom in the
> residue template, which will ensure that the net charge is an integer.
>
> The mol2 parser by default parses to a ResidueTemplate object (as does
> parsing an Amber OFF library, which actually parses to a
> ResidueTemplateContainer that is a list of ResidueTemplate objects).
> Unless there's a real use-case, I don't want to add fix_charges to
> Structure. My plan is for this to be an in-place modifier that returns
> self. So the API would look something like this:
>
> # Utility functiondef check_net_charge(res):
>     """ Returns True if the charge is an integer, False otherwise """
>     net_chg = sum(a.charge for a in res)
>     return round(net_chg) == net_chg
> import parmed as pmd
> res = pmd.load_file('molecule.mol2')assert not check_net_charge(res) # Assume the net charge is not an integer# Fix charges and write mol2 file
> res.fix_charges()
> res.save('integer_charges.mol2')# OR do it in one line# res.fix_charges().save('integer_charges.mol2')assert check_net_charge(res) # will be True now
>
> Does this work for your use cases, @nividic <https://github.com/nividic>
> and @davidlmobley <https://github.com/davidlmobley>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/268#issuecomment-121114138>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by nividic** [comment]
YES, it is ok for me as well. Thanks  a lot.

Gaetano
