### ISSUE TITLE
Renaming residues?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#272]
Is there an idiom that will allow me to rename residues?

The obvious idiom
```
# Rename CYS to CYX                                                                                                                                                                            
for atom in receptor[':CYS']:
    atom.residue.name = 'CYX'
```
doesn't seem to cause any permanent changes.

**Comment by hainm** [comment]
@jchodera: 

you can try
```python
for res in receptor.residues:
    if res.name == 'CYS':
        res.name = 'CYX'
```

**Comment by jchodera** [comment]
That did the trick---thanks!

**Comment by hainm** [comment]
I think `receptor[':CYS']` returns a copy, not a view of original `receptor`.

**Comment by jchodera** [comment]
Ah, I see that is clearly explained [here](http://parmed.github.io/ParmEd/html/structure.html#structure-slicing-and-selections).  I wonder if there is a way to make this behavior less surprising....?

**Comment by hainm** [comment]
@jchodera  I will leave the detail answer to @swails. But I think slicing an array to return a copy is not very suprising in Python world.

You can read "Advanced Indexing" when slicing numpy array.

http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

**Comment by jchodera** [comment]
That's for the pointer!  That seems to be the key here:
> Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view).

**Comment by swails** [comment]
Just to expand a little here. Slicing a list always returns a shallow copy of something in Python. In numpy, it's even shallower (unlike a list, even changes to classically immutable types propagate up to the original container because it is a view).

However, the Structure is not fully analogous to a simple container, since it contains many elements, which are all interconnected (like bonds to atoms, types to bonds, angles, etc.). Couple this with the fact that each item can really only belong to a single TrackedList and a view really is not a practical thing to implement.

So as @hainm pointed out, all slicing and indexing returns the equivalent of a deep copy, unless selecting a single integer, which just returns that atom.

**Comment by swails** [comment]
And thank you @hainm for fielding this question. You gave a good answer.
