### ISSUE TITLE
Is there a mode to preserve residue numbering in Structure?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#273]
Just wondering if `Structure` had the ability to preserve residue ids.

**Comment by swails** [comment]
The number attribute on each Residue is its original index. There is an argument for write_pdb that will use the original numbering if present. It's in the docs but I'm on my phone now so can't check easily.

**Comment by jchodera** [comment]
> There is an argument for write_pdb that will use the original numbering if present. It's in the docs but I'm on my phone now so can't check easily.

Ah!  I must have missed that!  Thanks!

**Comment by jchodera** [comment]
For the record, the argument `renumber` is set to `True` by default:
http://parmed.github.io/ParmEd/html/structobj/parmed.structure.Structure.html?highlight=write_pdb#parmed.structure.Structure.write_pdb

**Comment by swails** [comment]
Yes, that is the default behavior. I tend to solvate my pdb files, and as a result most of the residues do not have an assigned number (at least that's true for the pdb files I want to _write_ with parmed as opposed to just analyze). In cases like that, renumbering is the safest way to go. And since renumbering is never *wrong*, and only sometimes inconvenient, that's the default I went with.
