### ISSUE TITLE
pmd.tools.printBonds(p, 1)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#277]
Jason,

what should I expect when using above command?

It's likely that there is no different between 
`pmd.tools.printBonds(p, 1)` and `pmd.tools.printBonds(p, 100)`

**Comment by swails** [comment]
It issues an `UnhandledArgumentWarning`.  By default, the `SeriousParmWarning` class is *not* a fatal error, but rather a simple warning.  If you run the command:

```Python
import warnings
warnings.filterwarnings('error', category=pmd.tools.exceptions.SeriousParmWarning)
```

and then try your command, it will throw an exception.  The reason you don't see the warning is likely because the printout from `printBonds` floods the output and hides it.

The `print*` methods usually take Amber masks, and a standard integer will not be recognized.  If the warnings are non-fatal, then they are ignored and the default selection for `printBonds` is every atom.

**Comment by swails** [comment]
Is the explanation satisfactory?  Can this be closed?

**Comment by hainm** [comment]
> On Jul 22, 2015, at 12:45 AM, Jason Swails <notifications@github.com> wrote:
> 
> Is the explanation satisfactory?
> 
Yes, clear to me. But the I still think printBonds(p, 1) is a bug in ipython. :d

**Comment by hainm** [comment]
Sorry, I replied by email. Post again

"Yes, clear to me. But the I still think printBonds(p, 1) is a bug in ipython. :d"

**Comment by swails** [comment]
> Yes, clear to me. But the I still think printBonds(p, 1) is a bug in ipython. :d

It *is*.  The bug is that `printBonds` takes a mask and that example provides an integer. ;)

This action does have error checking on user input, but it's in the form of a non-fatal warning.  As I've said before, `parmed.tools` is basically the machinery used to power the CLI and GUI apps.  Turning them into an API was more of an after-the-fact consideration and was one of the first steps in moving ParmEd from strictly a program with an API only I used to a general, documented API by design.  So it still has residual behavior that reflects those origins (among them, the non-fatal default behavior of the command-line warnings).

#284 turns those warnings into fatal errors by default.  So now you get something like:

```Python

In [1]: import parmed as pmd

In [2]: l = pmd.load_file('test/files/trx.prmtop')

In [3]: pmd.tools.printBonds(l, 1)
---------------------------------------------------------------------------
UnhandledArgumentWarning                  Traceback (most recent call last)
<ipython-input-3-80c34a7afec3> in <module>()
----> 1 pmd.tools.printBonds(l, 1)

/iscratch/swails/src/ParmEd/parmed/tools/actions.py in __init__(self, input_parm, arg_list, *args, **kwargs)
    214         unmarked_cmds = arg_list.unmarked()
    215         if len(unmarked_cmds) > 0:
--> 216             warnings.warn(' '.join(unmarked_cmds), UnhandledArgumentWarning)
    217         self.valid = True
    218 

UnhandledArgumentWarning: 1
```

**Comment by hainm** [comment]
Kool

**Comment by hainm** [comment]
@swails 

printDetails too.

**Comment by swails** [comment]
All actions will behave this way.  Any unhandled arguments yield a `UnhandledArgumentWarning` which users can toggle to be fatal or not.

They now start off fatal by default, so what I showed with `printBonds` should be what happens with every other `print*` method now.
