### ISSUE TITLE
Add a `view` indexer (WAS: get atom indices?)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#278]
Jason,

I am not clear how to get atom indices from parm selection.

In `pytraj`, I can do this
```python
top = pt.load_topology("my_file.pdb")
top.select("@CA").indices # atom indices
```

if not, may be parmed can add `select` method like `mdtraj` to return indices?

**Comment by swails** [comment]
> I am not clear how to get atom indices from parm selection.

Use a listcomp instead:

```Python
top = pmd.load_file('my_file.pdb')
[a.idx for a in top.atoms if a.name == 'CA']
```

Atoms are always reindexed in a selection -- this is part of the discussion in #272 where I explained why making a selection into a view wasn't really tractable.

An idea I just had, though:  what about making a `view` attribute that can be indexed like a typical `Structure`, but returns something equivalent to a view rather than a deep copy?  So something like this:

```Python
top = pmd.load_file('my_file.pdb')
[a.idx for a in top.view['@CA'].atoms]
# or, alternatively
[a.idx for a in top.view('@CA').atoms]
```

**Comment by hainm** [comment]
yes, returning a 'view' is desirable since sometimes I (and users) only need to care about atom indices, nothing else.  

Per
```python
top = pmd.load_file('my_file.pdb')
[a.idx for a in top.atoms if a.name == 'CA']
```
what's about more complicated selection?

Since `parmed` already has atom mask selection, so returning its index is trivial (I guess :D). So ideally, I would love to see parmed having a method, like 'select' to return indices (rather explicitly doing listcomp).

The motivation is I want to connect parmed and pytraj. Sometimes we need to rename the residue, atom, ... later we want to get their indices and feed to `pytraj` to do whatever we want. I can do this with `pytraj` Topology but I think if `parmed` has index selection, it's more convenient and more flexible.

**Comment by swails** [comment]
> what's about more complicated selection?

Then the `if` clause becomes more complicated:

```Python
# Equivalent to top['B',['ALA'],['CA']]
[a.idx for a in top.atoms if a.name in ('CA', 'C', 'N') and a.residue.name == 'ALA' and a.residue.chain == 'B']
```

> Since parmed already has atom mask selection, so returning its index is trivial (I guess :D).

It is with the `AmberMask`:

```Python
list(pmd.amber.AmberMask(top, '@CA').Selected()) # Selected() is a generator
```

I'll mark this as an enhancement request (and change its name so I can see what the request is) to add a `view` indexer (akin to how `pandas.DataFrame.loc` behaves).

**Comment by hainm** [comment]
thanks

**Comment by swails** [comment]
This can be useful for some of the modeling ideas I have in mind.

**Comment by hainm** [comment]
@swails may be you can make a list of things that tleap fails to do in this repo.

**Comment by hainm** [comment]
and might use sklearn to mine/learn from amber mail-list :))

**Comment by hainm** [comment]
Jason

So those commits will make atom selection easier? 

parm.select('!:WAT')

**Comment by swails** [comment]
> So those commits will make atom selection easier?

How was it hard to begin with?  It's just `parm[<selection>]`.

> parm.select('!:WAT')

What is `select` supposed to do?  Right now `parm['!:WAT']` or `parm.view['!:WAT']` works by returning a full copy of the relevant portions or a view of the relevant portions, respectively.  How would `parm.select()` be any different?  I don't see how `parm.select(X)` is any easier than `parm[X]`.  It actually seems to me that it would be more restrictive, since `select()` wouldn't be able to take the traditional slice syntax (you'd need to pass explicit `slice()` objects:

```Python
In [1]: class MyClass(object):
   ...:     def select(self, *args):
   ...:         print('Got args:')
   ...:         print('\t' + '\n\t'.join([str(a) for a in args]))
   ...:         

In [2]: x = MyClass()

In [3]: x.select(0, 1, 1:10)
  File "<ipython-input-3-fe1e4082d2c3>", line 1
    x.select(0, 1, 1:10)
                    ^
SyntaxError: invalid syntax


In [4]: x.select(1, 1, slice(1, 10))
Got args:
        1
        1
        slice(1, 10, None)
```

So if `select()` is just going to be a subset of either `[]` or `.view[]`, I don't see the point.
