### ISSUE TITLE
better **kwargs for load_file

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#290]
this is the reason why

```python
In [4]: pmd.load_file("http://ambermd.org/tutorials/basic/tutorial4/files/sustiva.mol2",
structure=True)
Out[4]: <Structure 30 atoms; 1 residues; 32 bonds; NOT parametrized>




In [5]: pmd.load_file("../tests/data/tz2.pdb", structure=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-993ae273f07f> in <module>()
----> 1 pmd.load_file("../tests/data/tz2.pdb", structure=True)

/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/formats/registry.py in 
load_file(filename, *args, **kwargs)
    129                             name, arg)
    130     if hasattr(cls, 'parse'):
--> 131         return cls.parse(filename, *args, **kwargs)
    132     elif hasattr(cls, 'open_old'):
    133         return cls.open_old(filename, *args, **kwargs)

TypeError: parse() got an unexpected keyword argument 'structure'
```

I would like to see 'structure=True' work for `load_file` with all filenames. If not, `pytraj` need to check if the file is mol2 or not (by checking if "ResidueTemplate"). "ResidueTemplate" does not have "save" method. (pytraj use `save` to save `Structure` to pdb file and reload).

**Comment by hainm** [comment]
if not, another option: Is there any way to convert to `Structure` from `ResidueTemplate` internally without saving to `mol2` file first?

```python
if isinstance(p, ResidueTemplate):
    s = p.to_structure()
```

**Comment by hainm** [comment]
if none of the above work, I think `load_file` should always return `Structure` as default. If people want to load mol2 file to `ResidueTemplate`, they should use `template=True`

**Comment by swails** [comment]
> if not, another option: Is there any way to convert to Structure from ResidueTemplate internally without saving to mol2 file first?

Not really.  This works for single-residue molecules, but not for any type of internal polymer residue.  A multi-residue mol2 file (either as a mol2 file with several, concatenated `@<MOLECULE>` sections or with a single `@<MOLECULE>` within multiple residues) returns a `ResidueTemplateContainer` that would need to be stitched together to reconstruct the full `Structure`.

> if none of the above work, I think load_file should always return Structure as default. If people want to load mol2 file to ResidueTemplate, they should use template=True

Your use case is different than mine, and your suggestion makes sense when viewed from pytraj's perspective.  But it doesn't make sense for moving ParmEd forward as a tleap replacement or general modeling tool.

That said, I want to cater to your needs here since it is a fully legitimate use-case. 

> Ideally, I wish to have code like this
> 
```
> p = pmd.load_file(url, structure=True)
> top = pt.load_parmed(p)
```

This is my preferred route.  I can special-case the `structure` keyword to make sure it's only passed to the `Mol2` file (or maybe I can do some kind of introspection and only pass it to classes that take `structure` as an argument).  Will this work?

**Comment by hainm** [comment]
> This is my preferred route. I can special-case the structure keyword to make sure it's only passed to the Mol2 file (or maybe I can do some kind of introspection and only pass it to classes that take structure as an argument). Will this work?

it's up to you. To me (as user's perspective), I just need a consistent and predictable way to load a file to `Structure` (either pdb, parm7 or mol2) or the return object has `save` method  that can writes to pdb file. :D 

currently, `pytraj` need to overcome by `try except`
https://github.com/pytraj/pytraj/blob/master/pytraj/io.py#L79-L84
