### ISSUE TITLE
should `load_file` always return a Structure

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#291]
This closely relates to https://github.com/ParmEd/ParmEd/issues/290 and we dicuss before.

But after writing code converting parmed' Structure to pytraj' Topology file, I think it's better to have `load_file` to return `Structure`, which is parmed's core. If not, another package like `pytraj` need to add more complicated code 'if ... else' checking.

If you still prefer `load_file` as a universal method, I would love to see parmed have additional method, like `load_structure` to return a `Structure` object.

The point is `load_file(filename, structure=True)` does not always work with `parmed`.

**Comment by swails** [comment]
No, `load_file` should not always return a `Structure`.  It returns whatever object corresponds to the recognized type.  But file detection also works for NetCDF trajectories and restarts, Amber OFF libraries, CHARMM coordinate files, and CHARMM restart files.  These clearly should not (and cannot) return a `Structure`.  Mol2 files are the only file types that can return different things depending on what you want to do with it.  Since I *always* use them as residue templates and never as a PDB replacement, I chose to have it return a `ResidueTemplate` by default rather than a `Structure`.

I see `load_file` as a shortcut.  It provides a single interface to parse a file, and the idea is that more often than not, the format of the file is known beforehand.  But some parsers are `staticmethod`s on a parsing class (that basically provides a single namespace to contain the format identifier, writing routine, and parser that is amenable to being added to the registry easily using a metaclass) while others are part of the standard instance initializer (`__init__`).  `load_file` figures out what needs to be done and removes the headache from needing to know whether the relevant parser is called like `MyParserClass.parse('filename')` or `MyParserClass('filename')`.

So I think the only issue here is how do we handle your particular use case (which is similar to the use case I have for the `parmed` CLI/GUI where `parm` should be able to load a Mol2 file as a parm.  So let's close this and return the discussion to #290
