### ISSUE TITLE
load_file(pdb_id_or_cif_id) + download_PDB to download_pdb

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#313]
* since `load_file` is universal load method (file, url, ...), what do you think about "load_file("1l2y")`?

(same as download_PBD("1l2y")). If there is a file name "1l2y" on disk, parmed will load this file rather loading pdb file. or just to implicit? 

* what do you think about shorten 'download_PDB' to 'load_pdb' or 'download_pdb'? (given that you have `write_pdb`, 'write_cif`). Not using capitalized word saves my time. :D

**Comment by swails** [comment]
> (same as download_PBD("1l2y")). If there is a file name "1l2y" on disk, parmed will load this file rather loading pdb file. or just to implicit?

Too implicit.  This amounts to trying to guess user intent rather than user instruction, which I don't want to be in the habit of doing.  It would also require a fair amount of additional code complexity to make sure that PDB queries were only done when there was a reasonable expectation that a PDB query was *intended*, and to avoid spoiling the error message with something cryptic.

And then you have instances where people want to load their modified "1L2Y.pdb" file but forget the `.pdb`, only to get something that looks almost correct (especially bad).  The opposite is also possible (`1L2Y` exists locally, but users *really* wanted it downloaded).  And issues like this are particularly difficult to hunt down remotely, since the "buggy" behavior depends on the contents of their current folder (which will make it harder to debug if people report it as a problem).

> what do you think about shorten 'download_PDB' to 'load_pdb' or 'download_pdb'?

Tab-completion can help you with the typing, `download` is more explicit than `load`, and `download_PDB` matches `read_PDB`, which has been around for a long time and is used in a number of places.  So I'd personally rather keep the names (not really a good enough reason IMO to be breaking scripts).
