### ISSUE TITLE
Possible bug in the box dimensions in the gromacs module

### ISSUE THREAD

**Issue by nividic** [ParmEd/ParmEd#322]
Hi there,

I was trying to convert amber topology files between amber and gromacs by using parmed in python:

import parmed

structure = parmed.amber.AmberParm( 'system.prmtop', 'system.inpcrd')
gromacs_topology = parmed.gromacs.GromacsTopologyFile.from_structure( structure )

gromacs_topology.write('test.top')
parmed.gromacs.GromacsGroFile.write( gromacs_topology, 'test.gro')

Unfortunately the box dimensions written in the .gro file look wired to me but I'm not a gromacs expert.

I checked the file parmed file  "gromacstop.py" and in particular the function "from_structure". Apparently (I'm not sure) the box dimensions are not copied i.e. it is missing something like:

gmxtop.box=struct.box

Would you mind double checking please? If it will be necessary I'll send you my input files. 

Cheers,

Gaetano

**Comment by hainm** [comment]
> Unfortunately the box dimensions written in the .gro file look weird

How weird it is? :P

**Comment by nividic** [comment]
The coordinate file in amber has box dimensions in angstroms:  34.4570000  34.4570000  34.4570000. After conversion the gromacs .gro file has box dimensions (nm?): 
0.96023   1.01003   0.97784

**Comment by swails** [comment]
A couple things.  First, Gromacs uses nanometers internally (and kJ/mol, picoseconds, and daltons).  So you should expect coordinates and unit cell vectors to be 0.1 times the magnitude of what you see in Amber files.

Secondly, the unit cell information in Gromacs is stored as "reduced" unit cell vectors (that is, the first vector has to have a maximum projection on X, the second a maximum on Y, and the third is defined from the other two.  And the Gromacs unit cell vectors in the GRO file are defined in a very strange order.  See [the GROMACS Gro file documentation](http://manual.gromacs.org/current/online/gro.html) for more information about how the box is stored.

That said, the box dimensions you reported don't make any sense for either an orthorhombic box (in which case they should all be 3.4457) or for a truncated octahedron (in which case the 3 vectors in reduced form are shown below):

```
((3.4457, 0.0, 0.0),
 (-1.1485665739920026, 3.2486371473447564, 0.0),
 (-1.1485665739920026, -1.6243183770797334, 2.8134024107811766))
```

That said, I don't *think* that ParmEd is doing the box conversions incorrectly (since they've been checked on a couple different box shapes), but I may certainly be mistaken.  One thing that helps limit the occurrence of errors is that ParmEd always stores unit cell data in the same format -- a 6-element array of the 3 lengths (a, b, c) and 3 angles (alpha, beta, gamma), which it then converts to the required format whenever writing files that require that information.

Do these files not work with Gromacs if you try them?  If not, I would need to see the original files, I think.

**Comment by swails** [comment]
Also, some tips on simplifying your Python script:

```Python
import parmed

structure = parmed.load_file( 'system.prmtop', 'system.inpcrd')
structure.save('test.top', format='gromacs')
structure.save('test.gro')
```

The `save` function was a very nice suggestion by @hainm, and it reduces the code to something much more succinct.

**Comment by nividic** [comment]
Thanks Jason and hainm for your prompt reply. The problem seems to be the script:

import parmed

# #This works
# structure = parmed.load_file( 'system.prmtop', 'system.inpcrd')
# structure.save('test.top', format='gromacs')
# structure.save('test.gro')

#This does not work
structure = parmed.amber.AmberParm( 'system.prmtop', 'system.inpcrd')
gromacs_topology = parmed.gromacs.GromacsTopologyFile.from_structure( structure )
gromacs_topology.write('test.top')
parmed.gromacs.GromacsGroFile.write( gromacs_topology, 'test.gro')

I don't know which of the two methods is the official one, but in my opinion will be worse to further investigate the problem. 

Thanks Gaetano

**Comment by swails** [comment]
Yep!  Turns out that the unit cell information was not properly transferred when doing `GromacsTopologyFile.from_structure`.  I submitted #323 to fix this.

Thanks for the report!
