### ISSUE TITLE
Update file type table for reading

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#370]
http://parmed.github.io/ParmEd/html/readwrite.html

Only have table for 'writing'

**Comment by swails** [comment]
I don't understand what's missing in the docs.  The docs for `load_file` lists every file type that is supported (note that the user doesn't have to do anything -- ParmEd should automatically determine the filetype of any file whose type is in the list on that webpage).  Only `Structure.save` *needs* a table, because only the *writing* format actually needs to specify a file type (since how can any program know what type a non-existent file is??).  If the file already exists (as it must for `load_file`), then clearly the format must also be defined, so that is not user-controllable.  Ergo, no table (just a list).

**Comment by hainm** [comment]
In my opinion, it's easy to find key/file type that ParmEd supports if it's in table. It's more eye catchy.

And it' easy to look if using phone or tablet :)).

**Comment by swails** [comment]
Fair enough.  Do you want to add it to your open PR, or wait for me to submit a PR for it?

**Comment by hainm** [comment]
I think I will wait for you. I will finish the slice stuff + pytraj doc first.

(I only know ParmEd nicely support OFF file when asked you today). Too lazy to read so many text (that's why I like comics. lol)
