### ISSUE TITLE
how to write test case for parmed

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#376]
I am just curious how you test your code change? for example, for my `charge` property PR, I added test code to one of your test files. But it took too long to see the test pass.

**Comment by swails** [comment]
What *I* do is to add a test case to one of the `test_parmed*.py` files, then run *just* that file from the ParmEd directory via:

```
nosetests -vs test/test_parmed_<file>.py
```

Just to make sure that the test I added is actually run automatically by `nose`.  Then, for subsequent tests, I use

```
nosetests -vs test/test_parmed_<file>.py -m testNewMethod
```

Where `testNewMethod` is the name of the test function you just added.  This will test *only* the function you added (but it's important to check whether or not `nose` will automatically run your test, which is why I don't start out with the second command).

Perhaps someone that knows `nose` better than I do will have better advice, but that's what I do and it seems to work just fine.

**Comment by hainm** [comment]
> nosetests -vs test/test_parmed_<file>.py -m testNewMethod

Oh, this is what I am looking for. Thanks.
