### ISSUE TITLE
[wishlist] autocompletion for lowercase

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#378]
`printDi<tab>: yes`
`printd<tab>: no`

**Comment by swails** [comment]
autocomplete works for all listed and documented commands.  The only reason case-insensitive commands are *also* recognized is because other programs in Amber do the same (LEaP, cpptraj, etc.), but the camelCase names are the ones that are documented, listed by help, autocompleted, and available through the API.  So you can do printDihedral, printdihedral, PrintDihedral, PRINTDIHEDRAL, pRiNtDiHeDrAl, ..., but only printDihedral is autocompleted.

**Comment by swails** [comment]
I didn't go out of my way to *disable* lower-case autocompletion, but I deliberately made no attempt to support it, nor is it important for me.  It's also not a trivial addition, since autocomplete keywords are auto-generated by the `do_someCommand` methods on the `cmd.Cmd` class.  It would take some effort to get the `ParmedCmd` class to recognize case-insensitive autocompletes.

**Comment by hainm** [comment]
i see.
