### ISSUE TITLE
pmd.convert pmd.summary bla bla for cmd

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#399]
From this
https://github.com/robdmc/pandashells/blob/master/README.md

I am thinking about doing similiar thing for pytraj. 

What do you think about parmed?

(Given that it is faster to use '<tab>'

**Comment by hainm** [comment]
tab

**Comment by swails** [comment]
I don't know what this is supposed to be a suggestion for?

**Comment by hainm** [comment]
I meant currently parmed has a script called ``parmed`` (new of ``parmed.py``). What's about adding ``pmd.convert``, ``pmd.inspect`` (or ``pmd.summary``), .``pmd.printBonds``, ... scripts so we can use in the terminal. Just for quickly solve simple task.

```bash
$ pmd.convert test.parm7 test.pdb
$ pmd.summary test.parm7
...
```

The benifit is to use ``<TAB>`` to complete, so this will save lots of time.

But I think this might me a crazy idea, users can make the script by their own (like I am doing).

**Comment by swails** [comment]
`parmed convert <args>` is planned (as per #341), since that really *can't* be done very easily in `parmed` right now.  The concept and technology behind pandashells is neat (and I can see the use-case for data analysis, as I've utilized pipeline-based workflows with some RDB tools), but I think it only adds confusion for the average user of the `parmed` interpreter (which is quite different than the average user of the ParmEd API).

**Comment by hainm** [comment]
agree.
