### ISSUE TITLE
add flag_name=, flag_format=?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#401]
currently

```python
p.add_flag(flag_name, flag_format, data=None, num_items=-1, comments=None, after=None)
```
``flag_name, flag_format`` are positional arguments so there is no autocompletion.

What do you think?

**Comment by swails** [comment]
There are no sensible defaults for `flag_name` or `flag_format`...

**Comment by hainm** [comment]
what's about None?

**Comment by swails** [comment]
I don't think positional arguments are bad just because IPython doesn't make them tab-completable.  Every flag requires a name and a format, and that format needs to be consistent with the data type in the added flag, so there is no sensible default.  IMO, positional arguments make sense here, and I'd rather not change that.
