### ISSUE TITLE
Precision reduction on writing to .gro file

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#405]
Right now, when translated, .gro files seem to be truncated to 3 digits, which can result in a loss of precision.  .gro files are perfectly happy with more than three digits of precision in the coordinates (as long as x, y, z have the same precision), so I would suggest writing out the gro files at the same precision the input files are in.  

Otherwise, one is guaranteed that the energies generated running AMBER on the input file and running GROMACS on the output will not match (by 0.5-ish kcal/mol in the sample problems I'm testing, making it very hard to spot any other issues.

**Comment by mrshirts** [comment]
Same with the box vector at the end -- precision is arbitrary as long as all are the same.

**Comment by davidlmobley** [comment]
There is an optional argument on write which allows you to specify
precision.

**Comment by mrshirts** [comment]
Ah, that is useful to know.  Will test this out.

**Comment by mrshirts** [comment]
Possibly the default behavior should be to set to the precision of the input file, though.

**Comment by swails** [comment]
As @davidlmobley said, there is a `precision` argument that specifies how many decimals will be printed to each number: [see here](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacsgro.py#L173-L189).  The reason I chose 3 is because that *seems* to be the default in most of the GRO files I've seen (in fact, I didn't even realize at first that GRO files could take arbitrary precision until @leeping told me).

> Possibly the default behavior should be to set to the precision of the input file, though.

There is no way to know this information in a majority of cases, and it's never attached to the data structure sent to the GRO writing routines.  If I write a command-line converter program using ParmEd (and/or InterMol), then I can store this information and use it (and I would), but in the API the coordinates can come from literally anywhere.  At last count, there are ~10 different coordinate file formats supported, and in many cases they simply return or set a `coordinates` (and/or `box`) attribute on a `Structure` instance.  You can also use Rosetta to generate poses, in which case there *is* no input precision.  For `.gro` files, it's really up to the programmer to know what level of precision they want to save their files at.

One last thing I'll point out is that GRO files will need one more decimal than most other formats owing to their use of nm while most other files store Angstroms (and like the input precision, input units are never stored -- they are simply always converted to the AKMA system ParmEd uses internally).

**Comment by mrshirts** [comment]
Hi, Jason-

Thanks for the detailed information.  I was indeed able to use precision correctly.  

If we as planned generalize the automated all-to-all converter to use parmed, we can add in a precision check here and make sure any output gromacs file uses the precision from the input file.  That's really the only time we would really want to have the precision match - if one is just generating a file for a run, its not really needed.

**Comment by swails** [comment]
I think this can be closed.  Reopen if I'm mistaken.
