### ISSUE TITLE
diff two structure?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#419]
Is there any command to diff two structures? (I searched 'diff' and 'compare') in website but found nothing.)

```python
parm1 = pmd.load_file(...)
parm2 = pmd.load_file(...)
pmd.tools.diff(parm1, parm2)
```

**Comment by swails** [comment]
No, there's no way to do this currently.  It's also not easy to do, since a difference is not well-defined.  Does order of atoms and residues matter?  What about the order that the bonds are defined? (A little tidbit -- if you use the `copy` command in tleap and save a prmtop file using the original unit and the copy, the atom and residue sequences will remain unchanged but the topology and parameter lists will be reordered.)

I've occasionally wished I had at least an `__eq__` definition for `Structure`, but even that is not really well-defined...

**Comment by hainm** [comment]
Uhm, so our problem is: 'define' the difference first. :d
