### ISSUE TITLE
load_dataframe from json (class method)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#420]
are you intending to reconstruct ``Structure`` from DataFrame?

below does work
```python
df  = parm.to_dataframe()
pmd.Structure.load_dataframe() # object's method rather class method.
```

My question is relating to https://github.com/ParmEd/ParmEd/pull/418
```python
parm.to_dataframe().to_json('test.json')
pmd.Structure.load_dataframe(pd.read_json('test.json'))
```

**Comment by swails** [comment]
> are you intending to reconstruct Structure from DataFrame?

No, we discussed this in #270 awhile ago.  The generated DataFrame only contains atomic properties.  It's missing all topology features (e.g., bonds, angles, dihedrals, ...), as well as parameters, making it unsuitable for use as 

> My question is relating to #418
> 
```
> parm.to_dataframe().to_json('test.json')
> pmd.Structure.load_dataframe(pd.read_json('test.json'))
```

I think #418 renders this a negative addition.  #418 already implements better serialization, and does so completely in a way that deserialization properly instantiates the originally serialized subclass with all of its original data.  This proposal would introduce an alternative serialization scheme (going against the Python mantra of having one, and only one obvious way to do something), with worse compression, that doesn't automatically instantiate the correct class from which the data frame was generated, and that almost always results in an incomplete reconstruction of the original object.

This approach *will* work as long as you intend to use `load_dataframe` as an instance method rather than an alternative constructor (which is what `load_dataframe` is intended for).

**Comment by hainm** [comment]
> No, we discussed this in #270 awhile ago.

I feel old. :(
