### ISSUE TITLE
pandas

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#433]
parmed skipped lots of tests with pandas. should add pandas on travis?

**Comment by swails** [comment]
There are two "types" of builds here, one with all packages installed, and one with only numpy installed to make sure it continues exposing the supported functionality when optional packages are not installed.  So if you clicked on the (Python 3.3) MINIMAL_PACKAGES build, then it skips a lot of tests.  Otherwise, it just skips the ones requiring Rosetta, tleap, and "big" tests that take a lot of time in OpenMM.

See [here](https://github.com/ParmEd/ParmEd/blob/master/devtools/travis-ci/install.sh#L20)

This is what *should* happen.

**Comment by swails** [comment]
Sorry -- didn't mean to close.  If you're seeing something other than what I described above, let me know.  Otherwise I think this can be closed.

**Comment by hainm** [comment]
yeah, turned out that I looked at MINIMAL_PACKAGES. close now.
