### ISSUE TITLE
Splitting and re-merging a GROMACS topology results in incorrect FudgeLJ and FudgeQQ

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#450]
FudgeLJ and FudgeQQ in GROMACS topologies are being re-set to incorrect (default?) values upon splitting and re-merging a GROMACS topology file. For example:

'''
system = parmed.load_file('159.top')
system.write('output1.top')

components = system.split()
outputsys = components[0][0] * len(components[0][1])
outputsys.write('output2.top')
'''

In this case, `output1.top` has the correct values (0.5 and 0.833 for fudgeLJ and fudgeQQ, respectively) but in output2.top, they are incorrect (1 and 1, respectively).

Input topology file for the above example: https://dl.dropboxusercontent.com/u/3409095/159.top

We've had to kill a number of things we were running because they apparently had incorrect scaling factors as a result of this issue.

@bannanc, this is the issue you mentioned.

**Comment by bannanc** [comment]
This is the issue, thanks for submitting the request!

**Comment by swails** [comment]
Sorry about that!  I'll make fixing this top priority.

**Comment by swails** [comment]
OK.  I have this fixed.  Sorry about the inconvenience!  I have a rather longer explanation for why I didn't catch it before, but the fix itself is pretty straightforward.  I've also added a version bump to that PR so you can add a check for it in whatever program/application you may be writing with ParmEd to make sure you get the right answer (minimum version 2.0.4)

Sorry again!  It's a rather embarrassing mistake...

**Comment by swails** [comment]
Another thing I added in this PR, since I needed something better than I had before, is the ability to more easily detect ParmEd version and set up minimum version requirements programmatically.

Starting with this PR, you can use `parmed.version` as a tuple that has `(major, minor, patch-level)` attributes (with an optional beta field where applicable).  So if you want to add a quick check, you can do:

```Python
import parmed as pmd

if pmd.version < (2, 0, 4):
    raise RuntimeError('ParmEd is too old! Please upgrade.')
```

For any version that's really below 2.0.4, this will throw an `AttributeError`, but going forward this will continue to work.

It also works with betas (so 2.0.4-beta1 is greater than 2.0.3, but less than the actual 2.0.4 non-beta release).
