### ISSUE TITLE
add Box class?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#466]
currently ParmEd treats Box as ndarray. What do you think about make it a separate class Box?

pytraj/cpptraj has its own class.

```python
import parmed as pmd
box = Box([...])
box = Box()
box.type = 'ortho' # --> auto assign alpha, beta, gamma values
box.center
```

**Comment by swails** [comment]
I've thought about it before, but I was never able to convince myself it was a good idea.  cpptraj doing it is not a convincing argument one way or the other -- C++ and Java patterns are very frequently not Pythonic (and MDTraj works the same way ParmEd does).

Some questions:

- How much complexity does this code add (compared to the current simple 6-element ndarray)?
- Does this break backwards compatibility? (Can this be avoided? at what cost in code complexity?)
- What is the benefit?


```Python
> import parmed as pmd
> box = Box([...])
> box = Box()
```
I can't think of a time when I've *set* box information outside of a parser.  And inside a parser, I usually just read the unit cell dimensions (or box vectors) and set the attribute directly.  Like [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/_amberparm.py#L225-L227) and [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacsgro.py#L150-L161) and [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L523-L533) and [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L1182-L1186) (and there might be a couple other places).

```Python
> box.type = 'ortho' # --> auto assign alpha, beta, gamma values
```

How much easier is this than `struct.box = [a, b, c, 90, 90, 90]`?  i.e.,

```Python
struct.box = [a, b, c, 90, 90, 90]
# vs. something like
struct.box.type = 'ortho'
struct.box.set_lengths(a, b, c)
```

```
> box.center
```

I'm not even sure what this would do.  Give the coordinates of the center of the box?  But I'd like to see some examples of how this would make things better, and how we could mitigate backwards-incompatible changes.

**Comment by hainm** [comment]
> I've thought about it before, but I was never able to convince myself it was a good idea. 

I can't, either :P 

> How much complexity does this code add (compared to the current simple 6-element ndarray)?
Does this break backwards compatibility? (Can this be avoided? at what cost in code complexity?)

Not much, ten lines of codes. I don't concern about backwards compatibility if Box is just a numpy array wrapper

```python
class Box(object):
    def __init__(self, data):
        self.data = data

    def __array__(self):
        return np.asarray(self.data)
```
--> just it

> What is the benefit?

I don't know yet. I've just had Box for ParmEd in mind after reading your email (sent to us) today. Just want to have 'Box' more abstract rather working with number. [90.0, 90.0, 90.0] are easy numbers to remember but not easy with other box types.

Per
```python
struct.box = [a, b, c, 90, 90, 90]
# vs. something like
struct.box.type = 'ortho'
struct.box.set_lengths(a, b, c)
````
you can still autocast `struct.box = [a, b, c, 90, 90, 90]`

```python
@box.setter
def box(self, arr):
    return Box(arr)
```

>> box.center

>I'm not even sure what this would do. Give the coordinates of the center of the box? But I'd like to see some examples of how this would make things better, and how we could mitigate backwards-incompatible changes.

:D, just typing as illustration. 

Anyway, box has only 6 numbers. So it might be a big deal in either way.

**Comment by swails** [comment]
> Not much, ten lines of codes. I don't concern about backwards compatibility if Box is just a numpy array wrapper
> 
```
> class Box(object):
>     def __init__(self, data):
>         self.data = data
> 
>     def __array__(self):
>         return np.asarray(self.data)
> 
>     def __setitem__ ...
```
> --> just it

[There is already more error-checking than that in the current code](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1564-L1590) :).  One of the reasons that @drroe uses a separate `Box` class is that it lets him isolate all of the PBC-specific code there.  There are multiple useful representations of unit cells, the two principal ones being as dimensions (like what `Structure.box` is, and how Amber files store them), and the second being as the H-matrix (which is what codes use internally to convert to scaled coordinates in order to do MIC).

Having a single `Box` class in cpptraj lets you ask for which representation you want from the same set of data (eliminating the chance that different representations fall out-of-step).  This is a very good benefit, and a very good use for a class.  But C++ does not have descriptors in the same sense that Python does -- I get the same benefit, but `box` and `box_vectors` are separate attributes on `Structure`.  Is this better than `Structure.box.vectors`?  Meh.  According to the Zen of Python (flat is better than nested), the answer would seem to be "maybe slightly worse"... or perhaps "maybe slightly better".  I think there is no clear answer.

`box_vectors` and `box` still derive from the same underlying array, though (as it does in MDTraj as well), so they never fall into disagreement. So I get (what I've always seen as) the main benefit of having a `Box` class in a way that looks like a simple ndarray attribute.  And I already have a module where I dump useful functions for PBC manipulation.

The way I see it, users should rarely have to *use* the `box` and `box_vectors` attributes for anything -- they're mostly for use internally whenever something requires imaging.  And as rarely as I have need to directly *use* `box` outside of ParmEd internals, I've almost never (outside of debugging) had to actually *modify* it.
