### ISSUE TITLE
Possible issue with Parmed/OpenMM and new Amber14/lipid14 force field

### ISSUE THREAD

**Issue by dr-nate** [ParmEd/ParmEd#468]
See my issue over here: https://github.com/pandegroup/openmm/issues/1218

**Comment by swails** [comment]
I follow both repos, so I saw that issue when you first posted it. 

It's good to have a stub here to help keep track of potential issues, but the fact that it breaks with both AmberPrmtopFile and AmberParm in the same way suggests to me that the problem lies elsewhere. Or is at least present in both ParmEd and OpenMM. 

So let's keep the discussion about this issue over there for the time being. When I'm not forced to use my phone, I will post more helpful responses there :)

**Comment by dr-nate** [comment]
Ok great. Yea, I wasn't sure what to do, but I thought it might help someone else in the future if I posted here too. Thanks for the help!

**Comment by dr-nate** [comment]
Closed because it was not a Parmed/OpenMM issue. See issue linked in first comment.
