### ISSUE TITLE
should use new format style

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#498]
FYI: just for future reference:

https://pyformat.info/

It's easier to make mistake with this `%s`
```python
            atomrec = ('ATOM  %5d %-4s%1s%-4s%1s%4d%1s   %8.3f%8.3f%8.3f%6.2f'
                       '%6.2f      %-4s%2s%-2s\n')
```

vs.

```python
'{first} {last}'.format(first='Hodor', last='Hodor!')
```

**Comment by swails** [comment]
These are completely analogous.  What I wrote is akin to

```Python
atomrec = 'ATOM  {0:5d} {1:-4s} ...'
# and later
atomrec.format(i, name, ...)
```

What you wrote is akin to

```Python
'%(first)s %(last)s' % dict(first='Hodor', last='Hodor!')
```

The two string methods are highly analogous, and I don't think one is more error-prone than the other with one exception -- multiple repeated replacements.

The main (only?) advantage of the `'{}'.format()` approach is that you can re-use positional arguments. e.g., `'{0} {1} {0}'.format(1, 2)` will print `1 2 1`.  To do this with the % operator requires `'%s %s %s' % (1, 2, 1)`.  This isn't done in many places, though.

**Comment by swails** [comment]
I personally prefer the `%s` because I'm more comfortable with it and the code is more transferrable to C and C++ (I have on rare occasion copy-and-pasted stuff from Python into C/C++ for testing).  There are times I use `'{}'.format()` in the case of repeated variable output, but I don't need to do that very often.

I also still occasionally write some code that needs to be Py24-compliant (most notably, `update_amber` and other critical utilities that need to be able to run on the system Python on RHEL systems).  If I always use %-substitution, then I never have to worry about backwards-compatibility of the code chunks I use it in.

At the end of the day, the two are typically very similar, and I consider the choice between them largely unimportant.  The only reason I went into this much detail is to show you that I *have* actually thought about this before and that leaning toward % substitution instead of `.format` is a deliberate choice :).

**Comment by hainm** [comment]
:+1:
