### ISSUE TITLE
discussion about supporting more formats

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#508]
I am thinking about adding parser for some formats: sdf, lammps, xyz, ...

Any idea where I should add? to sandbox?

given that only supporting reading to Structure (not writing, no force field pars).

My aim is quite simple:
- I want to use ParmEd to read some extra files (that cpptraj does not support) for molecule viewer https://github.com/hainm/nglview 

- I don't want to make those parsers to pytraj since I want the pytraj API is consistent for all supported formats (like pytraj can load to in and out of core trajectory --> means: out of core trajectory parser code must be in C++, inherited from cpptraj's class).

**Comment by mrshirts** [comment]
Jason Swails, Christoph Klein, and I have been talking about working towards merging ParmEd and InterMol (https://github.com/shirtsgroup/InterMol), which currently supports LAMMPS, Desmond, and Gromacs. There are some nice approaches in InterMol that make it more extensible, though it's definitely less polished than ParmEd.

**Comment by swails** [comment]
The convention I've been following is putting standalone formats inside `parmed/formats/` -- these are formats that are really just their own standards, with no programs behind them defining those formats.  So PDB, PDBx/mmCIF, mol2, ... etc.  Programs themselves, like LAMMPS, get their own folder with all of their classes inside them.

I also see that @mrshirts beat me to the punch mentioning InterMol, which I was about to do :).  What's currently on the docket here is to join these two projects at the API level for now (i.e., teach each package how to understand the others' core molecule data structure), and investigate the feasibility of merging later on.  For LAMMPS and Desmond support, it would be fantastic if the effort for supporting those formats was put into tying InterMol and ParmEd together so that the InterMol parsers themselves could be used.  The benefit there is that ParmEd/InterMol could then provide the conduit between Amber, CHARMM, OpenMM, LAMMPS, GROMACS, and Desmond!

**Comment by hainm** [comment]
> Jason Swails, Christoph Klein, and I have been talking about working towards merging ParmEd and InterMol (https://github.com/shirtsgroup/InterMol), which currently supports LAMMPS, Desmond, and Gromacs.

this is terrific idea. :+1:

**Comment by hainm** [comment]
@swails  
> he benefit there is that ParmEd/InterMol could then provide the conduit between Amber, CHARMM, 
OpenMM, LAMMPS, GROMACS, and Desmond!

I am thinking about using cclib to parse gaussian, gamess, ... (https://github.com/cclib/cclib) to Structure. What do you think?

**Comment by swails** [comment]
> What do you think?

Unless you have a specific use-case in mind, I think it's a waste of time.  My experience running QM calculations is that what is of interest there is very different than what is of interest in MM/MD calculations.  Orbital energies, electron densities, energies, spectroscopic properties, shielding tensors, absolute energies, polarizabilities, frequencies, ...

The reason I'd never done this before was because I never saw what ParmEd's `Structure` had to offer the world of QM.  But that was for my own applications.  If you have a use-case, and you think it's worth your time, then introducing an optional dependency on cclib to support that use-case is definitely welcome.

**Comment by hainm** [comment]
Just for visualization in jupyter notebook :d

**Comment by hainm** [comment]
But admitted that I dont have an use case for myself.

**Comment by swails** [comment]
Going to go ahead and close this.  If someone has a format they want to add, they're more than welcome to (and open up a separate issue for that).  This doesn't need to stay open anymore.

**Comment by swails** [comment]
Oh, this wasn't the issue I thought it was...

**Comment by hainm** [comment]
>  This doesn't need to stay open anymore.

agree.

**Comment by hainm** [comment]
may be you change change the title to be more descriptive?

**Comment by hainm** [comment]
I  close this issue since supported formats in parmed and cpptraj cover my need. And i don't foresee i would implement more myself.
