### ISSUE TITLE
Selecting residues with selection syntax when residue name is a number

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#516]
Normally, it seems `parmed` lets one select perform [residue selections](http://parmed.github.io/ParmEd/html/parmed.html#residue-selections) for a residue like `ALA` via `structure[':ALA']`, or residue number 123 via `structure[':123']`.  But what happens when the residue name is a number, as in the residue named `112` (an ATP analogue) in [`2G1T`](http://www.rcsb.org/pdb/explore/explore.do?structureId=2G1T)?

You can [browse the PDB Ligand Expo](http://ligand-expo.rcsb.org/pyapps/ldHandler.py?formid=cc-browse-search&operation=smiles&target=$&category=aa&first=1) and see that a large number of residues are actually named as numbers.

Perhaps it is worth adding a special way to specify residue names, rather than just detect whether they are a number or not a number?

**Comment by swails** [comment]
What you're describing is the AMBER atom mask selection syntax, and unfortunately that syntax interprets numbers as indices.  It may be possible to bring that up with Amber developers, but ParmEd has to follow what everyone else does there.

As for selecting residues named "123", or some other value that can be cast to an integer, you should use the [more expressive slicing/selection syntax](http://parmed.github.io/ParmEd/html/structure.html#structure-manipulation-slicing-combining-replicating-and-splitting).  For example, to select all residues named `123`, do the following:

```Python
In [13]: import parmed as pmd
    ...: struct = pmd.download_PDB('2g1t')
    ...: print(repr(struct['112',:]))
    ...: print(repr(struct['112',:].residues))
    ...: 
<Structure 140 atoms; 4 residues; 0 bonds; NOT parametrized>
ResidueList([
        <Residue 112[1101]; chain=E>
        <Residue 112[1201]; chain=F>
        <Residue 112[1301]; chain=G>
        <Residue 112[1401]; chain=H>
])
```

**Comment by jchodera** [comment]
Would it just add confusion to support a superset of the AMBER atom mask selection syntax?  Like using the prefix `$:` means the specifier is interpreted as a string instead of a number?

**Comment by jchodera** [comment]
Thanks also for the pointers on the more expressive syntax.  I think that would work for us.

**Comment by swails** [comment]
> Would it just add confusion to support a superset of the AMBER atom mask selection syntax? Like using the prefix `$:` means the specifier is interpreted as a string instead of a number?

I'd personally rather avoid adding to the syntax, so I'd imagine the best approach would be something like `:"123",1,ASP`, where the `"` indicates it's a string.  But one of the problems with supporting a superset of the Amber mask selection syntax is that a typical workflow involves prepping with ParmEd (e.g., via `tiMerge` or other functionalities), running with sander/pmemd, then analyzing with cpptraj.  It's important to me for each of the mask parsers to implement the same functionality to avoid disrupting this workflow (I've been burned by it before, since cpptraj understands the mask string `:ASP:GLU:HIS`, but sander and pmemd do not).

> Thanks also for the pointers on the more expressive syntax. I think that would work for us.

This also works for chain selections, and is quite a bit more flexible, I think.

**Comment by swails** [comment]
Are we good here?  Can this be closed?

**Comment by jchodera** [comment]
Should we at least report this issue upstream on the amber issue tracker?

**Comment by swails** [comment]
Honestly I don't see how this can realistically be fixed with the current mask syntax.  The quote characters are both legitimate characters in atom names (think nucleic acids), so you can't assume that the regex `(["'].*["'])` matches a single name, since that would break perfectly legitimate and commonly-used masks like `@C1',H1'`

There are also two workarounds: use actual numbers (so there is no ambiguity) or use the much older CARD input that will allow you to specify numbers in a "string" section (I believe).  Not to mention this is exceedingly rare (I've never seen someone make a prmtop with purely numeric residue or atom names).  So it would live at the bottom of the priority pile for quite some time most likely.

**Comment by swails** [comment]
Actually, I think I have a workaround.  If you add a `=` to the end of any atom number, it should turn that into a string, hopefully (it acts as a wild-card, and prevents that token from being castable to an int).  The downside is that `1=` will match residue names "1", "100", "1EA", ... etc.  But for 3-character numeric residue names, it should work fine. So in your original case, does

```
structure[':123=']
```

work?
