### ISSUE TITLE
Splitting of dihedrals for a system prepared using ForceField?

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#564]
So I just want to clarify a thing about https://github.com/ParmEd/ParmEd/pull/555 

This is how I'm doing my testing:
``` python
import parmed as pmd
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

parm = pmd.load_file('ala399SBildn.top', 'ala399SBildn.crd')
system = parm.createSystem()

print('AMBER energies:')
print(pmd.openmm.energy_decomposition_system(parm, system))

amber_total = 0
for i in pmd.openmm.energy_decomposition_system(parm, system):
    amber_total += i[1]

print('Total: %s' % amber_total)

pdb = PDBFile('ala3.pdb')
topology = pdb.topology
positions = pdb.positions

ommtop = pmd.openmm.load_topology(topology, xyz=positions)
ff = ForceField('ff99SBildn.xml')
system2 = ff.createSystem(topology)

print('ffxml energies:')
print(pmd.openmm.energy_decomposition_system(ommtop, system2))

ffxml_total = 0
for i in pmd.openmm.energy_decomposition_system(ommtop, system2):
    ffxml_total += i[1]
    
print('Total: %s' % ffxml_total)
```

so I'm creating `system2` using only OpenMM, with the newly converted ffxml. Can I create a system straight from `ommtop` (i.e. can I parametrize a `Structure` with an ffxml?). Otherwise I don't see how I can do the dihedral splitting on `system2` (works good on `system` of course) - and that is where it is really useful. What am I missing here?

**Comment by swails** [comment]
With the Amber force field (since it doesn't rely on a `CustomNonbondedForce`), you can actually load a system with a topology in `load_topology`.  This won't work for all CHARMM force fields, since they rely on CustomNonbondedForce for their NBFIXes.  But you can round-trip anything that doesn't have explicit solvent *and* ions.

I notice a couple problems with your above script though.  The biggest one is that you want to be *sure* you load the same positions into each context.  Different files have different precisions, which can very easily lead to different energies if you are not careful.  When you instantiate `ommtop`, pass `parm.positions` to `xyz` instead of `positions` to make sure the coordinates are *exactly* the same (of course this assumes that the atom ordering is identical in each case -- if you made `ala3.pdb` from tleap this will be true).

Next, instantiate `ommtop` like so:

```Python
ff = ForceField('ff99SBildn.xml')
system2 = ff.createSystem(topology)
ommtop = pmd.openmm.load_topology(topology, system2, xyz=parm.positions)

system3 = ommtop.createSystem()

enelist2 = pmd.openmm.energy_decomposition_system(ommtop, system2)
enelist3 = pmd.openmm.energy_decomposition_system(ommtop, system3)
```

You should compare `enelist2` with `enelist3` to make sure that ParmEd faithfully translated the `System` into parameters (there are "round-trip" tests in ParmEd that you helped me fix recently).  Once you verify that `enelist2` and `enelist3` are the same, then you can do whatever you do to `parm` to `ommtop`.

It's a little convoluted.  Does it make sense?

**Comment by rafwiewiora** [comment]
Oh this is a perfect reply, thanks @swails!

**Comment by rafwiewiora** [comment]
This is working well, closing!
