### ISSUE TITLE
Structure.omm_nonbonded_force adds too many exceptions

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#608]
It seems like ```Structure.omm_nonbonded_force``` adds more exceptions than there should be.

This is the system I have been using:
https://github.com/ChayaSt/openmm/tree/charmm36/devtools/forcefields/charmm/tests

The system only has 117, 38 residues (of which 37 are waters and 1 is methanol) atoms and 79 bonds yet the nonbondedForce has 243 exceptions. Here is the link to the script:
https://github.com/ChayaSt/openmm/blob/charmm36/devtools/forcefields/charmm/tests/test_ffconversion.py

When I create the system in OpenMM, I get 126 exceptions which sounds reasonable. 
Here is the output from the script:

```
In [18]: %run test_ffconversion.py
potential energy from openmm nan kJ/mol 
nonbonded exceptions from openmm and charmm36.xml 126
potential energy from parmed system -241.376513105 kJ/mol
nonbonded exceptions from parmed openmm system 243
```

**Comment by swails** [comment]
There should be 3 exceptions per water: 3\*37 = 111 water exceptions.  The methanol should have 6\*5/2 = 15 exceptions.  So there should be 126 exceptions total.  The OpenMM number is correct.  But the energy is NaN... why is that?  Is that because of the negative epsilons that you just fixed?

I had never noticed this before because I had only ever compared energies, and those always came out correct.  But the 243 that you get from ParmEd still looks OK -- that is equal to 126 (the same number OpenMM gives) + 117 (the number of atoms).  Clearly [my algorithm](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L2355-L2373) is excluding each atom with itself (which you can verify by looking at the actual exclusions).  Maybe OpenMM should flag this, but it makes no difference in the actual energy and force calculation.

**Comment by ChayaSt** [comment]
> But the energy is NaN... why is that? Is that because of the negative epsilons that you just fixed?

Yes, it was NaN because of the negative epsilon. The energies still don't match up and I am still trying to figure out where the problems are.

**Comment by swails** [comment]
So it would be *nice* if ParmEd didn't exclude atoms from themselves, but that's purely cosmetic.  So I'll label this as a minor defect for the time being.
