### ISSUE TITLE
segment gets changed when splitting PSF file

### ISSUE THREAD

**Issue by ajasja** [ParmEd/ParmEd#651]
Hi!

I'm trying to split a PSF file.
I'm using version 2.1.10.

```python
import mdtraj as md
import parmed as pmd

t=md.load("TLR-flag.pdb",top='TLR-flag.psf')
p_ind = t.top.select("segname TLR")

cf=pmd.load_file('TLR-flag.psf')
cf[p_ind].save('test1.psf', vmd=True)
```

The segment name changes from `TLR` to `SYS`. Is this intended or a bug?

Examples are attached: [TLR.zip](https://github.com/ParmEd/ParmEd/files/193710/TLR.zip)

**Comment by swails** [comment]
Ideally, ParmEd should not lose information.  I'll look into why this is happening.

**Comment by hainm** [comment]
may be parmed can add 

```python
cf.take(atom_indices, keep_segid=True)
```

The slicing `cf[p_ind]` does not keep segid info.

**Comment by ajasja** [comment]
@swails The funny thing is that if I save the whole psf (so `cf.save('tets.psf', vmd=True)`) then the segids are preserved. So [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/psf.py#L133) the `atom.residue.segid` is not available (but I don't know why)

@hainm I would expect the slicing to keep the segid info by default.

**Comment by hainm** [comment]
> but I don't know why

no worry, @swails always know the answer. :D 

> I would expect the slicing to keep the segid info by default.

ah yes.

**Comment by ajasja** [comment]
@swails Aha, got it:
When the atom is added [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L903) the segid is not passed. (this also appears in several other places)

**Comment by swails** [comment]
That's exactly what I was expecting it to be.  I'm fixing it now.

As for the `pwd` module -- that is Unix only.  I need to find an alternative for Windows.  Perhaps it would be helpful if I got appveyor running...

Thanks for the report!

Also, your hack seems entirely reasonable.  IMO, CHARMM segid and the CHAIN ID are the same thing, except CHARMM clearly didn't want to be limited by the 26-chain, 1-letter limit :).  I'll implement your suggested change when I have time, or you can file a PR yourself.  Let me know what you'd like to do.

**Comment by swails** [comment]
OK.  I opened PRs to address both issues you raised here.  When they pass, I'll go ahead and merge them in.  If you can, give them a try and see if they work?

Thanks!

**Comment by ajasja** [comment]
@swails 
>Also, your hack seems entirely reasonable. IMO, CHARMM segid and the CHAIN ID are the same thing.

I'm not entirely sure this is true; i've always thought of seg-ids as another layer in the hierarchy.  So one could have chains A, B and C with segid PRT and chains D and F with segid MEM.

Also, [PDB files](http://deposit.rcsb.org/adit/docs/pdb_atom_format.html#ATOM) have both a chainID and a segID.

**Comment by swails** [comment]
> I'm not entirely sure this is true; i've always thought of seg-ids as another layer in the hierarchy. So one could have chains A, B and C with segid PRT and chains D and F with segid MEM.
> 
> Also, PDB files have both a chainID and a segID.

Where did that PDB file format spec come from? [This is the one I've always gone off of](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM), and SEGID is not there.  Both versions are hosted on the RCSB, although the one you linked to is a bit more hidden than the one I've always used.  Also, the PDBx/mmCIF format [has no SEGID either](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Categories/atom_site.html), so I'm inclined to follow the guide at www.wwpdb.org/documentation/file-format-content.

In my experience, I've never seen a PDB file from RCSB or wwPDB contain both CHAIN and SEGID, although I'll mine the PDB and see if this is really the case.  And I'd never really paid much attention to the chain ID from CHARMM PDB files, only the SEGIDs.  Moreover, I've typically seen CHARMM PDB files utilize SEGIDs the same way chains are utilized in PDB files -- at least for proteins and nucleic acids.  For other moieties, like lipids, chain IDs are less convenient to use (and this is where I've seen chains and segments differ in practice).  But I don't have much experience with CHARMM files outside of a handful of examples of different kinds of systems from CHARMM-GUI.

That's why, when only one or the other is available, ParmEd uses them interchangeably where necessary (PSF files contain SEGID but no chain while most PDB files contain chains but no SEGID).  Obviously when both are specified (as in some PDB files), ParmEd stores them both and uses the appropriate one in each case (I've never considered them identical, but if they were a venn diagram, the circles would be almost coincident :smiley:).

**Comment by ajasja** [comment]
>Where did that PDB file format spec come from?
Honestly I just googled "PDB ATOM record specification" and it was the first hit:)

>That's why, when only one or the other is available, ParmEd uses them interchangeably where necessary 
You're right, I think that's the correct way.
