### ISSUE TITLE
TypeError: __init__() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#670]
Hi,

so I blindly try to use ParmEd to load LES parm7 + rst7 file. Then swapping atoms and then saving to new parm7 + rst7 files (call 'new.parm7', 'new.rst7')

Reloading cause the error in the title

```python

import parmed as pmd
pmd.load_file('new.parm7', 'new.rst7')

```

files: https://github.com/hainm/amber_things/tree/master/things/parmed/LES

PS: just dummy try. My point here is to have better error message.

**Comment by swails** [comment]
Turns out LES prmtops are not really supported...

What's happening here is that `pmd.load_file` tries to load `new.parm7` as an `AmberParm` instance.  But that fails because it doesn't know how to handle LES topologies.  So, failing that, it falls back and tries to load it as an `AmberFormat` instance so you at least have access to the data.  While that would work, `AmberFormat` does not take a restart file argument like `AmberParm` and friends do.  Which is why you get the error you see.

One of the downsides of `parmed.load_file` is that it handles such a vast array of file types that concise error reporting is difficult (e.g., a `TypeError` does not even come close to telling you what went wrong in the general case).  So basically what you're stuck doing is doing a separate `except` block for each type of exception you see, then parsing the contents of the message to figure out what you think went wrong and transforming that into a more informative error message.  That's both ugly and fragile.  My approach of letting any exception bubble up means you get a traceback that can tell you exactly what went wrong post-mortem.

Naturally I'd love better error messages, but I don't see a clear way to do that well here.  I'd love for someone to prove me wrong, though.

**Comment by hainm** [comment]
> Turns out LES prmtops are not really supported...

you meant not supporting writing LES? ParmEd reads the original file without error: https://github.com/hainm/amber_things/blob/master/things/parmed/LES/orig/4lztab.parm7

**Comment by swails** [comment]
As an AmberParm, or an AmberFormat?  Of course it'll work as an AmberFormat -- that doesn't try to load any Structure stuff.  It just reads the data into dictionaries.

**Comment by hainm** [comment]
```python
In [1]: pmd.load_file('4lztab.parm7')
Out[1]: <AmberParm 2451 atoms; 273 residues; 2469 bonds; PBC (orthogonal); parametrized>
```

**Comment by swails** [comment]
Then what the heck happened to `new.parm7`??

**Comment by hainm** [comment]
```python
In [4]: import parmed as pmd

In [5]: from random import shuffle

In [6]:

In [6]: tn, rst7 = "4lztab.parm7", "4lztabH.rst7"

In [7]: parm = pmd.load_file(tn, rst7)

In [8]: indices = list(range(len(parm.atoms)))

In [9]: shuffle(indices)

In [10]:

In [10]: nparm = parm[indices]

In [11]: nparm.save('new.parm7', overwrite=True)

In [12]: nparm.save('new.rst7', overwrite=True)

In [13]: tn, rst7 = 'new.parm7', 'new.rst7'

In [14]: pmd.load_file(tn, rst7)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.2-py3.5-linux-x86_64.egg/parmed/amber/amberformat.py in parse(filename, *args, **kwargs)
    352         try:
--> 353             return LoadParm(filename, *args, **kwargs)
...
```

**Comment by hainm** [comment]
another type of error

```python
In [25]: len(parm.atoms)
Out[25]: 2451

In [26]: len(indices)
Out[26]: 2451

In [27]: len(parm[indices].atoms)
Out[27]: 2450
```

**Comment by swails** [comment]
```
> In [4]: import parmed as pmd
> 
> In [5]: from random import shuffle
> 
> In [6]:
> 
> In [6]: tn, rst7 = "4lztab.parm7", "4lztabH.rst7"
> 
> In [7]: parm = pmd.load_file(tn, rst7)
> 
> In [8]: indices = list(range(len(parm.atoms)))
```
This doesn't do what you think it does.  Atoms cannot be reordered by the selection arrays, so if this was a selection array it would simply select every atom in the structure and change nothing. However, as is described [here in the docs](http://parmed.github.io/ParmEd/html/structure.html#structure-manipulation-slicing-combining-replicating-and-splitting), whenever a selector array is the same size as the number of atoms in a structure, it is interpreted as a mask array.  Meaning it keeps all "truthy" values.  Since `range(len(parm.atoms))` contains the boolean equivalent of `[False, True, True, ..., True]`, the resulting `Structure` will have 1 fewer atoms than the original (indeed this is what you observe, which is not really an error, but intentional and documented behavior).  Normally it'd be the first atom, but you shuffled it to who-knows-where, so *some* atom will be stripped out, I'm just not sure which one.  Nobody would *actually* attempt to do what you just did here :).

```
> In [9]: shuffle(indices)
> 
> In [10]:
> 
> In [10]: nparm = parm[indices]
> 
> In [11]: nparm.save('new.parm7', overwrite=True)
> 
> In [12]: nparm.save('new.rst7', overwrite=True)
> 
> In [13]: tn, rst7 = 'new.parm7', 'new.rst7'
> 
> In [14]: pmd.load_file(tn, rst7)
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> /home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.2-py3.5-linux-x86_64.egg/parmed/amber/amberformat.py in parse(filename, *args, **kwargs)
>     352         try:
> --> 353             return LoadParm(filename, *args, **kwargs)
```
Does this happen only with LES topologies, or with any kind?

**Comment by hainm** [comment]
> Does this happen only with LES topologies, or with any kind?

likely happen with normal parm7 too. (I just tried the code with tz2.nc and tz2.parm7 in cpptraj)

```python
$ cat try2.py
import parmed as pmd
from random import shuffle

tn, rst7 = "tz2.parm7", "tz2.nc"
parm = pmd.load_file(tn, rst7)

indices = list(range(len(parm.atoms)))
shuffle(indices)

nparm = parm[indices]
nparm.save('new.parm7', overwrite=True)
nparm.save('new.rst7', overwrite=True)

tn, rst7 = 'new.parm7', 'new.rst7'
pmd.load_file(tn, rst7)
```

Error:
```python
Traceback (most recent call last):
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/amberformat.py", line 353, in parse
    return LoadParm(filename, *args, **kwargs)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/readparm.py", line 70, in LoadParm
    parm = parm.view_as(AmberParm)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/amberformat.py", line 420, in view_as
    return cls.from_rawdata(self)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 259, in from_rawdata
    inst.initialize_topology()
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 203, in initialize_topology
    self.fill_LJ()
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 786, in fill_LJ
    lj_index = pd["NONBONDED_PARM_INDEX"][ntypes*i+i] - 1
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try2.py", line 15, in <module>
    pmd.load_file(tn, rst7)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/formats/registry.py", line 150, in load_file
    return cls.parse(filename, *args, **kwargs)
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/ParmEd-2.4.5-py3.5-linux-x86_64.egg/parmed/amber/amberformat.py", line 355, in parse
    parm = AmberFormat(filename, *args, **kwargs)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by swails** [comment]
ok, I have to figure out why this is breaking the prmtop, then.
