### ISSUE TITLE
Mol2Error: String conversion trouble: could not convert string to float: '844.7490-1166.7730'

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#694]
should ParmEd try to parse `'844.7490-1166.7730` as `'844.7490 -1166.7730`

file: https://github.com/hainm/amber_things/blob/master/things/parmed/mol2/1W9.mol2

This file is legit since it is output from antechamber. pytraj/cpptraj can parse it.

**Comment by hainm** [comment]
Q: Why don't use pytraj?
A: tease ParmEd

**Comment by swails** [comment]
> This file is legit since it is output from antechamber.

Antechamber printing it does not make it legit.  In fact, this violates the standard, which dictates whitespace-delimited tokens on data lines.  See here: http://www.tripos.com/data/support/mol2.pdf

Antechamber should be fixed (I'd suggest reporting this to the dev list or to Dave).

> pytraj/cpptraj can parse it.

And it gets the coordinates right?

**Comment by hainm** [comment]
> And it gets the coordinates right?

yes.

mo2 lines

```python
     15 O1P      1051.9760  845.1750-1167.6330 o         1 1W9     -1.130333
     16 O2P      1053.8180  843.4970-1167.0570 o         1 1W9     -1.130333
     17 O3P      1053.5250  845.6080-1165.6500 o         1 1W9     -1.130333
     18 C4A      -222.9790 -183.0700  246.9560 c2        1 1W9     -0.205000
     19 C5A      1052.0120  844.7080-1163.4520 c1        1 1W9      0.201000
```

pytraj/cpptraj
```python
[ 1051.976   845.175 -1167.633]
[ 1053.818   843.497 -1167.057]
[ 1053.525   845.608 -1165.65 ]
[-222.979 -183.07   246.956]
[ 1052.012   844.708 -1163.452]
```

**Comment by hainm** [comment]
> Antechamber should be fixed (I'd suggest reporting this to the dev list or to Dave).

@dacase: I ping you here for this issue from antechamber: 1W9.mol2 was generated from amber_library (phenix).

**Comment by davidlmobley** [comment]
Just because simulation package x (or antechamber) can do something with a
file does not mean it is valid. Especially egregious are things which treat
pdb as space delimited and mol2 as fixed width. :) If another tool violates
the format it should be fixed.

**Comment by drroe** [comment]
> pytraj/cpptraj can parse it.

Weird - `sscanf()` (which is what cpptraj uses under the hood here) is probably seeing the '`-`' characters and treating them as delimiters which is why parsing works in this case. Replace that with a digit (i.e. the coords are positive and an order of magnitude larger) and I guarantee parsing will fail. Bottom line is that this mol2 file does not conform to the standard, and the program that originally generated it should be fixed so that the digits are properly delimited.

**Comment by hainm** [comment]
@all: I actually did not know that antechamber violated the format. :D

**Comment by swails** [comment]
Man I'm behind the times.  

> Weird - sscanf() (which is what cpptraj uses under the hood here) is probably seeing the '-' characters and treating them as delimiters which is why parsing works in this case.

Yes.  I know that `sscanf` does this.  You are telling it to parse floating point numbers, so when it sees something like ``0.1 0.2-0.3`` and told to parse 3 floats, it does the unambiguous thing.  Note, though, that as soon as you do ``0.1 0.210.3``, `sscanf` will choke.

My first thought when you said pytraj and cpptraj parsed those mol2 files was "I bet that's because it's using sscanf".

So cpptraj and pytraj parse those files "correctly" by accident.  The file is broken, and antechamber should use a format string like `%8.4f %8.4f %8.4f` instead of `%9.4f%9.4f%9.4f` (or whatever it does).  If it was as simple as switching to `sscanf` in Python, I'd do it.  But it's not, so I'm leaving it alone.

**Comment by dacase** [comment]
On Wed, Apr 20, 2016, Hai Nguyen wrote:

> > Antechamber should be fixed (I'd suggest reporting this to the dev 
    list or to Dave).

OK: I think we can squeeze in a fix to ensure that records in mol2 files
created by antechamber are white-space delimited.  This should be in 
AmberTools16, whose release is coming very soon.

Thanks for those to found this and brought it to my attention.

....dac

**Comment by swails** [comment]
Ah!  I forget that you're active here now...  I'll try and remember to just tag you in threads I think you may find of interest.

**Comment by swails** [comment]
It looks like @dacase fixed this in Amber.  I'll go ahead and close this.
