### ISSUE TITLE
Prmtop can't be opened by Parmed (ParmError: Added parm must be Structure or a subclass)

### ISSUE THREAD

**Issue by jaimergp** [ParmEd/ParmEd#705]
Hi,

I can't open this PRMTOP file with ParmEd loader, but the one in OpenMM can. I've tried with both the command line program and the Python API. Any clue?

Thank you!

[sys.prmtop.zip](https://github.com/ParmEd/ParmEd/files/248620/sys.prmtop.zip)

**Comment by swails** [comment]
Your topology file is truncated.  Have a look:

```python
>>> import parmed as pmd
>>> pmd.amber.AmberParm('sys.prmtop')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.5.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 182, in __init__
    self.initialize_topology(xyz, box)
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.5.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 213, in initialize_topology
    self.load_structure()
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.5.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 479, in load_structure
    self.load_atom_info()
  File "/scratch2/miniconda/envs/py35/lib/python3.5/site-packages/ParmEd-2.5.0-py3.5-linux-x86_64.egg/parmed/amber/_amberparm.py", line 538, in load_atom_info
    atom.solvent_radius = radii[i]
IndexError: list index out of range
>>> # Now just load the data
... fmt = pmd.amber.AmberFormat('sys.prmtop')
>>> fmt.parm_data['POINTERS'][0] # number of atoms
111414
>>> len(fmt.parm_data['ATOM_NAME']) # consistent
111414
>>> len(fmt.parm_data['RADII']) # oops...
38770
```

And `RADII` is the last section of your topology file.  ParmEd reads everything from the prmtop in and loads all of the data into its core data structure.  OpenMM loads all of the information as strings into a dict of arrays and processes it only when it needs specific data.  If you tried to do a GB calculation, you would see that OpenMM gives you the same IndexError (at least I think).

The simple solution is to just delete every line in the file from `%FLAG RADII` to the bottom.  ParmEd will fill the data with zeroes, and you can set the radius set to whatever you want if necessary (using `parmed.tools.changeRadii`).  This is necessary to use the prmtop in sander or pmemd (since Amber requires the RADII section to always be present).

What's more worrying to me is how did your file get truncated?  I don't think that RADII is usually the last flag in a topology file, so what other flags are missing from that prmtop?  How did you make this prmtop?

**Comment by swails** [comment]
For more information, the reason you get "must be a `Structure` subclass" is because `parmed.amber.LoadParm` tries to figure out what "kind" of topology file a specific file is.  There are 3 variations: "traditional" Amber topology file, "chamber"-style Amber topology file (which has a different electrostatic constant and some additional potential energy terms, like improper torsions, modified 1-4 L-J terms, and CMAPs), and an AMOEBA-style topology file. There are also files of the same format that don't fit into any of the categories -- specifically the "mdl" files used in RISM.  So if `LoadParm` runs into any problems trying to load the file as any of those 3 different formats, it falls back to loading an `AmberFormat` object which just stores the raw data in a dict of arrays.  But `AmberFormat` is not a subclass of `Structure` (unlike `AmberParm`, which is).

And the parmed command-line program is really primarily aimed at modifying chemical structures, which is why it complains when it is passed something it thinks isn't one.

**Comment by jaimergp** [comment]
Hi @swails. Thanks for your prompt answer. Really appreciate it!

This prmtop comes from one of my colleagues here in Barcelona. According to her, all she does is load a PDB of the protein in xleap, solvate it with `solvatebox` and then generate the prmtop and inpcrd. She also mentions a `leaprc` that contains the amber99sb forcefield and a couple of frcmods to handle metal ions and custom residues.

Maybe the missing radii correspond to the water atoms? I am checking it right now.

**Comment by swails** [comment]
Once upon a time there was a bug in tleap that occasionally resulted in truncated files (although typically it was inpcrd files).  See update.2 for AmberTools 14 (http://ambermd.org/bugfixesat.html).

I'd suggest making sure that all updates are applied to Amber and try again.  Or if she's already using AmberTools 15, send the Amber mailing list the input files so we can figure out what the bug is in tleap that is spitting out broken prmtop files.
