### ISSUE TITLE
`save` to file-like object too?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#710]
currently `parm.save` only accept filename but `write_pdb` can accept file-like object.

My Q

- should `save` accept file-like too?

- if not, is `write_pdb` stable API?

I asked this because NGLView can read file-like object. So if ParmEd can write to buffer, I don't need to save to disk first (so NGLView can reload to its own Topology object)

**Comment by swails** [comment]
> should `save` accept file-like too?

That could probably be done.  But I usually think about `save` the same way I think about `load`, and `load` only takes filenames (since it needs to open the file and inspect the beginning contents for each file type it tries to test).  `save` by default uses the file name suffix to determine what kind of file to write, and while this can be overridden there is no "default" file type like there is with cpptraj.

I'm also not positive that all of the supported file types actually accept file handles in their writing routines.  If they do, this would be a fairly trivial change.

> if not, is `write_pdb` stable API?

Yes.  `write_pdb` and `write_cif` are not going anywhere.

**Comment by hainm** [comment]
thanks.
