### ISSUE TITLE
topology file conversion from Gromacs to AMBER

### ISSUE THREAD

**Issue by nachi83** [ParmEd/ParmEd#714]
Hello, 

I have a issue converting the topology from GROMACS to AMBER. I keep running into "GromacsTopologyFile" is not defined error. I used the script given in the documentation for conversion.

from parmed import gromacs, amber, unit as u
gmx_top = GromacsTopologyFile('pmaawaterFE20mer2.top')
gmx_gro = GromacsGroFile.parse('pmaawaterFE20mer2.gro')
gmx_top.box = gmx_gro.box # Needed because .prmtop contains box info
gmx_top.positions = gmx_gro.positions
amb_prm = AmberParm.from_structure(gmx_top)
amb_prm.write("pmaa.top")
amb_inpcrd = amber.AmberAsciiRestart("pmaa.crd", mode="w")
amb_inpcrd.coordinates = gmx_top.coordinates
amb_inpcrd.box = gmx_top.box
amb_inpcrd.close()

Attached is the file I'm trying to convert. 
Thanks.

[files.tar.gz](https://github.com/ParmEd/ParmEd/files/296244/files.tar.gz)

**Comment by swails** [comment]
As the error message says, `GromacsTopologyFile` was never imported into the top-level namespace.  It's part of the `gromacs` subpackage (as is `GromacsGroFile`), so you need to access the objects from their appropriate namespaces.

Specifically, `gromacs.GromacsTopologyFile` instead of `GromacsTopologyFile`.  You can simplify your script quite a bit as follows:

```python
import parmed as pmd

gmx_top = pmd.load_file('pmaawaterFE20mer2.top', xyz='pmaawaterFE20mer2.gro')
gmx_top.save('pmaa.top', format='amber')
gmx_top.save('pmaa.crd', format='rst7')
```

The first line (not including the import) loads the topology, coordinates, and box information into the same `Structure` subclass.  The second line converts it to an Amber topology file and saves it.  The third line converts the coordinates into an Amber coordinate file and saves it.

**Comment by nachi83** [comment]
Thanks Jason.

 I still run into:  GromacsWarning: 40 1-4 pairs were missing from the [ pairs ] section and were set to zero; make sure you know what you're doing! GromacsWarning). I guess my gromacs topology file is missing some information. 

Is there any I can just extract the RB dihedral information into AMBER dihedral form. I have all the other parameters except for the dihedrals.

I want to use OPLS parameters for simulations in AMBER.  I couldn't find most of the parameters in opls_parm.dat. So I'm trying to convert OPLS parameters available in GROMACS to AMBER.

**Comment by swails** [comment]
> I still run into: GromacsWarning: 40 1-4 pairs were missing from the [ pairs ] section and were set to zero; make sure you know what you're doing! GromacsWarning). I guess my gromacs topology file is missing some information.

This is a somewhat complex feature of most force fields.  Nonbonded interactions between atoms separated by one or two bonds is usually ignored completely, as the interactions between those atoms are assumed to be completely described by the bond and angle terms, respectively.  For atoms separated by 3 bonds (which form a dihedral, and would be atoms 1 and 4 if you labeled each of the 4 atoms in a dihedral), the rules are a little more complicated.  Some force fields scale those interactions by a constant factor.  Others design whole new L-J or charge parameters for specifically those pairs.

GROMACS explicitly enumerates all of its exceptions, while Amber derives them implicitly from the bond, angle, and dihedral lists.  What this warning is telling you is that GROMACS omitted several of the 1-4 pairs, which we've found by experimentation is equivalent to setting those terms to zero.  However, it's unusual, hence the warning.

For AMBER, however, ParmEd has to add those extra 40 dihedrals to ensure that they are omitted properly in the nonbonded calculation in AMBER.  If you know this is *supposed* to happen, then you can ignore the warning.  If it's not, you should look into why GROMACS is only spitting out some of the 1-4s and not others. (It could be that it is only omitting 1-4 terms that are supposed to be zero anyway, like degenerate pairs in 4-, 5-, or 6-member rings, for instance).

> Is there any I can just extract the RB dihedral information into AMBER dihedral form. I have all the other parameters except for the dihedrals.

Alas I don't yet have R-B -> standard proper dihedral conversion working yet.  I derived a relationship between the parameters, but for some reason can't seem to get agreement between the two functional forms for either energies or forces.  It's on the back-burner for now, but something I do hope to get to.

In the meantime, I think InterMol has that particular conversion working.  So I would suggest looking into InterMol to do the GROMACS -> AMBER conversion for you.  (InterMol uses ParmEd under the hood to do that conversion, but I believe it will convert the GROMACS topology into a form that ParmEd can consume).  Tagging @mrshirts and @ctk3b, as they are the InterMol experts here.

**Comment by ctk3b** [comment]
@swails do you happen to still have your scratchwork code lying around for doing the RB->proper conversion correctly?

**Comment by swails** [comment]
I never did it "correctly", since the energies didn't match.

I *did* sit down one day to work out the proper coefficients for the expansion, but I tossed it since the energies weren't even close.  What I have in my `rbtorsion` branch is, I think, my brief attempt to copy what InterMol did, but I don't think that worked either.

You can find the code base [here](https://github.com/swails/ParmEd/tree/rbtorsion) (in particular, search for the ``from_rbtorsion`` constructor in `parmed/topologyobjects.py`).

**Comment by swails** [comment]
At one point I had thought of a way to solve this pretty easily with some symbolic algebra program like sympy or mathematica, but that was awhile ago and I've since forgotten it... If I can think of it again, I'll make a note here.

**Comment by mrshirts** [comment]
I think that 'correctly' in this sense meant "in the way that it should be constructed in ParmEd". We can try to look at that branch and get the math working since we have been looking at this in InterMol.

**Comment by dspoel** [comment]
Any comments on the patch (including test) that Paul suggested above?

**Comment by swails** [comment]
I merged it into the branch the PR was submitted to.  I seemingly forgot to post a PR to master, though.  I'll do that now.

**Comment by swails** [comment]
cc #832

**Comment by swails** [comment]
@dspoel and @maaren -- I have merged this change into the master branch.  There's still some work to be done for actually doing the conversion to Amber files, though, since R-B torsions actually need to be converted into proper periodic dihedrals that Amber understands.

I'll add this to the backlog and try to get to it in the next week or two.

Thanks!

**Comment by maaren** [comment]
If you can give us a hint on what needs to be done, I will try to have another look.

**Comment by ctk3b** [comment]
I've taken a stab at this in #837 but there are a few additional concerns as mentioned in the PR.

**Comment by rip4** [comment]
hi there how do i convert amber to gromos? thanks!

**Comment by swails** [comment]
I don’t know. I’ve never used GROMOS before and don’t know anything about their file formats. 

If you know of a way to convert GROMACS to GROMOS, you can use ParmEd to convert  amber to GROMACS and then convert to GROMOS. But ParmEd doesn’t support GROMOS directly.
