### ISSUE TITLE
Missing impropers in conversion

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#716]
Can provide more files as needed.  But I am getting (for a system that runs fine in AMBER) a failure to generate dihedrals in charmm -- appears to be two of them. 

<CODES>: No improper parameters for    10 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    11 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    12 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    21 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    22 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    23 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    24 ( NLTU     C3LTU    CLTU     C3LTU   )
 <CODES>: No improper parameters for    25 ( CALTU    CALTU    CALTU    C3LTU   )
 <CODES>: No improper parameters for    26 ( CALTU    CALTU    CALTU    C3LTU   )
 <CODES>: A TOTAL OF    9 MISSING PARAMETERS

Definitely no impropers are defined for them in the .prm file.  There are parameters defined for permutations of these angles (CALTU C3LTU CALTU CALTU and NLTU C3LTU C3LTU CLTU), but I don't know if that is meaningful.  I'm not a full expert in AMBER prmtop files, so I can't say for sure if those should be there or not -- in AMBER, they are all expressed as dihedrals.  Will try to keep digging comparing to gromacs.

**Comment by swails** [comment]
OK.  This probably comes from my own misunderstanding of how CHARMM matches impropers internally (since there is no fixed order in an improper like there is in a proper torsion).

Basically what needs to be done is to figure out what permutation CHARMM expects to see the impropers specified in, then have ParmEd print the impropers in that permutation.  Internally, ParmEd sorts all impropers into an alphabetically sorted permutation before trying to match impropers, so atom type ordering in an improper definition does not matter with the exception of where the central atom is placed.

**Comment by mrshirts** [comment]
This comment suggests that there may be some difference between the impropers in the topology and the parameter file. ttps://www.charmm.org/ubbthreads/ubbthreads.php?ubb=showflat&Number=12068

Some more here.
https://www.charmm.org/ubbthreads/ubbthreads.php?ubb=showflat&Number=1658

I can try to investigate this if you don't have time (though I'm not sure my time amounts either).

**Comment by swails** [comment]
Can you tell which atom type corresponds to the central one?

If you can post these files somewhere I can download them, I will see what I can figure out.

**Comment by mrshirts** [comment]
Files sent to your gmail.

I think the central atom is correct -- in CHARMM, it's supposed to be first, and the CHARMM improper parameters that have those four atoms start with the same one.  It's a bit hard to tell because of the changes from AMBER to CHARMM in the files.

Actually, I'll send you the AMBER files that these came from, so it will be easier, as well.

**Comment by mrshirts** [comment]
OK AMBER files sent.  Thanks for taking a look at this!

**Comment by swails** [comment]
So I looked at this and CHARMM is clearly not doing what I expected it to do.  As per the improper rules that CHARMM usually (but not always!) follows, I reordered the torsion to put the central atom first in both the PSF and PRM files.  But apparently CHARMM expects all of the impropers in the PRM file to have exactly the same order (or reversed order) as what appears in the PSF (despite the fact that the ordering of the non-central atoms is formally arbitrary).

Rather than guess at what I should do, I really need to ask one of the CHARMM developers for clarification.

In the meantime, a hacky workaround is to add in the "missing" parameters by copying the equivalent parameter in the section and just giving it the expected atom type ordering.  It's ugly, but will implement the behavior ParmEd intends to (and is probably the best we can do for a quick turnaround).  I'll CC you on the email I send to Justin Lemkul.

**Comment by swails** [comment]
OK.  I talked to Justin and he gave me some helpful pointers.  I think I have this fixed (although I had to make some changes to your inp file to provide unit cell dimensions and reduce the total cutoff before the calculation would actually give me energies).

I'll submit the PR in a few seconds.

**Comment by mrshirts** [comment]
Fantastic.  I'll test it out this evening.

> although I had to make some changes to your inp file to provide unit cell
dimensions and reduce the total cutoff

I'll take a look at those issues. The cutoff is something that the
other program
worked fine with, so that's something that will have to be examined, but
the box vector is probably something that I've done wrong.

Thanks again!

**Comment by mrshirts** [comment]
Tested, looks like it's working for me in the wild.
