### ISSUE TITLE
tag name should be consistent

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#751]
to be easily sorted

``` bash
$ git ls-remote --tags https://github.com/parmed/parmed

bb62e774340f15c9eb60dc74e651ff706459fb6f        refs/tags/1.1
49ca425d43228eca6fa1f2b8bb2c0216fa47c257        refs/tags/2.0.5
1f2ee0b63411e9ddfe0f87f94de8cf313d45beee        refs/tags/2.0beta1
9b187500363e69c441ef0e356d601899ce7bfde2        refs/tags/2.5.0
dff51c42a4ff64c0396478e5b77e264a9b33e392        refs/tags/2.5.1
dacd3b9f3dc3bd432fdd9d7eb384726cdcb96540        refs/tags/v1.0
5ff40d2cf3dbc6e95d016fa4c6a1195414486aae        refs/tags/v2.0-beta
2c7c3a4007c05fde54dedbc8d4b22dd352b927d5        refs/tags/v2.0-beta2
c63a2dd23657e2346c3c84627cde463067f0c5b3        refs/tags/v2.0-beta3
9b187500363e69c441ef0e356d601899ce7bfde2        refs/tags/v2.5.0
```

PS: I am working on automated script to detect version based on git tag for conda build.

**Comment by swails** [comment]
It will be from now on... :)  You can simply ignore any tag prefaced with v

**Comment by swails** [comment]
Note that if you are looking to sort tags, you should do so based on time rather than name.  For instance, the tag 2.5.0 will come after 2.10.0 (if there is such a thing), and 2.0 will come before 2.0beta1, even though 2.0 is a later release.

Even with a standardized tag naming scheme, you can't rely on alphabetic sorting to work.  I'm going to close this.

**Comment by hainm** [comment]
Let me check if there is a option to sort by time for

`git ls-remote --tags`
