### ISSUE TITLE
Flags containing Lennard-Jones parameters are left unchanged when two Amber PARM topologies are combined using + operator

### ISSUE THREAD

**Issue by gaborb91** [ParmEd/ParmEd#756]
If two Amber PARM structures are combined using the + operator like parm1 += parm2 in Python code, flags related to Lennard-Jones parameters (NONBONDED_PARM_INDEX, LENNARD_JONES_ACOEF, LENNARD_JONES_BCOEF) in parm2 are ignored. The topology will be incorrect if parm2 has extra atom types or the order of nonbonded parameters is different.

**Comment by swails** [comment]
I think you're right.  The simple fix is to not re-use Lennard-Jones types and live with duplicates in the tables.  The better fix (since it will impact GPU performance potentially) is to make sure every L-J type is unique.

This will be hard to do in a way that preserves off-diagonal modifications to the L-J matrix, but easy to do otherwise.  A reasonable compromise is to look for off-diagonal modifications and take the "easy" way (simply append the Lennard-Jones lists) if they exist and simply recompute the L-J tables if they don't (thereby eliminating duplicates).

I believe as a temporary (and clumsy) workaround you can convert everything to a GROMACS topology, do the addition there, and then convert back (if you need something before I can get to this bug).

**Comment by swails** [comment]
Also, do you have a test case that demonstrates where this actually fails?  That will help me implement a fix faster.

**Comment by gaborb91** [comment]
"topol1 += topol2 ; topol3 = AmberParm.from_structure(topol1)" probably solves the problem if I comment out the "if type(struct) is cls" in block (_amberparam.py) and there are no off-diagonal modifications.
