### ISSUE TITLE
Incorrect charge on an atom after reading to and writing from GROMACS format

### ISSUE THREAD

**Issue by davidlmobley** [ParmEd/ParmEd#791]
I've found a bug of some sort where an atom in a residue ends up with an incorrect charge after writing to GROMACS format (or it has its charge swapped with another symmetry-equivalent atom, or atoms are re-named and re-ordered).

Inputs and outputs are attached, and to reproduce it, please use this:
```python
#!/bin/env python

import parmed
from simtk.openmm.app import PDBFile
import simtk.openmm.app as app

# Load PDB
pdbfile = PDBFile('cyclohexane_ethanol_0.4_0.6.pdb')

# Load AMBER system
parm = parmed.load_file('out.prmtop', 'out.crd')
ambersys = parm.createSystem(nonbondedMethod= app.NoCutoff, constraints = None, implicitSolvent = None)
print(parm.atoms[126].charge, parm.atoms[126].name)


# Save to GROMACS
structure = parmed.openmm.topsystem.load_topology( pdbfile.topology, ambersys, pdbfile.positions )
# Same behavior with this:
#structure = parmed.openmm.topsystem.load_topology( parm.topology, ambersys, parm.positions )
print(structure.atoms[126].charge, structure.atoms[126].name)
structure.save( 'bug.top', overwrite = True, format="gromacs")
structure.save( 'bug.gro', overwrite = True, format = "gro")

# Load GROMACS system
top = parmed.load_file('bug.top')
print(top.atoms[126].charge, top.atoms[126].name)
```

Output is:
```
(-0.07549999670733112, 'C1')
(-0.07549999670733112, 'C1')
(-0.0761, 'C1')
```

As you can see, `C1` in residue `ZBE` (which happens to be cyclohexane) has a charge magnitude slightly less than 0.076 before GROMACS format is involved, and slightly over 0.076 after GROMACS format is involved. This isn't rounding -- the carbon atoms in cyclohexane all have charges of -0.0755 except this one, which is (for some reason) -0.0761. In AMBER, this charge appears to end up on atom 128; after a round-trip from GROMACS, it ends up on atom 126.

@swails , any insights? In my test, this is making it so energies are not identical after conversion to GROMACS format.

[Archive.zip](https://github.com/ParmEd/ParmEd/files/637654/Archive.zip)

**Comment by ctk3b** [comment]
This is happening because of how GROMACS molecule types are combined by default. Looking at your input files, it's somewhat random which carbon gets the different charge. When writing it to GROMACS, all molecules are consolidated to one moleculetype that has the different charge on the same atom each time.

The following should prevent this combining from happening (which I believe should fix your particular issue):
```python
structure.save( 'bug.top', overwrite = True, format="gromacs", combine='all')
```

**Comment by ctk3b** [comment]
This also brings up a somewhat interesting question about default values. As shown here, the default setting has the potential to alter the system in a very opaque way. While the default certainly produces much nicer and more organized .top files, this might be worth changing. We could then add a warning that lets users know about the cleaner output option?

**Comment by davidlmobley** [comment]
> This is happening because of how GROMACS molecule types are combined by default. Looking at your input files, it's somewhat random which carbon gets the different charge. When writing it to GROMACS, all molecules are consolidated to one moleculetype that has the different charge on the same atom each time.

Ahh, this is interesting. It hadn't occurred to me that different instances of the molecules in my inputs could have the charges on different atoms, but now that you mention it, I can see how this could happen.

Your fix does seem to resolve this issue, though now I have a different issue -- I'm getting different nonbonded force exception qq parameters for the interaction of atom 1542 with 1545:
```
NonBondedForce Exception atom (1542, 1545) has charge values of 0.001429 and 0.001191 elementary charge**2, respectively.
```
I don't see why this would be , though I note that the difference between the two is a factor of 0.833 ( @swails ). These are hydrogen atoms on the cyclohexane.

I also find it highly non-intuitive that the `combine='all'` keyword results in my residues NOT being combined, but that's sort of a separate issue.

> This also brings up a somewhat interesting question about default values. As shown here, the default setting has the potential to alter the system in a very opaque way. While the default certainly produces much nicer and more organized .top files, this might be worth changing. We could then add a warning that lets users know about the cleaner output option?

It certainly seems like it is bad whenever the default behavior makes a change which would alter the energy/forces in the system when it is not expected. I'd propose changing how the default option works so that it doesn't result in merging residues in these types of cases (where merging would result in non-equivalent parameters), if that can be done without too much headache.

**Comment by ctk3b** [comment]
`structure.adjusts` are all scaled by 0.8333

`top.adjusts` are all scaled by 1.0

[This is because `structure` does not have  the `defaults` attribute and when that isn't present, the parser only checks dihedrals to look for scaling factors.](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1241-L1272) I believe a sensible fix would be to also iterate over `struct.adjusts` to look for `scee_values` as is done for dihedrals.

**Comment by davidlmobley** [comment]
@ctk3b - this is when I'm comparing the parameters used in one topology/system to the parameters used in the other topology/system using an external tool. So, it's looking at parameters which SHOULD be equivalent, I think.

Wait, no, I see -- you're pointing out that when I save out to GROMACS format, I end up with a fudgeLJ/fudgeQQ of 1 rather than the 0.8333 that should be there, so I get something different when I read back in. What's the fix? (i.e. how would I write a GROMACS file which has the correct scale factors?) 

Presumably this is just an issue with how I'm producing the GROMACS file, as I'm not super familiar with this aspect.

**Comment by ctk3b** [comment]
Under the hood, when you call `structure.save` with `format='gromacs'`, [this function](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1192) gets called. 

The problem is that that function is [looking for the attribute `defaults`](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1241) which doesn't exist for `structure`. So instead it attempts to infer this from dihedral type information but those all have `scee` set to 1.0. 

What I'm suggesting is to additionally loop over `struct.adjusts` to see if we can find any more info about this scaling parameter from there but that strikes me as sketchy fix. I can take a closer look later tonight but maybe @swails has some better suggestions.

**Comment by davidlmobley** [comment]
Hmm, this is odd. I've previously used `structure` fairly extensively to convert AMBER to GROMACS in a way which reproduces energies (i.e. see https://github.com/choderalab/openmoltools/blob/master/openmoltools/utils.py#L558), so I attempted to reproduce what I did there. However, if I do that in this test as follows:
```python
struct2 = parmed.amber.AmberParm( 'out.prmtop', 'out.crd')
gromacs_topology = parmed.gromacs.GromacsTopologyFile.from_structure(struct2)
gromacs_topology.write('out2.top')
```
I get this exception:
```
/Users/dmobley/anaconda/lib/python2.7/site-packages/ParmEd-0+unknown-py2.7-macosx-10.5-x86_64.egg/parmed/gromacs/gromacstop.pyc in from_structure(cls, struct, copy)
   1259                         scnb_values.add(dihedral.type.scnb)
   1260             if len(scee_values) > 1:
-> 1261                 raise GromacsError('Structure has mixed 1-4 scaling which is '
   1262                                    'not supported by Gromacs')
   1263             scee_values = list(scee_values)
```
So it looks like perhaps the issue might be something deeper? 

I did also check that converting a prmtop for a single molecule of cyclohexane into GROMACS format via a `structure` (through the code I linked to above) results in a correct fudgeLJ and fudgeQQ in the topology, so it's not as simple as `structure` just losing these, apparently.

**Comment by davidlmobley** [comment]
(In fact, I think somehow the problem is an issue with the `prmtop` produced as there shouldn't be anything here which has "mixed 1-4 scaling")

**Comment by davidlmobley** [comment]
Hmm, oddly, when I peek at an alternate `cyclohexane.prmtop` which I am not using as part of this setup, the SCEE values are 1.2 everywhere, whereas in the prmtop I've written out here for my full system, the SCEE values are 1.0 for the first few entries and 1.2 later. So maybe the issue is with the `System` I am writing out, even prior to the `prmtop` itself.

How would I inspect my `structure` or OpenMM `System` before writing to AMBER format to troubleshoot? What should I be looking at? (I start with a `System`, then use `parmed.openmm.topsystem.load_topology` to take a Topology, System, and positions and create a `structure`, then I save to AMBER format).

**Comment by ctk3b** [comment]
I was looking at `[d.type.scee for d in structure.dihedrals][:10]` and `[a.type.chgscale for a in structure.adjusts][:10]` to take a peak at the first 10 entries for dihedrals and 1-4 pairs.

**Comment by ctk3b** [comment]
> I get this exception:
> 
> > ```python
> > /Users/dmobley/anaconda/lib/python2.7/site-packages/ParmEd-0+unknown-py2.7-macosx-10.5-x86_64.egg/parmed/gromacs/gromacstop.pyc in from_structure(cls, struct, copy)
> >    1259                         scnb_values.add(dihedral.type.scnb)
> >    1260             if len(scee_values) > 1:
> > -> 1261                 raise GromacsError('Structure has mixed 1-4 scaling which is '
> >    1262                                    'not supported by Gromacs')
> >    1263             scee_values = list(scee_values)
> > ```

Ok so there are at least two issues here:

1. The immediate cause of the error is that the input structure created by loading those AMBER files contains dihedrals with different charge scaling terms (e.g. `struct2.dihedrals[0].type.scee == 1.2` and `struct2.dihedrals[1].type.scee == 1.0`). I'm not terribly familiar with AMBER but if I recall correctly the accounting for 1-4 pairs is different than in GROMACS. I'll have to do a little digging to see how ParmEd parses and stores these but the reason that that error is raised is that GROMACS only has a global charge scaling factor and otherwise you need to specify the actual LJ terms for the pairs you want scaled differently. Right now, the GROMACS code is trying to detect that charge scaling factor simply by looking at all the dihedral types' `scee` attribute. If I understand this correctly, this is a fix that we can make simply by making the GROMACS code a bit smarter about creating specific 1-4 pairs with the appropriate scaled parameters when we encounter a structure with multiple scaling factors.
2. Creating the GROMACS structure from a structure populated directly by AMBER files is not the same as running it through the OpenMM system like you did in your original example. Somewhere along the line information gets lost or mangled.

**Comment by swails** [comment]
Thanks @ctk3b for tracking this down.  Indeed the problem (and it's a bug) is that molecules that are technically different from a FF perspective (due to small differences in charge) are being identified as the same molecule.  The appropriate fix is to distinguish them as different molecules.  The `combine='all'` should be considered a temporary workaround until better molecule distinction is implemented.

> I also find it highly non-intuitive that the combine='all' keyword results in my residues NOT being combined, but that's sort of a separate issue.

It all depends on your point of view, I suppose.  The [docs](http://parmed.github.io/ParmEd/html/api/parmed/parmed.gromacs.gromacstop.html#module-parmed.gromacs.gromacstop) on this method should hopefully clarify the choice.  The `combine` keyword refers to combining multiple molecules together and considering them as a single `moleculetype` (as opposed to considering them separate molecules that can be specified as separate `moleculetype`s).

> What I'm suggesting is to additionally loop over struct.adjusts to see if we can find any more info about this scaling parameter from there but that strikes me as sketchy fix. I can take a closer look later tonight but maybe @swails has some better suggestions.

This is exactly what needs to happen.

> (In fact, I think somehow the problem is an issue with the prmtop produced as there shouldn't be anything here which has "mixed 1-4 scaling")

My suspicion is that it's a precision thing -- I'll have to look into it.  But the way I track the number of unique 1-4 scaling factors I see is by collecting them in a set and looking at the length of that set.  For backing out an OpenMM `System`, I have to compute the scaling factor for each exception by dividing the product of the actual charges by the charge product stored in the exception.  It wouldn't take much to have 0.83333333 and 0.83333332 get calculated that way and yield this error.

> (e.g. struct2.dihedrals[0].type.scee == 1.2 and struct2.dihedrals[1].type.scee == 1.0).

This is a little misleading.  If you check `struct2.dihedrals[1].ignore_end`, I suspect you'll see that it's `True`, which means that scee value is not used (and so should not be accumulated in the variable 1-4 check -- I think I need to fix that).

> If I understand this correctly, this is a fix that we can make simply by making the GROMACS code a bit smarter about creating specific 1-4 pairs with the appropriate scaled parameters when we encounter a structure with multiple scaling factors.

Unless I missed something, GROMACS doesn't allow you to specify charge-specific parameters for exception pairs, does it?  It does for Lennard-Jones (which is required to implement the CHARMM force field), but not for electrostatics?

**Comment by swails** [comment]
One thing I forgot to mention is that the default behavior (`combine=None`) is required for a lot of alchemical calculations in GROMACS (or at least that's what I recall from conversations with @mrshirts).  But an absolute requirement here is that the Hamiltonian not change.  I'm almost certain that molecule equivalence checking (which is only done for single-residue molecules like solvent) only looks at topology and atom names.

**Comment by ctk3b** [comment]
> Unless I missed something, GROMACS doesn't allow you to specify charge-specific parameters for exception pairs, does it? It does for Lennard-Jones (which is required to implement the CHARMM force field), but not for electrostatics?

I believe that's correct - ignore that comment.

**Comment by swails** [comment]
@davidlmobley -- have a look at #794 and see if this fixes the problems you were having (you still need to use `combine='all'` in the GROMACS conversion, since that part is not yet fixed).

**Comment by davidlmobley** [comment]
So, @swails - as noted in #794 , I presently have two problems:
1. Taking my original system to AMBER format and loading it again results in nonbonded energy discrepancies
2. Taking my AMBER system to GROMACS format and loading it again results in nonbonded energy discrepancies due to 1-4 electrostatics

In #794 , I posted a test case to reproduce problem 2. **Here, I'll post a test case to reproduce problem 1.**

python code (which uses `openmoltools` for energy evaluation -- conda installable from omnia -- as I'm not totally clear on how to get a `structure` from a `System` so I don't see how to use your `energy_decomposition_system` function in this case):
```python
import parmed
from simtk.openmm.app import PDBFile
import simtk.openmm.app as app
from simtk.openmm import XmlSerializer
import simtk.unit as unit
import simtk

pdbfile = PDBFile('cyclohexane_ethanol_0.4_0.6.pdb')

# Load SMIRFF system
file = open('smarty_system.xml')
serialized_system_smirff = file.read()
smirff_system = XmlSerializer.deserialize(serialized_system_smirff)
file.close()

# Attempt to put it into AMBER format and re-load
structure = parmed.openmm.topsystem.load_topology( pdbfile.topology, smirff_system, pdbfile.positions )
structure.save('bug4.prmtop', overwrite=True)
structure.save('bug4.crd', format='rst7', overwrite = True)
parm = parmed.load_file('bug4.prmtop', 'bug4.crd')
amber_system = parm.createSystem()

# Do an energy comparison
from openmoltools import *
timestep = 1.0 * unit.femtoseconds
integrator0 = simtk.openmm.VerletIntegrator( timestep )
integrator1 = simtk.openmm.VerletIntegrator( timestep )
platform = simtk.openmm.Platform.getPlatformByName("Reference")
positions = pdbfile.positions
simulation0 = app.Simulation( pdbfile.topology, smirff_system, integrator0, platform = platform )
simulation0.context.setPositions(positions)
simulation1 = app.Simulation( pdbfile.topology, amber_system, integrator1, platform = platform )
simulation1.context.setPositions(positions)
syscheck = system_checker.SystemChecker( simulation0, simulation1 )
groups0, groups1 = syscheck.check_energy_groups(skip_assert = False)
energy0, energy1 = syscheck.check_energies(skip_assert = False)
```

Output:
```
AssertionError: Error, NB energy difference (3665.758201 kJ/mol) is greater than 12.552000 kJ/mol
```

It's entirely possible that there is something wrong with my original OpenMM system which is leading to these issues (and if you have any insight into what that is, it would be much appreciated) though obviously the issues themselves are also problematic as ideally, a "bad" System would be caught rather than just converted inconsistently.

Files attached.
[Archive 3.zip](https://github.com/ParmEd/ParmEd/files/640405/Archive.3.zip)

**Comment by swails** [comment]
I'm looking into this now.  However, just as a quick tip, `parmed.load_file` understands a lot of OpenMM-specific files.  For instance, you can replace

```python
file = open('smarty_system.xml', 'r')
smarty_xml = file.read()
smarty_system = XmlSerializer.deserialize(smarty_xml)
file.close()
```

with

```python
smarty_system = pmd.load_file('smarty_system.xml')
```

:smiley:

**Comment by swails** [comment]
I can't reproduce this problem.  Here is my script:

```python
import parmed
from simtk.openmm.app import PDBFile
import simtk.openmm.app as app
from simtk.openmm import XmlSerializer
import simtk.unit as unit
import simtk

pdbfile = PDBFile('cyclohexane_ethanol_0.4_0.6.pdb')

# Load SMIRFF system
file = open('smarty_system.xml')
serialized_system_smirff = file.read()
smirff_system = XmlSerializer.deserialize(serialized_system_smirff)
file.close()

# Attempt to put it into AMBER format and re-load
structure = parmed.openmm.topsystem.load_topology( pdbfile.topology, smirff_system, pdbfile.positions )
structure.save('bug4.prmtop', overwrite=True)
structure.save('bug4.crd', format='rst7', overwrite = True)
parm = parmed.load_file('bug4.prmtop', 'bug4.crd')
amber_system = parm.createSystem()
```

And here is my output:

```
[('HarmonicBondForce', 42.56419725029097), ('HarmonicAngleForce', 109.54929865539138), ('PeriodicTorsionForce', 381.41869738246396), ('NonbondedForce', 12147.284220929932), ('CMMotionRemover', 0.0)]
[('HarmonicBondForce', 42.564197250290974), ('HarmonicAngleForce', 109.54929866522606), ('PeriodicTorsionForce', 381.4186968652314), ('NonbondedForce', 12147.284217827897), ('CMMotionRemover', 0.0)] 
```

If I use the files in `Archive.3.zip`, these are the results I get:

```python
[('HarmonicBondForce', 42.564197250290974), ('HarmonicAngleForce', 109.54929865797553), ('PeriodicTorsionForce', 381.4186969362977), ('NonbondedForce', 12146.712917653775), ('CMMotionRemover', 0.0)]
[('HarmonicBondForce', 42.564197250290974), ('HarmonicAngleForce', 109.54929857219327), ('PeriodicTorsionForce', 381.4186973163293), ('NonbondedForce', 12146.71290641736), ('CMMotionRemover', 0.0)]  
```

So a little different than the original files you sent me, but still consistent...
