### ISSUE TITLE
+ operator does not combine coordinates

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#793]
e.g:

```python
import parmed as pmd
parm_0 = pmd.load_file('phenol.prmtop', xyz='phenol.crd')
print(parm_0.coordinates.shape)
parm_1 = pmd.load_file('biphenyl.prmtop', xyz='biphenyl.crd')
print(parm_1.coordinates.shape)

# get 
# (13, 3)
# (22, 3)

print((parm_0 + parm_1).coordinates)
# get
# None
```

**Comment by swails** [comment]
This only happens for `AmberParm`.  `Structure` handles it just fine:

```python
In [5]: s1 = create_random_structure(parametrized=False)

In [6]: s2 = create_random_structure(parametrized=False)

In [7]: import numpy as np

In [8]: s1.coordinates

In [9]: s1.coordinates = np.random.rand(10, len(s1.atoms), 3)

In [10]: s2.coordinates = np.random.rand(8, len(s2.atoms), 3)

In [11]: s1.get_coordinates('all').shape
Out[11]: (10, 458, 3)

In [12]: s2.get_coordinates('all').shape
Out[12]: (8, 394, 3)

In [13]: s12 = s1 + s2

In [14]: s12.coordinates
Out[14]: 
array([[ 0.19328492,  0.52010417,  0.21271705],
       [ 0.20222404,  0.18048604,  0.73506185],
       [ 0.13937732,  0.63067637,  0.88359155],
       ..., 
       [ 0.57617134,  0.43426672,  0.48378015],
       [ 0.73578158,  0.48216736,  0.32729413],
       [ 0.54052915,  0.65646154,  0.38967115]])

In [15]: s12.get_coordinates('all').shape
Out[15]: (8, 852, 3)
```

**Comment by hainm** [comment]
> This only happens for AmberParm. Structure handles it just fine:

True.

I got that example when working on doc for visualization

`(parm_0 + parm_1).visualize`

**Comment by swails** [comment]
I have no idea what the heck Python is doing here.  The problem is that in the `Structure.__add__` method, the line `cp = copy(self)` is dispatching to `AmberFormat.__copy__` instead of `AmberParm.__copy__` even though `self` is of type `AmberParm`.  The former (`AmberFormat.__copy__`) does not copy coordinates, while the latter does.

So *why* is Python dispatching to `AmberFormat.__copy__` even though I've explicitly defined an `AmberParm.__copy__`? This makes no sense!!

**Comment by swails** [comment]
I'm dumb.  The `__copy__` I was looking at was from the `Rst7` class.  I see what's happening.
