### ISSUE TITLE
wrong atomic_number for PSF

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#798]
We discussed about atomic_number in several issues but I still do not "feel" a final conclusion about this.
Is that `ParmEd` won't try to guess atomic_number?

Usage case:
```python
In [8]: parm = pmd.load_file('ala3.psf')

In [9]: [atom.mass for atom in parm if atom.atomic_number == 1]
Out[9]: []
```

**Comment by swails** [comment]
The PSF file has atomic masses, so I can use that to guess the atomic number.  HMR could throw that off, but atom names is not really a reliable way with CHARMM files, given that ion naming is madness in CHARMM FFs (SOD for sodium, CLA for chloride, ... what??)

Best thing to do is load RTFs and PRM files.

**Comment by ctk3b** [comment]
Would it make sense to add a `guess_elements` option to `load_file` (defaulting to False and maybe raising a warning) which allows this to then get passed down to all applicable formats? The issue has come up for at least three different formats now (.mol2, .gro and now .psf) and I think for users that know what they're doing, this could be a useful way to get around this.

**Comment by swails** [comment]
I don't think there's a need for `guess_elements`.  I think that the parsers should all just do it.  It's true that this issue has come up for .mol2 and .gro, but the fix for those two was to add element detection to those formats.  (Also note that the .gro detection only became reliable once automatic bond detection was also implemented).  But now those formats just *do* it.

Adding `guess_elements` would then require element guessing to be implemented in the PSF parser, and then I'd have to go back and make it optional in all of the formats that have to guess.

I think the best policy to have is this:

1. If there is a definitive source of element information, use that
2. If not, make the best attempt we can to guess
3. If no reasonable attempts exist, or there is a high propensity for bad guesses for common systems, don't try.

PSF files just happen to be missing element guessing at the moment :)
