### ISSUE TITLE
load_file/save should accept StringIO too?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#813]
to avoid writing temp file if reading output from another program.

`read_PDB` and `write_pdb` do read/write StringIO.

**Comment by hainm** [comment]
updated `save` for the title

**Comment by swails** [comment]
I had originally tried to make `load_file` work with any file-like object.  But not all file-like objects supported `seek(0)`, which would be needed to cycle through each file format and check.

In addition to that, all of the `id_format` functions will need to be modified to accept a file object instead of a string.  IIRC, the complexity started getting out of hand, so I fell back to forcing `load_file` to accept a string.  It would be a nice to have, but perilous to implement.

You shouldn't need this, though.  Most of the parsers *do* take file objects (since `seek` is unnecessary).  So if you know the format that the other program is spitting out (which you should if you're calling it), just call the constructor for the file type that's being generated directly.

> updated save for the title

Probably a good change, but keep in mind that with a `StringIO`, filename extension won't be much use.

**Comment by hainm** [comment]
>> updated save for the title 

> Probably a good change, but keep in mind that with a StringIO, filename extension won't be much use.

cool. I will try to make a PR. We can always specify 'format=' if not able to use file extension.

**Comment by swails** [comment]
You implemented this, didn't you @hainm ?

**Comment by hainm** [comment]
yeah, #815
