### ISSUE TITLE
option to NOT writing TER, MODEL, ...

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#822]
hi,

is it ok to add that to `write_pdb`? Original `pdb4amber` code does have option to not write TER (or MODEL, ...). If not ok, I can just write a small chunk of code to do that in new `pdb4amber` code.

**Comment by swails** [comment]
Not writing `MODEL` is just wrong.  If there's only one frame, no `MODEL`/`ENDMDL` records are printed.  If there are multiple frames, you *must* have that as a delimiter.

As for the `TER` card -- what is the use-case for omitting them?  tleap requires them to prevent linking polymeric residues between chains, so I struggle to see any benefit to omitting them in `pdb4amber` -- a program that by its very name suggests it exists to create Amber-ready PDB files :)

**Comment by hainm** [comment]
Cool. I will remove this stuff in pdb4amber.

**Comment by hainm** [comment]
> As for the TER card -- what is the use-case for omitting them? tleap requires them to prevent linking polymeric residues between chains, so I struggle to see any benefit to omitting them in pdb4amber -- a program that by its very name suggests it exists to create Amber-ready PDB files :)

I reopen this since amber-phenix really need 'noter' option.

From @dacase:
>> If there is a gap, are we not allowed to put TER between?
>
> We cannot have the TER cards, because then LEaP will put Cterminal and
> Nterminal residues before and after, which is not what we want: it is not
> what is actually in the crystal.

pdb4amber has function to detect gaps, if having gaps, it will add `deleteBond` command in leap input.

**Comment by swails** [comment]
I think the consensus is that amber-phenix really *doesn't* need `--noter`, but rather needs a tweak to the TER placement algorithm.  Instead, we *don't* want intra-chain TER cards, but we do want inter-chain TERs still.

I really don't like the idea of adding a `-noter` option, since that's really the wrong behavior for PDB files.  Many programs depend on them being placed correctly, and any tool that breaks with properly-placed TER cards are going to have lots of problems.

Maybe I'm not understanding the original problem, but I think the use-case you reopened this for is fixed by #843.  If so, this can be closed again, I think.

**Comment by hainm** [comment]
Yeah, close now.
