### ISSUE TITLE
Running charmm36 with implicit solvent in openmm

### ISSUE THREAD

**Issue by Yuan-Yu** [ParmEd/ParmEd#833]
I have some question in running simulations in charmm36 forcefield with implicit solvent.
I chose OBC2 as my solvent model but I found that all the OBC2 parameters like "offset radii" and "Scaled offset radii" were hard coded in customgbforces.py. However, it seems that customgbforces.py is for Amber only. The CHARMM group released some document (https://github.com/sunhwan/charmmdoc/blob/master/doc/c39b1/openmm.doc) that mentioned about "USING GBSA OBC2 IN CHARMM/OPENMM". They took the parameter from amber99sb.xml and amber99_obc.xml and then used the parameters in CHARMM/OPENMM.
I am confused about what is the difference between the method in customgbforces.py and CHARMM group.

**Comment by hainm** [comment]
I think this issue should be in `openmm` repo. https://github.com/pandegroup/openmm

**Comment by swails** [comment]
Those GB models were developed for the Amber family of force fields.  I've never tried them with CHARMM, and if you want to use those GB models with the CHARMM force field you will almost certainly have to validate them somehow.

I actually don't think OpenMM is the right forum to post -- this question is best asked to the CHARMM community, since they will have more experience with their force fields than us.
