### ISSUE TITLE
Problem with converting psf to prmtop

### ISSUE THREAD

**Issue by alzdorev** [ParmEd/ParmEd#847]
Dear ParmEd user community,

I am new in working with ParmEd. I am trying to convert CHARMM topology file (psf) to AMBER (prmtop). I am writing in the interpreter:

> !!
py >>> import parmed as pmd
py >>> psf = pmd.load_file('dodec_wb_ion.psf')
py >>> psf.save('amb.prmtop')
py >>> !!

And receive the following error:
AttributeError: 'NoneType' object has no attribute 'idx'

Could you tell me please what am I doing wrong?

Thank you in advance

**Comment by swails** [comment]
That's certainly the hard way around!

Use the `chamber` command.  The particular problem here is that the PSF file does not contain any parameters, so the code to actually load the parameters into the PSF file has a few more steps.

Use `help chamber` to get more information:

```
bash$ parmed 

 _~__________________
 |_|_______________|_|
 |  ,-------------.  |
 | |  .---------.  | |
 | |  |P        |  | |
 | |  | a       |  | |
 | |  |  r      |  | |
 | |  |   m  ED |  | |
 | |  `---------'  | |
 | `---------------' |
 |   _ ParmedBoy     |
 | _| |_         ,-. |
 ||_ O _|   ,-. "._,"|
 |  |_|    "._,"   A |
 |    _  _    B      |
 |   // //           |
 |  // //    \\\\\\  |
 |  `  `      \\\\\\ ,
 |________...______,"
 
ParmEd: a Parameter file Editor


Reading input from STDIN...
> help chamber
chamber -top <RTF> -param <PAR> [-str <STR>] -psf <PSF> [-crd <CRD>] [-nocmap]
        [-box a,b,c[,alpha,beta,gamma]|bounding] [-radii <radiusset>]
        [nosettle]

    This action will read CHARMM parameter, topology (RTF), and stream (STR)
    files and apply those parameters to a structure defined in a CHARMM PSF
    (protein structure file). XPLOR, CHARMM, and VMD-generated PSF files are all
    supported. You may specify -top, -param, and -str as many times as you want
    to provide multiple parameter files. All topology files are read first (in
    the order they are specified), followed by all parameter files, and finally
    all stream files are read in.  Topology files are only necessary if the
    parameter files do not define the atom types (newer CHARMM force fields
    define atom types directly in the parameter file. Environment variables and
    shell wild-cards (* and ?), as well as the home shortcut character ~ are
    properly expanded when looking for files.

    Options
    -------
        - -top        CHARMM topology, or Residue Topology File (RTF) file
        - -param      CHARMM parameter file
        - -str        CHARMM stream file. Only RTF and parameter sections read
        - -toppar     CHARMM topology, parameter, and/or stream file(s). File
                      type is detected from extension (or in the case of .inp
                      files, the presence of 'top', 'par' in the name)
        - -psf        CHARMM PSF file
        - -crd        Coordinate file (PDB, CHARMM CRD, Amber restart, etc.)
        - -nocmap     Do not use any CMAP parameters
        - -box        Box dimensions. If no angles are defined, they are assumed
                      to be 90 degrees (orthorhombic box). Alternatively, you
                      can use the word 'bounding' to define a box that encloses
                      the centers of all atoms.
        - -radii      Implicit solvent solvation radii. <radiusset> can be
                      amber6, bondi, mbondi, mbondi2, mbondi3
                      Same effect as the changeRadii command. Default is mbondi.
        - nosettle    This avoids changing the names of the water residue and
                      oxygen atoms from TIP3 and OH2 to WAT and O

    If the PDB file has a CRYST1 record, the box information will be set from
    there. Any box info given on the command-line will override the box found in
    the crd file.
    
> 
```

**Comment by alzdorev** [comment]
Thank you for your answer.

But now I have some problems with using chamber.
I use a psf file of Dickerson Dodecamer without water and ions generated by psfgen in VMD. Parameter files I use from CHARMM37 force field, the same parameter files as I used for generating psf.
When I run commands

> chamber -top top_all36_na.rtf  -param par_all36_na.prm  -psf dodec.psf

> outparm amb.prmtop

it successfully creates file amb.prmtop.

Then I load this file into VMD and get the following error

AMBER 7 parm read error at flag section TITLE,
      expected flag field TITLE but got CTITLE

I change the flag CTITLE to TITLE in file amb.prmtop manually, and VMD opens it.

But this file does not define the DNA structure, i.e. in VMD console it is written:
Info)    Atoms: 758
Info)    Bonds: 0
Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
Info)    Residues: 758
Info)    Waters: 0
Info)    Segments: 1
Info)    Fragments: 758   Protein: 0   Nucleic: 0

So chamber has converted the file dodec.psf to amb.parmtop in the wrong way. 


Could you please tell me what's wrong? All the necessary files I attach here:  
[files.zip](https://github.com/ParmEd/ParmEd/files/834580/files.zip)

Thank you

**Comment by drroe** [comment]
This is a problem with the VMD Amber topology parser. CTITLE is written instead of TITLE when the topology contains CHARMM parameters. VMD doesn't currently appear to recognize Chamber topologies. To use this topology for viewing in VMD you can remove the CHAMBER info with cpptraj, using e.g. the following input:
```
parm amb.prmtop
parmwrite out vmd.amb.prmtop nochamber
```

**Comment by swails** [comment]
In addition to what @drroe said -- just use the PSF file instead of the prmtop in VMD.

The chamber file that is generated will *only* work in sander and pmemd (and OpenMM through ParmEd).  Note that the `vmd.amb.prmtop` file will likely "work", but you will get meaningless answers since it won't include all terms in the CHARMM force field.  That file is for visualization only.

**Comment by alzdorev** [comment]
Thank you very much for fast answers. Actually I need to convert a psf file to prmtop to analyse trajectory file produced by NAMD in Curves+ program. Curves+ needs a topology file in prmtop format. So I need a .prmtop file which can be recognized by Curves+.

**Comment by swails** [comment]
You need to follow Dan's suggestion

**Comment by swails** [comment]
To recap here, a chamber-style topology file has modified formatting (slightly) that will make it fail in programs expecting a "standard" Amber topology file.  This is a feature, since it will error in situations where it would otherwise do wrong things silently and (perhaps worst of all) subtly.

ParmEd will not print out an Amber-ized CHARMM prmtop file since that file is useless for simulation and cpptraj already does it :).  If you *can* use the PSF file (e.g., in VMD), then use that.  If you *can't* (either because `chamber` had to reorder atoms in the system or you're using a program like curves++ that will read only prmtop files), you need to use cpptraj according to @drroe's suggestion to create a compatible prmtop file.  Just remember _**NOT**_ to use that file for simulations.

I'm going to go ahead and close this, since I think everything has been addressed.  If not, either reopen (if it's the same topic) or create a new issue.
