### ISSUE TITLE
Contributing a LAMMPS datafile writer?

### ISSUE THREAD

**Issue by avirshup** [ParmEd/ParmEd#862]
A developer with my group (@dane1122) has been using a ParmEd Structure to create LAMMPS data files - [the code is here](https://github.com/Autodesk/molecular-design-toolkit/blob/4e8813e724120d62d3cda86dcaa060b3e5775147/moldesign/models/lammps_model.py#L181). We've only got the datafile _writer_ (no reader), but I'd be very happy to adapt it for contributing into ParmEd, if it would make sense on your end. If this sounds reasonable, let me know, and I'll start putting together a PR.

**Comment by mrshirts** [comment]
Right now, InterMol both reads and writes LAMMPS (https://github.com/shirtsgroup/InterMol), which we've been using to add onto AMBER for so it might make sense to back up and see where to go with it.  Since Jason Swails isn't actively developing right now, it complicates adding new things.

Since there appears to be a commitment from MolSSI to push through file interconversion (through extension/merging some combination of InterMol and ParmEd), it might make sense to wait a little bit to see where we want to go.  That might not be until early June, however. If we want to have some discussions SOONER than that to see how AutoDesk might want to be involved, we can certainly try to accelerate the discussion.

**Comment by avirshup** [comment]
@mrshirts - Ah right, of course :). Sorry, I was in code cleanup mode today - was looking to contribute the conversion code to a better long-term home. But there's definitely no rush, happy to let this stuff sit until the InterMol/ParmEd plan gets worked out. The long-term plan for us is definitely to move to InterMol anyway ...

**Comment by swails** [comment]
Hi @avirshup -- thanks for contacting!

As @mrshirts mentioned, my new job provides limited time to power ahead as quickly with ParmEd as I once did, but I'm still contributing some features and fixing bugs these days (and recent contributors are really picking up the slack here).

My current understanding is that efforts are aimed at tying ParmEd and InterMol together by allowing the two programs' main data structures to interconvert easily between each other.  Fortuitously, neither program overlaps very heavily -- InterMol supports GROMACS, LAMMPS, and Desmond while ParmEd supports AMBER, CHARMM, GROMACS, and OpenMM.  Each program has so many quirks as to how they implement things that it seems unlikely (at least in the near future) for either program to subsume the functionality of the other.

Given where things currently are, I think the best way forward for providing any kind of LAMMPS support through ParmEd is by going through InterMol.  Anything else would likely result in code less likely to be supportable or maintainable.  That said, I'm happy to help where I can in the efforts to tie everything together, so please feel free to keep me in the loop on these efforts so I can help as much as I can.

And of course, I'm always happy to accept additions and fixes to ParmEd.

Thanks!

**Comment by avirshup** [comment]
@ctk3b @swails: Thanks guys - yeah, I'm sure the InterMol converter will be a lot more general and robust than what we've written, which is for a fairly narrow use case. So I agree, our best course is to wait patiently for new superpowers from the ParmEd/InterMol integration.

**Comment by mrshirts** [comment]
I'll try to accelerate some of the conversations with MolSSI people over the next couple of weeks.  I have hunch that otherwise things won't get worked out until the interoperability meeting in June.

**Comment by avirshup** [comment]
Closing this for now :)

**Comment by mkrompiec** [comment]
Any progress since then? I tried InterMol for conversion of OPLS-AA systems (obtained from LigParGen. First OpenMM-> GROMACS with ParMed, then  GROMACS->LAMMPS in InterMol. Unfortunately, I got utter garbage, and it wasn't ParMed's fault (because using GROMACS itp and gro files generated with LigParGen gave a similar result). It seems that InterMol is written for a specific use case (quite different than mine). BTW that snippet from Autodesk's Molecular Design Toolkit wasn't better (=completely scrambled dihedrals).

**Comment by ahy3nz** [comment]
The [package mbuild](https://github.com/mosdef-hub/mbuild/blob/master/mbuild/formats/lammpsdata.py) has some functionality to write out parmed structures to lammps datafiles. It has some support for some basic functional forms. If you can convert your OpenMM or Gromacs files into a `parmed.Structure` object, you could try using the `mbuild.formats.lammpsdata.write_lammpsdata` function

**Comment by mrshirts** [comment]
If you can attach files and a code snippet showing how you called it, I can take a look.   In theory, it should work; GROMACS -> LAMMPS generally works OK.  Hard to know what the problem is from the issue so far.

**Comment by mkrompiec** [comment]
@ahy3nz Thanks, I will try mbuild.
@mrshirts Thank you very much for your response. I used the convert.py script:
python /path/convert.py --gro_in benzene_opls.gro benzene_opls.top --lammps
I obtained the GROMACS files from LigParGen (the .itp needed a tiny edit to make it a system composed of a single molecule). Attached are my input & output files, as well as a "reference" LAMMPS file from LigParGen. From what I understood, InterMol incorrectly interpreted torsions as being of multi/harmonic style (instead of opls). 


[benzene_test.zip](https://github.com/ParmEd/ParmEd/files/3682615/benzene_test.zip)

**Comment by mrshirts** [comment]
So, I guess I'm not sure what the specific problem is.

I made the .gro file bigger so it could get processed by Gromacs to compute the energy (just changed the box from 1.0 to 10.0 large. 

I then ran python /path/convert.py --gro_in benzene_opls.gro benzene_opls.top --lammps -e so I could see the energies.   The output was:

Energy group summary
=======================================================================
                type     input(gromacs)   output (lammps)     diff (lammps)
-----------------------------------------------------------------------
Not comparable energies: are likely not to be the same
-----------------------------------------------------------------------
        coulomb (LR)         8.71242559        0.00000000       -8.71242559
        coulomb (SR)         4.93277988        0.00000000       -4.93277988
       coulomb total        13.11181391       73.34026071       60.22844680
          coulomb-14        -0.53339155        0.00000000        0.53339155
              proper         0.00000000        0.00000000        0.00000000
            vdw (LR)        -0.00010551       -0.00035320       -0.00024769
            vdw (SR)        -0.81414483        0.00000000        0.81414483
           vdw total        22.16825262       22.16765158       -0.00060105
              vdw-14        22.98250296        0.00000000      -22.98250296
-----------------------------------------------------------------------
Comparable energy terms: these should be very close
-----------------------------------------------------------------------
               angle         0.10386529        0.10386529       -0.00000000
                bond         0.89428568        0.89428569        0.00000001
              bonded         0.99815097        0.99815098        0.00000001
            dihedral         0.00000000        0.00000000        0.00000000
           nonbonded        35.28006654       35.29209439        0.01202786
           potential        36.27821750       36.29024533        0.01202783

---------------- Total Potential Energy Comparison --------------------
Input gromacs potential energy:            36.27821750
Difference in potential energy from gromacs=>lammps conversion:         0.01202783
=======================================================================

This seems about as good as one would expect (nonbonded differences can happen for a number of reasons). 

There's a number of different ways that torsions can be represented, so it might not look like the one expected, but the energies match.

**Comment by mkrompiec** [comment]
@mrshirts I am sorry, you are absolutely right, and I shouldn't have jumped to conclusions. The only source of the "garbage" I got before was my own mistake: different ordering of atoms in coordinate and topology files in my test case (box of 500 benzene molecules), due to confusion of coordinate files from two different parametrizations.

**Comment by mrshirts** [comment]
Yeah, the design of InterMol is that the design choice is that only the energies are "guaranteed" (i.e. if no bugs!) to be the same, since there are many input files that represent equivalent systems (i.e. perturbing all of the atom numbers is still the same system physically, and there might be multiple functional forms that are mathematically equivalent).
