### ISSUE TITLE
After pickling, can't create OpenMM system from AmberParm object

### ISSUE THREAD

**Issue by avirshup** [ParmEd/ParmEd#874]
This seems very similar to the other issue I opened (#839), except now it's with pickling instead of copying. I get this error with both 2.7.3 and the current master head (ParmEd-2.7.3+155.g43c0723).

To reproduce: (using [this prmtop file, e.g.](https://github.com/ParmEd/ParmEd/files/789266/prmtop.zip)):
```python
import parmed, pickle

struc = parmed.load_file('prmtop')
pickled_struc = pickle.loads(pickle.dumps(struc))

struc.createSystem()  # succeeds
pickled_struc.createSystem()  # raises AttributeError
```
It raises ~the same~ a similar exception to #839 , `AttributeError: 'AmberParm' object has no attribute 'LJ_radius'` I assume this has to do with `__getstate__` not returning some Amber-topology-specific variables?

Happy to fix it if you can point me to where the fix should go.

**Comment by avirshup** [comment]
It _appears_ that this can be fixed in my case by calling `pickled_struc.initialize_topology()`, but I'm not sure if that's generally applicable or not.

**Comment by swails** [comment]
What you're looking for here is the `__setstate__` implementation: https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/_amberparm.py#L2131-L2133

That defines how objects get unpickled, so if `initialize_topology` needs to be called, you can just add the line

```python
self.initialize_topology()
```

to the end of `__setstate__` to make sure that's triggered at the end of reconstructing the object.

This also could be happening because `LJ_radius` (and similar dicts) don't get packaged in the pickled dictionary, so adding it there would be another way to address this issue.

If you have time to add a test case that reproduces this bug (preferably with one of the files already in the test directory) and submit a PR to fix it, that would be awesome.  If not, I'll try to get to it this weekend when I have a chance.

Thanks for the report!

**Comment by avirshup** [comment]
OK, sounds good - I'll at open a PR to at least add tests for this, and hopefully it will contain a working fix as well :)
