### ISSUE TITLE
Order of atom indices in improper dihedrals in openmm

### ISSUE THREAD

**Issue by mattwthompson** [ParmEd/ParmEd#881]
I'm trying to figure out why impropers are defined around the third atom from ```getTorsionParameters```

In [this](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L269) chunk of code, the improper is checked around the third atom of the group of four.
```
def _process_dihedral(struct, force):
    ....
    for ii in range(force.getNumTorsions()):
        i, j, k, l, per, phase, phi_k = force.getTorsionParameters(ii)                                                                                                               
        ai, aj = struct.atoms[i], struct.atoms[j]
        ak, al = struct.atoms[k], struct.atoms[l]
        [ ... ]
        improper = (ai in ak.bond_partners and aj in ak.bond_partners and 
                    al in ak.bond_partners)
        [ ... ]
```

I don't know how all engines define it, but [openmm](http://docs.openmm.org/7.0.0/userguide/application.html) defines it around the first atom

> An improper torsion involves a central atom and three others that are bonded to it: atoms 2, 3, and 4 are all bonded to atom 1

As far as I can tell, there's nothing in the [getTorsionParameters](https://simtk.org/api_docs/openmm/api4_1/python/classsimtk_1_1openmm_1_1openmm_1_1PeriodicTorsionForce.html) functions that is aware of whether the dihedral is proper or improper, but it does keep track of the order.

**Comment by swails** [comment]
ParmEd translates exactly what it reads from the openmm System object. 

However, Amber specifies the third atom as the central one, so openmm does the same thing when implementing the Amber force field. 

Did you use the amber force field to create the openmm files?

**Comment by mattwthompson** [comment]
I was building an xml from scratch for use in foyer, which is supposed to rely on openmm/parmed code and not re-invent the wheel. I have barely touched amber, I mostly use gromacs.

Some more search has found a ton of similar issues from the openmm crowd and discussion from a year ago. For my purposes I guess I just need some clarification as to where I should be placing my central atoms in the ```<Improper>``` element. The documentation implies it should be the first index but is not clear. I can't find any recently-updated xml files but at least one older [xml](https://github.com/pandegroup/AMBER-FB15/blob/master/Params/OpenMM/amber-fb15.xml) has some wildcards in class3, which implies that it couldn't be the third index. I'm assuming there's nothing different about the order in the xml and what getTorsionForce returns.

**Comment by swails** [comment]
What force field did you use? Did you use OpenMM's ForceField class? How did you assign the original parameters?

**Comment by swails** [comment]
It looks like you used the Amber FF XML files in the OpenMM distribution as a source of parameters (and therefore OpenMM's `ForceField`, `Modeller`, and `Topology` classes to create the system XML file.

In order to be true to the original reference implementation of the Amber force field, they try to apply the improper ordering the same way the Amber software does (which is setting the central atom 3rd).  ParmEd takes the terms verbatim from the system XML file and translates that into its parameter objects.  If you call `createSystem` on that object and pass in the same coordinates, you should get an identical energy.

I'm not completely clear on what your concern is here.  If it's just that the documentation says the central atom comes first but your observations are that it comes third, then you've stumbled upon one of the very many issues involved with improper torsions and the fact that each class of force field handles them differently.  This is expected behavior.

**Comment by mattwthompson** [comment]
The forcefield I'm trying to build is from a [paper](http://pubs.acs.org/doi/abs/10.1021/jp0362133) and is in the OPLS-AA family. I'm basing it off of foyer's [OPLS-AA XML](https://github.com/mosdef-hub/foyer/blob/master/foyer/forcefields/oplsaa.xml), manually writing the parameters from the paper to the XML. I don't know what to properly call this XML, as I don't think I'm touching Amber in that process (I reference an Amber FF XML file because it showed the element I wanted). I then use foyer's ```Forcefield.appy()``` to generate a parmed structure and write it to GROMACS .gro and .top files.

Indeed my problem seems to come down to software inconsistencies and/or my familiarity with these packages. There doesn't seem to be a parmed issue, so feel free to close if the above is accurate.
