### ISSUE TITLE
convert amber top and crd files into gromacs topology - a system containing carbohydrates

### ISSUE THREAD

**Issue by SoArZn** [ParmEd/ParmEd#883]
Hi,

I wish to convert my amber topology and coordinate files into gromacs format. Thus, I installed parmEd and used the script:

import parmed as pmd 
amber = pmd.load_file('prmtop', 'inpcrd') 
amber.save('gromacs.top') 
amber.save('gromacs.gro') 

but got error shown below: 

raise GromacsError('Structure has mixed 1-4 scaling which is ' 
parmed.exceptions.GromacsError: Structure has mixed 1-4 scaling which is not supported by Gromacs 

My system contains carbohydrates, and the forcefields involved are leaprc.gaff, leaprc.protein.ff14SB and leaprc.GLYCAM_06j-1.

I tried another system without carbohydrates, and it worked fine.

Do you have any idea how I can convert my system with carbohydrates?

Thanks!

**Comment by swails** [comment]
The glycam force field uses a different 1-4 scaling factor than the rest of the Amber force fields do. So if you mix glycam with other components, you wind up with a system in which some 1-4 pairs have an electrostatic scaling factor of 1.0 (between glycam atoms) and others with a scaling factor of 1.2 (between other atom types). 

GROMACS does not support this feature so it's impossible to convert your prmtop into an equivalent set of GROMACS files. Rather than try converting to files that are close (but still systematically wrong in a subtle way) ParmEd throws an error explaining why the conversion can't be done. 

Just to be clear, this is not a ParmEd limitation, it's a GROMACS limitation.

**Comment by SoArZn** [comment]
I see. Thanks for the explanation!
