### ISSUE TITLE
attributes' name needed to be consistent && compiling fail with python3.4

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#90]
hi,

* I just tried installing ParmEd from github with python 3.4.3 and got some errors like:

> File "/home/haichit/anaconda3/lib/python3.4/site-packages/chemistry/charmm/parameters.py", line 429
>     except CharmmFileError, e:
>                           ^
> SyntaxError: invalid syntax

(and other similar error too). It's likely you need to change to "except (CharmmFileError, e):

* I just checked pysander to get class's methods/att.
Some attributes' name are off from convention's name

'has_cmap', 'hasbox', 'hasvels' (why not has_vels, has_box?). 

below is my script:

    import sander as pys
    
    mm = pys.InputOptions()
    qm = pys.QmInputOptions()
    parm = pys.AmberParm("./data/Tc5b.top", "./data/Tc5b.crd")
    
    print (dir(parm)) #parm from <class 'chemistry.amber._amberparm.AmberParm'>

Is this because `chemistry` package depends on/tries to catch other's package attributes' name?

**Comment by swails** [comment]
> (and other similar error too). It's likely you need to change to "except (CharmmFileError, e):

Actually, the Python 3 syntax is (exclusively):

```Python
try:
    something
except MyExceptionType as e:
    something_else
```

The `as` keyword also works in Python 2.6 and 2.7, but I haven't yet committed to dropping support for Python 2.5.  However, this is a very common strategy for supporting both Python 2 and Python 3 in one code base -- code for Python 2, and configure `setup.py` to use `2to3` to compile for Python 3.  How did you install ParmEd?  If you used `python3.4 setup.py install`, then it should have been automatically converted to work with Python 3.

I have Travis regularly testing on both 2.7 and 3.4, so there's no reason it shouldn't be working...

> 'has_cmap', 'hasbox', 'hasvels' (why not has_vels, has_box?).

Because `hasvels` and `hasbox` were attributes that I added a *long* time ago.  There's no good reason why those variables do not follow the convention of `has_cmap`, but I also want to get rid of `hasbox` and `hasvels` altogether and have that replaced with something like `velocities is not None` and `box is not None`.  I just haven't bit the bullet yet.

> Is this because chemistry package depends on/tries to catch other's package attributes' name?

I'm not sure what this means?

**Comment by hainm** [comment]
> If you used python3.4 setup.py install, then it should have been automatically converted to work with Python 3.

I used `python ./setup.py install`
(but the python version is 3.4)

Tried `python3.4 setup.py install` to but getting this

$ python3.4 setup.py install
> running install
> running build
> running build_py
> running build_ext
> running build_scripts
> running install_lib
> byte-compiling /home/haichit/anaconda3/lib/python3.4/site-packages/chemistry/formats/mol2.py >to mol2.cpython-34.pyc
>  File "/home/haichit/anaconda3/lib/python3.4/site-packages/chemistry/formats/mol2.py", line 295
>     except ValueError, e:
>                     ^
> SyntaxError: invalid syntax

> running install_scripts
> changing mode of /home/haichit/anaconda3/bin/xparmed.py to 755
> changing mode of /home/haichit/anaconda3/bin/parmed.py to 755
>  running install_egg_info
> Removing /home/haichit/anaconda3/lib/python3.4/site-packages/ParmEd-15.0b-py3.4.egg-info
> Writing /home/haichit/anaconda3/lib/python3.4/site-packages/ParmEd-15.0b-py3.4.egg-info

`Is this because chemistry package depends on/tries to catch other's package attributes' name?`

--> Oh, I just meant another packge has `hasvels` so you keep your code to follow this to get the att

Hai
