### ISSUE TITLE
Problem creating system from mol2 + frcmod

### ISSUE THREAD

**Issue by stefdoerr** [ParmEd/ParmEd#905]
Is it possible to create a system from a mol2 and an frcmod?
I tried as follows:
```python
m2 = parmed.formats.Mol2File.parse('./mol.mol2')
prm = parmed.amber.AmberParameterSet('./mol.frcmod')
structure = m2.to_structure()
structure.createSystem(prm)
```

Gives following error:
```pytb
/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/parmed/structure.py in omm_bond_force(self, constraints, rigidWater, flexibleConstraints)
   2267                 continue
   2268             if bond.type is None:
-> 2269                 raise ParameterError('Cannot find necessary parameters')
   2270             force.addBond(bond.atom1.idx, bond.atom2.idx,
   2271                           bond.type.req*length_conv, 2*bond.type.k*frc_conv)

ParameterError: Cannot find necessary parameters
```

The mol2 file however does contain order and bond types as far as I can tell:
```
@<TRIPOS>BOND
     1    1    2 1
     2    1   28 1
     3    1   29 1
     4    1   30 1
     5    2    3 1
     6    3    4 ar
     7    3    8 ar
     8    4    5 ar
```

Here are the files if you want to try them 
[files.zip](https://github.com/ParmEd/ParmEd/files/1358972/files.zip)

**Comment by swails** [comment]
mol2 files do not contain any force field information.  There are no parameters.  You have a Structure and a ParameterSet, but you never transfer the parameters to the Structure, so there is no force field defined.

There's really no "assign force field parameters" method on `Structure` to use in this instance, so unless you write your own there's really not much that can be done (and keep in mind that ParmEd also isn't filling in "other" valence terms like angles or torsions).

You really need to use a tool like tleap to create a prmtop and read that into ParmEd.

As what you're trying to do is not supported within ParmEd, I'm going to go ahead and close this.

**Comment by swails** [comment]
One other comment -- the "bond types" in the mol2 file are, at best, useful descriptions.  They mean little in the context of typical force fields and parameters except in the context of very coarse (and usually inaccurate) "universal" force fields).

**Comment by stefdoerr** [comment]
Practically though mol2+frcmod can contain all information needed (topology+parameters) to run a simulation of a single small molecule in vacuum, no? No guessing is required if the frcmod contains all terms (mass, bond, angle, dihedral, improper, nonbonded) which is what a parametrization will give you. `tleap` would just dump all the info in the `prmtop`.

I thought the `.createSystem` would take the parameters from `frcmod` and join them with the topology to create a system. What is the point of passing parameters to `.createSystem` if they have to be already included already in the `Structure`? I might be misunderstanding something here.

**Comment by stefdoerr** [comment]
Ah okay I see we would be missing some forcefield specific info like excluded atoms (and atom radii in case of implicit solvent)

**Comment by swails** [comment]
ParmEd typically doesn't build topology information, and doesn't add anything beyond bonds.  So your `Structure` you get from the mol2 file is missing angles, torsions, cmaps (if applicable), etc.

I have no intention to make ParmEd do that kind of modeling since so many other packages already do it:

* OpenMM
* Amber (tleap)
* CHARMM
* GROMACS
* Tinker
* insert many others here

Each force field does it slightly differently 

> What is the point of passing parameters to .createSystem if they have to be already included in the Structure?

You *don't* pass parameters to `Structure.createSystem` -- [see here](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1934-L1951).  Only for `CharmmPsfFile.createSystem` do you pass parameters ([see here](https://github.com/ParmEd/ParmEd/blob/master/parmed/charmm/psf.py#L431)), and that's because parameters are stored in prm files and the PSF file has *all* of the topology information.  So all ParmEd has to do is a very simple mapping.  But for the other supported programs (OpenMM, GROMACS, and Amber), the topology file has all of the parameters either directly inside it or included (as is the case with GROMACS).

**Comment by swails** [comment]
Excluded atoms are actually pretty simple to do, and ParmEd has routines to build exclusion lists.  It needs to be able to do that, for example, if you decide to remove some topological feature of the system (like an atom, bond, angle, torsion, etc.).

It also has the standard GB radii parameters for each supported GB model [stored inside](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L89-L158), and it uses those assignments if the input `Structure` does not contain that information.

**Comment by stefdoerr** [comment]
Oh! Ok that clarifies it. Many thanks for the detailed response!
