### ISSUE TITLE
Difference between NAMD & Parmed-OpenMM energies

### ISSUE THREAD

**Issue by leelasd** [ParmEd/ParmEd#907]
I have been trying to compare energies between NAMD and Parmed-OpenMM systems for an Arginine tripeptide system. I create PSF and PDB files using VMD and minimized it with NAMD. When I pass the optimized PDB and PSF file to Parmed-OpenMM, the single point energy difference between the two is 2.492990 kcal/mol, it is mainly coming from electrostatic energy (2.455244 kcal/mol). 

I have made sure that coordinates, charges are exactly the same. I have also scaled it with appropriate electrostatic constants. But the difference still seems to persist. Does anyone have an idea why this difference happens? Any insight would be highly appreciated. 

Here are the energies and the files, I used for obtaining these results. 

OpenMM:  3.275131 NAMD:  3.280400 BOND_DIFF: -0.005269
OpenMM: 20.311567 NAMD: 20.283300 ANGL_DIFF:  0.028267
OpenMM:  5.632441 NAMD:  5.619500 TORS_DIFF:  0.012941
OpenMM:  0.901552 NAMD:  0.893400 IMPR_DIFF:  0.008152
OpenMM: -111.596656 NAMD: -114.051900 ELEC_DIFF:  2.455244
OpenMM: 13.263942 NAMD: 13.270300 VDWL_DIFF: -0.006358
OpenMM: -68.212010 NAMD: -70.705000 TOTL_DIFF:  2.492990
[NAMD_vs_OpenMM.zip](https://github.com/ParmEd/ParmEd/files/1373232/NAMD_vs_OpenMM.zip)

**Comment by swails** [comment]
> I have also scaled it with appropriate electrostatic constants.

What does this mean?  You shouldn't need to "scale" any charges.

The energy differences you posted seem a little too large to be identical coordinates, especially if you're using double precision.

What happens if you use either the CPU or Reference platforms?

**Comment by leelasd** [comment]
@swails By scale I meant dividing the Electrostatic energy from gromacs with electrostatic constant from this paper  J Comput Aided Mol Des (2017) 31:147–161 and multiplying with NAMD electrostatic constant.  

Regarding energies, except electrostatic energy other terms differ by < 0.01 kcal/mol, including LJ energies. So I am sure about coordinates being the same. I tried it with CPU platform, it gave me the same energies. 

Just to check what exactly is the electrostatic constant of NAMD, I did an energy minimization of Na+ Cl- system in NAMD & Parmed-OpenMM. For a separation of 3.1 Angstrom between Na+ and Cl-, I got the electrostatic energy of -106.9116 kcal/mol for NAMD and -107.11733 kcal/mol for Parmed-OpenMM. From here if we back calculate electrostatic constant its 331.42596 for NAMD 
332.063692 for OpenMM. 

This is electrostatic constant value is very different from whats reported in that paper for NAMD. Whereas OpenMM electrostatic constant matches Gromacs one as expected. 

I believe this difference in electrostatic constants will blow up when you have a system like mine where there is a net charge of 3. For a simple Na+ Cl- pair the difference is 0.2 kcal/mol.  

What do you think about this?

**Comment by swails** [comment]
You can see NAMD's published constants here: http://www.ks.uiuc.edu/Research///namd/1.5/ug/node67.html

It publishes its electrostatic constant as 332.0636 kcal.A/(mol.e^2), which matches what OpenMM uses.  So something's screwy with NAMD, and I have no idea what that might be.  But the discrepancy between what NAMD documents as its Coulomb constant and what you back-calculated is a good thread to pull on.

**Comment by leelasd** [comment]
I tried with versions 2.7b3 2.10 and 2.12 of NAMD, and all of them gave the same energy of  -106.9116 kcal/mol for NaCl. Which means an electrostatic constant of  331.42596. 

Yes, there is certainly something wrong with NAMD.

**Comment by radakb** [comment]
For NAMD, you probably want to use "fullDirect on" rather than setting a
large cutoff.

Also, I'm a little confused looking at your inputs - are these
minimizations or single point energies? The former is very unlikely to
match between two different programs.

**Comment by swails** [comment]
I agree with @radakb that this is probably just an incorrect setting in NAMD.  It's probably trying to use some flavor of PME.

The kind of calculation you're doing is useful for debugging, but basically *never* done in the context of biomolecular simulations.  So it's not surprising that there are non-obvious default electrostatic settings that would be messing things up.

However, I'm far from a NAMD expert and have little-to-no experience using it at all.  So I won't be any help figuring out the root cause.

**Comment by swails** [comment]
> The former is very unlikely to
> match between two different programs.

This is certainly true, but *all* terms would fail to match, not just electrostatics.

**Comment by leelasd** [comment]
@radakb Oops sorry for the confusing scripts. I am optimizing with NAMD and comparing last step energy with SP energy from Parmed-OpenMM. 

@swails @radakb I tried with `fulldirect on` It did give me the result closer to OpenMM but if you calculate electrostatic constant from it, it is 332.00752 not 332.0636. I agree that this is not relevant for Biomolecular simulations but when I am implementing a  new force field, I need to make sure that everything matches up to at least 2 decimals.

**Comment by radakb** [comment]
Ok - I think we're more on the same page now (thanks for clarifying @swails).

I'm coming at this as mostly a NAMD user. I'm still not sure how you are computing the electrostatic constant, but I can assure you that the hardcoded value is indeed 332.0636. If there is a difference there, it is often because the file format itself uses the constant, rather than the code. You can also recompile NAMD with the constant from a different program.

Can you resend the NAMD scripts that you are using? Please only single point energies and PDB coordinates.

**Comment by leelasd** [comment]
@radakb never mind. When I did a single point calculation of NaCl again at a separation of 3.1 Angstrom it matched with OpenMM (up to 3 decimals). But When I was using the other strategy, as i mentioned above (Optimize and compare the last point of NAMD with SP from OpenMM) it differed, even though coordinates are exactly the same. 

You can check this out. I am attaching the files for SP calculation. Since I couldn't  figure out how to do an SP calculation with NAMD, I am just considering the Step 0 of optimization as my single point.   
[NAMD_OpenMM.zip](https://github.com/ParmEd/ParmEd/files/1376845/NAMD_OpenMM.zip)

**Comment by radakb** [comment]
A single point energy in NAMD can be performed using "run 0"

**Comment by leelasd** [comment]
@radakb Ok !! That worked. I am embaressed

**Comment by radakb** [comment]
No cause to be embarrassed - most MD codes are rather loose with how they
implement their minimizers since they mostly use them for removing bad
contacts. This is easily missed by most users since the procedures often
even have the same name (steepest descent, etc) but the specific details
are rather different.

Glad to hear energies are matching now -- it is very good for the different
codes to get together every now and then to make sure energies and forces
match!
