### ISSUE TITLE
Dihedral types sorted or not?

### ISSUE THREAD

**Issue by stefdoerr** [ParmEd/ParmEd#912]
I was under the impression that dihedral types were sorted in parmed as per: https://github.com/swails/ParmEd/blob/a79adc8541d3156e099ba996febda1babddd3338/parmed/charmm/psf.py#L614 for PSFs
However if I read a prmtop like this:
```python
struct = parmed.load_file(prmtop)
prm = parmed.amber.AmberParameterSet.from_structure(struct)
```
They seem unsorted

```
ipdb> prm.improper_periodic_types
OrderedDict([(('CX', 'N', 'C', 'O'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'CA', 'CA', 'CT'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('2C', 'O2', 'CO', 'O2'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('2C', 'N', 'C', 'O'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('N2', 'N2', 'CA', 'N2'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'CA', 'C', 'OH'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C', 'CT', 'N', 'CX'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CT', 'CV', 'CC', 'NA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CB', 'CT', 'C*', 'CW'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('2C', 'O', 'C', 'OH'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CX', 'O2', 'C', 'O2'), <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C', 'CX', 'N', 'H'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'CA', 'CA', 'HA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C', 'H', 'N', 'H'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'H', 'N2', 'H'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C8', 'CA', 'N2', 'H'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C', 'CA', 'CA', 'HA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'C', 'CA', 'HA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CC', 'NB', 'CV', 'H4'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('NA', 'NB', 'CR', 'H5'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CC', 'CR', 'NA', 'H'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CA', 'CB', 'CA', 'HA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CN', 'CA', 'CA', 'HA'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('CW', 'CN', 'NA', 'H'), <DihedralType; phi_k=1.000, per=2, phase=180.000,  scee=0.000, scnb=0.000>), (('C*', 'NA', 'CW', 'H4'), <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>)])
```

Is this a bug or intended behaviour? (or am I misunderstanding something?)

**Comment by stefdoerr** [comment]
Also I see now that `improper_periodic_types` contains `DihedralType` instead of `ImproperType`?
Something seems fishy here :)
The prmtop is generated by `tleap` directly.

**Comment by stefdoerr** [comment]
[I see now](https://github.com/ParmEd/ParmEd/blob/bbf43f2a209481f4f8e0ccf175d53a0322e51da8/parmed/parameters.py#L239-L251) that diherdals are copied to impropers if `.improper` is `True`. But you don't change the class type meaning that  you have a `phi_k` instead of a `psi_k` which impropers are supposed to have.

**Comment by stefdoerr** [comment]
Ok, as on the first subject I see that amber dihedrals are sorted [excluding the third atom](https://github.com/swails/ParmEd/blob/a79adc8541d3156e099ba996febda1babddd3338/parmed/amber/parameters.py#L698-L701)

So how would you suggest to me matching my impropers with the ones read by parmed? Would I need to make two cases, one for CHARMM and one for AMBER? In the one case sorting all and in the other sorting all except the third? Is there no way of standardizing this inside parmed?

**Comment by stefdoerr** [comment]
Actually it seems like they are totally unsorted in this case (i.e. ('CC', 'NB', 'CV', 'H4')). I guess you don't sort when converting from structure to `AmberParameterSet`.

**Comment by swails** [comment]
Impropers are the biggest pain-point in all of force fields, in my opinion.  Each program handles them slightly differently so there's no way to adopt a single standard that behaves correctly in all cases.

ParmEd largely side-steps this problem entirely by relying on the third-party packages it supports to do the parameter assignment.  For reading parameter sets, it adopts the conventions used by the programs from which the parameter files originated (in Amber, that's ordering atoms 1, 2, and 4 whereas CHARMM files don't even have a common convention at all -- the central atom type is *usually* first, but not always).  The algorithm used in ParmEd has gotten the same parameter assignment that CHARMM gets in all cases I tested, but there very well might be corner-cases that would differ.

Whenever ordering comes from a source *other* than a particular program's parameter file (e.g., a `Structure`), ParmEd keeps that ordering (it only attempts to sort when reading from parameter files).

Another point of clarity (based on comments you seem to have deleted) for the difference between DihedralType and ImproperType.  They differentiate different functional forms rather than the abstract concept of what they are topologically:

* DihedralType is a periodic torsion functional form that Amber uses for both its proper and improper torsions
* ImproperType is a harmonic torsion functional form that CHARMM uses for its impropers

The naming is a little unfortunate and is a consequence of ParmEd's early development (first as an Amber topology parser and later adding CHARMM support before aiming to become more program-agnostic).

**Comment by stefdoerr** [comment]
Yes, sorry, I deleted them because I understood the naming.

Okay I see, so in the case that I read a `prmtop` file I should not order my types at all and just keep the same order as the dihedral atoms in the file. I guess this requires 3 cases. 

But practically if you are detecting the central atom can't we just standardize it inside parmed to have the central atom first and at writing reorder to whatever each software wants? What would we lose in that case?

**Comment by swails** [comment]
> But practically if you are detecting the central atom can't we just standardize it inside parmed to have the central atom first and at writing reorder to whatever each software wants? What would we lose in that case?

Honestly I'm not sure.  I needed to read (and sort) parameters from parameter files for a very small number of applications.  For CHARMM and GROMACS, that was parameter assignment.  For AMBER, that was to write frcmod files from prmtops and translate force field files to OpenMM format.  I had tried to define a single standard way of ordering impropers, but I could never get all of my use-cases to work.  The problem is that parameter files do not always adhere to a strict convention that the central atom is in a specific place (e.g., CHARMM), which makes picking a single standard quite difficult.

It could be that I just never quite persevered enough, and that I could have eventually gotten it to work.  However, it was such a tiny (and, as I judged it, unimportant) aspect of ParmEd that it never warranted the time I estimated it would have taken.  That said, I feel like I have fixed a *lot* of improper-related corner cases over the years, so there's also the concern of throwing out too much hard-learned knowledge that I have since forgotten about.  There are a lot of test cases, but not too many integration test cases that I know about from other packages that rely heavily on this functionality.

**Comment by stefdoerr** [comment]
Ok I see. Thanks for the insight. What would you thing of adding a `sorted` flag, or even better a sort-index-array in the ParameterSet classes? Then you would not need to handle explicitly the case that the parameters came from a structure. I could even try to implement it if you want.

**Comment by swails** [comment]
If there's a change you'd find helpful, go ahead and raise a PR for it.  If it doesn't break anything (or break any assumptions/conventions that ParmEd uses), I'd be happy to merge it.

That said, I'm not exactly clear on what you're proposing (or perhaps I'm just not sure what that would look like in code).  If you can whip up a demo to clarify that'd be a good place to start the conversation.

**Comment by stefdoerr** [comment]
I unfortunately don't have time now to implement it so I'll close the issue
