### ISSUE TITLE
Why does CharmmParameterSet convert residue and atom names to uppercase?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#919]
@swails : Why does `CharmmParameterSet` convert residue and atom names to uppercase?

The current CHARMM36 parameter set includes both uppercase and mixed-case atom and residue names `TM3P` and Tm3p` which refer to distinct residues/atoms:
* [`toppar/top_all36_cgenff.rtf`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/top_all36_cgenff.rtf) has residue `TM3P`, which is "C5H9O5P 4'-methyl,3'-phosphate tetrahydrofuran (phosphate -2)"
* [`toppar/stream/misc/toppar_ions_won.str`](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/stream/misc/toppar_ions_won.str#L339-L342) has residue `Tm3p`, which is a "Thulium +3 ion"

OpenMM seems to tolerate both `TM3P` and `Tm3p`, considering these as separate entities.

Will it break ParmEd to remove the code that converts CHARMM atom and residue names to uppercase?

**Comment by swails** [comment]
I remember this was a very intentional choice, and I'm pretty sure it followed the realization somewhere that CHARMM was being case-insensitive in some of it's non-CHARMM force field files in particular.  IIRC, it was about atom type names.

Since so many parts of CHARMM were case-insensitive, I figured it was case-insensitive everywhere.

I think it will break parmed to stop upper-casing atom types.  It's probably OK to stop upper-casing residue names.
