### ISSUE TITLE
No scee scnb read from prmtop

### ISSUE THREAD

**Issue by stefdoerr** [ParmEd/ParmEd#921]
This is mostly my curiosity. What lead to parmed not reading the scee and scnb fields in prmtop files and just defaulting to 2/1.2? ([here](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/_amberparm.py#L1434) you check if it has been read but [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/amberformat.py) it's not read). I am curious because I think I have a `tleap` bug which writes zero in those fields causing a `NaN` in acemd but which works great with parmed and openmm as they ignore the field.

**Comment by swails** [comment]
> This is mostly my curiosity. What lead to parmed not reading the scee and scnb fields in prmtop files and just defaulting to 2/1.2?

If they're not there... that's it.  If there *is* a `SCEE_SCALE_FACTOR` or `SCNB_SCALE_FACTOR` section in the prmtop file, it's read in and used.  If there is no section in the prmtop file, it's not used.

> I am curious because I think I have a tleap bug which writes zero in those fields causing a NaN in acemd but which works great with parmed and openmm as they ignore the field.

This isn't a bug, it's a feature :).  I think it's since been reversed, but a value of 0 was applied to all dihedral types assigned to torsions whose end-group interactions were omitted.  So even though those individual terms would be NaN, they'd never actually get used in the calculation of the 1-4 terms.

This way you could identify a buggy implementation -- if you got a NaN, then clearly you were including a term that should have been omitted.

**Comment by stefdoerr** [comment]
Oh! Great I didn't know that about the omissions.

> If there is a SCEE_SCALE_FACTOR or SCNB_SCALE_FACTOR section in the prmtop file, it's read in and used.
Could you point me to the line where the amber reader reads the SCEE_SCALE_FACTOR? I can't find it.

**Comment by swails** [comment]
> Could you point me to the line where the amber reader reads the SCEE_SCALE_FACTOR? I can't find it.

The parser portion is in the `AmberFormat` subclass (`AmberParm` inherits from both `AmberFormat` and `Structure`).  What it does is it parses through the prmtop and packs *every* `%FLAG <FLAG_NAME>` that is found into the `parm_data` dictionary.

[That is done here](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/amberformat.py#L490-L553).  That's the pure Python code that does the reading.  [There is also a C++-optimized reader that is ~3-5x faster](https://github.com/ParmEd/ParmEd/blob/master/src/readparm.cpp) that works basically the same way.

**Comment by stefdoerr** [comment]
thanks!
