### ISSUE TITLE
AmberParameterSet.from_leaprc produces no residues

### ISSUE THREAD

**Issue by bas-rustenburg** [ParmEd/ParmEd#977]
Tagging @jchodera 

Somewhere between parmed 2.7.3 and 3.0.1, this forcefield generator in openmoltools stopped working

`openmoltools.forcefield_generators.generateForceFieldFromMolecules`
https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L346

Stepping through it with the debugger, I can see that the line 
`params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)`
ended up producing a  parameter set without any residues defined. 

Below is a minimal example that can capture the problem for me. Note that this feature of openmoltools depends on openeye, so a license is required to run it.

```py
from openmoltools import forcefield_generators, openeye
from lxml import etree


def check_num_elements(xml, elements: list=None) -> int:
    """Check for elements in an xml file"""
    tree = etree.fromstring(xml)

    results = dict()
    for key in elements:
        results[key] =  len(tree.xpath('/ForceField/Residues/{}'.format(key))[:])

    return results


mol = openeye.iupac_to_oemol("2-(Ethylamino)-1,2-diphenylethanol")

ffxml=forcefield_generators.generateForceFieldFromMolecules([mol], ignoreFailures=False, normalize=False) 
print(ffxml)
results = check_num_elements(ffxml, ["Residue/Atom", "Residue/Bond", "Residue"])
assert results["Residue"] == 1, "There should be 1 Residue."
assert results['Residue/Atom'] >0, "No atoms were found, this template is broken"
assert results['Residue/Bond'] >0, "No bonds were found, this template is broken"
```

The forcefield template only has these contents at the end.
```xml
<ForceField>
  <Info>
    <DateGenerated>2018-04-13</DateGenerated>
  </Info>
  <PeriodicTorsionForce>
    <Improper k1="4.6024" periodicity1="2" phase1="3.141592653589793" type1="ca" type2="ca" type3="ca" type4="ha"/>
  </PeriodicTorsionForce>
</ForceField>
```

**Comment by jchodera** [comment]
Thanks for such a great test case!

CCing @pgrinaway since this happened to me while running Perses too.

One issue is seems to be that you use `normalize=False` here. In that case, even PyMOL refuses to recognize the Tripos-format `mol2` file written, which has weird atom and bond types:
```
...
@<TRIPOS>ATOM
      1 C1          1.4622    1.5826   -4.2713           1 2-(ethylamino)-1,2-diphenyl-ethanol         0.1452
      2 C2          1.5369    1.5268   -5.7592           1 2-(ethylamino)-1,2-diphenyl-ethanol        -0.0952
      3 N1          1.9627    0.3522   -3.6734           1 2-(ethylamino)-1,2-diphenyl-ethanol        -0.8195
...
@<TRIPOS>BOND
     1    1    2 
     2    1    3 
     3    4    5 
...
```
Switching `normalize=True` produces the expected atom and bond types:
```
...
@<TRIPOS>ATOM
      1 C1          1.4622    1.5826   -4.2713 C.3       1 2-(ethylamino)-1,2-diphenyl-ethanol         0.1452
      2 C2          1.5369    1.5268   -5.7592 C.3       1 2-(ethylamino)-1,2-diphenyl-ethanol        -0.0952
      3 N1          1.9627    0.3522   -3.6734 N.3       1 2-(ethylamino)-1,2-diphenyl-ethanol        -0.8195
...
@<TRIPOS>BOND
     1    1    2 1
     2    1    3 1
     3    4    5 ar
...
```
If I enable debugging in ParmEd, the reason the residue is dropped when writing is:
```
/Users/choderaj/github/parmed/ParmEd.jchodera/parmed/openmm/parameters.py:111: UserWarning: Residue MOL contains atom type c3 not found in parameter set and will be dropped.
```
This appears to be because the [`leaprc` file](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L400-L441) being written by `generateForceFieldFromMolecules()` doesn't actually instruct ParmEd to load `gaff.dat` or `gaff2.dat` first!

**Comment by jchodera** [comment]
OK, the issue here is that we want to use our *own* `gaff.xml` or `gaff2.xml` conversions, rather than having ParmEd convert them for us since this would lead to duplicate parameter sets.

The issue must be that ParmEd now refuses to write molecules if parameters are missing. We just need to allow this to be overridden.

**Comment by jchodera** [comment]
This issue was introduced by the [code I added](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L96-L126) in #942 to strip CHARMM water molecules of their non-chemical H-H bonds, which requires we drop residues without defined parameters. 

This can now be overridden by a fix in two parts:
* `parmed`: https://github.com/ParmEd/ParmEd/pull/978
* `openmoltools`: https://github.com/choderalab/openmoltools/pull/275

New bugfix releases of both tools will have to be cut to resolve this.
