### ISSUE TITLE
Possible AmberParm memory leak

### ISSUE THREAD

**Issue by williamdjones** [ParmEd/ParmEd#991]
I have a script that needs to iterate over ~10,000 .prmtop files, and so I open each separately extract the information I need, delete the reference to the AmberParm object, and go about my business. Problem is that over the course of my scripts running time, the estimated time to completion grows (using tqdm), the progress rate gradually slows. Monitoring system resources, I observe that the memory usage continues to grow, even when the AmberParm() objects fall out of scope, it doesn't appear that the memory is being deallocated properly. I have attempted to garbage collect manually (gc), however I still find that there are references to the AmberParm objects even after calling gc.collect() ( I also make the call gc.enable() directly after imports).

**Comment by williamdjones** [comment]
So to be specific, I believe that adding a close() or ability to use with a context manager would be valuable additions.

**Comment by swails** [comment]
There's almost certainly a memory leak in the C++-optimized topology file reader.

The actual parsing routines are fine -- I just checked them (readparm.cpp and readparm.h).  valgrind found nothing and parsing the same file 10000 times never used more than 1 MB of RAM.  However, if I read the same file with `parmed.amber._rdparm.rdparm` 10000 times, I see memory usage explode (like you did).  This screams memory leak.

As a result, the leak is almost certainly in `_rdparm.cpp`.  The good news is that file is small.  However, I haven't worked with the C-API in ages and I have limited time to work on ParmEd, so it may take me a little bit to get to this.  The problem is almost certainly that I'm using the wrong macro somewhere, or I've forgotten a decref in a few places.  Maybe when I'm packing the collections.

As a workaround, you can [modify `AmberFormat.rdparm`](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/amberformat.py#L430) and set the default value of `slow` to `True`.  This will force ParmEd to use the slow (pure-Python) parser, which will sidestep the leak.

It *will* run quite a bit slower, but you may be able to use asyncio or a thread pool (e.g., in `concurrent.futures`) to speed things up a bit.

**Comment by williamdjones** [comment]
That solution, coupled with using multiprocessing, has made life much easier! Thank you for the responsiveness and help!

**Comment by swails** [comment]
@williamdjones this leak should now be fixed (and the C++-accelerated prmtop parsing now releases the GIL which is beneficial for multithreading, but multiprocessing sidesteps the GIL anyway).

If you update to the latest version, the leak you were experiencing should now be gone and the parsing part of your script should now hopefully be ~5x faster than when you forced it to use the pure-Python parser.

Thanks again for the report!
