### ISSUE TITLE
Error - parmed.exceptions.GromacsError: Structure has mixed 1-4 scaling which is not supported by Gromacs

### ISSUE THREAD

**Issue by tarsisferreira** [ParmEd/ParmEd#992]
Hi,

Is there a way to overcome the:

parmed.exceptions.GromacsError: Structure has mixed 1-4 scaling which is not supported by Gromacs

when converting from amber to gromacs?

Thanks

**Comment by swails** [comment]
This is a GROMACS limitation, not a parmed one (to my knowledge). So there’s no workaround.

**Comment by wehs7661** [comment]
Hi, 
I was having the same issue as @tarsisferreira and I found a [paper](https://www.sciencedirect.com/science/article/pii/S2352711018300736) published last year that seemed to address the issue. However, it is not very clear to me how one should use acpype to convert the files given a parm7 file and an rst7 file if the issue ocurrs. I'm wondering if the workaround for the issue is to use tleap to generate a prmtop and an inpcrd file, as mentioned in [this dicussion thread](https://www.researchgate.net/post/SOLVED_How_do_I_use_the_GLYCAM_force_field_parameters_in_an_enzyme_substrate_complex_MD_simulation_in_GROMACS). Since the procedure described in the thread didn't use any parm7 and rst7 file as the inputs, but just a pdb file which was probably the output PDB file generated by GLYCAM, I was not totally confident in it. Also, will the update of acpype be incoporated in ParmEd in the future? Sorry if this is a naive question. Thank you!

**Comment by tarsisferreira** [comment]
Hi @wehs7661,

Just run acpype -p file.prmtop -x file.crd. You'll get a message citing the 1-4 scaling - see bellow.
=========================================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2020-10-24T12:16:34CEST (c) 2021 AWSdS |
=========================================================================================
Converting Amber input files to Gromacs ...
==> Writing GROMACS files

==> Writing GMX dihedrals for GMX 4.5 and higher.

==> Non-default 1-4 scale parameters detected. Converting individually. Please cite:

 BERNARDI, A., FALLER, R., REITH, D., and KIRSCHNER, K. N. ACPYPE update for
 nonuniform 1-4 scale factors: Conversion of the GLYCAM06 force field from AMBER
 to GROMACS. SoftwareX 10 (2019), 100241. doi: 10.1016/j.softx.2019.100241"

> Hi,
> I was having the same issue as @tarsisferreira and I found a [paper](https://www.sciencedirect.com/science/article/pii/S2352711018300736) published last year that seemed to address the issue. However, it is not very clear to me how one should use acpype to convert the files given a parm7 file and an rst7 file if the issue ocurrs. I'm wondering if the workaround for the issue is to use tleap to generate a prmtop and an inpcrd file, as mentioned in [this dicussion thread](https://www.researchgate.net/post/SOLVED_How_do_I_use_the_GLYCAM_force_field_parameters_in_an_enzyme_substrate_complex_MD_simulation_in_GROMACS). Since the procedure described in the thread didn't use any parm7 and rst7 file as the inputs, but just a pdb file which was probably the output PDB file generated by GLYCAM, I was not totally confident in it. Also, will the update of acpype be incoporated in ParmEd in the future? Sorry if this is a naive question. Thank you!
